- README.md
- centraldashboard/base/deployment.yaml
- centraldashboard/base/kustomization.yaml
- centraldashboard/base/role.yaml
- centraldashboard/base/rolebinding.yaml
- centraldashboard/base/service.yaml
- centraldashboard/base/serviceaccount.yaml
- centraldashboard/overlay/add_service_annotation.yaml
- centraldashboard/overlay/kustomization.yaml
- kustomization.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/15)
> add centraldashboard

- pipeline/kustomization.yaml
- pipeline/pipelines-ui/base/kustomization.yaml
- pipeline/pipelines-ui/base/service.yaml
- pipeline/pipelines-viewer/base/kustomization.yaml
- pipeline/pipelines-viewer/base/service.yaml
fixes kubeflow/kubeflow/issues/3143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/35)
> kfctl generate failed with kustomize

- OWNERS
Will help speed up progress on ISTIO and kustomize integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/45)
> add gabrielwen to manifests OWNERS

- common/centraldashboard/base/clusterrole-binding.yaml
- common/centraldashboard/base/clusterrole.yaml
Mirrors the configuration from https://github.com/kubeflow/kubeflow/blob/master/kubeflow/common/centraldashboard.libsonnet.
closes #37 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/47)
> Update centraldashboard roles to match ksonnet files

- pipeline/pipelines-ui/base/kustomization.yaml
- pipeline/pipelines-ui/base/params.env
- pipeline/pipelines-ui/base/params.yaml
- pipeline/pipelines-ui/base/virtual-service.yaml
- pipeline/pipelines-viewer/base/kustomization.yaml
- pipeline/pipelines-viewer/base/params.env
- pipeline/pipelines-viewer/base/params.yaml
- pipeline/pipelines-viewer/base/virtual-service.yaml
Fixes kubeflow/kubeflow#2962
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/43)
> Pipeline UI ISTIO manifests

- jupyter/jupyter-web-app/base/kustomization.yaml
- jupyter/jupyter-web-app/base/params.env
- jupyter/jupyter-web-app/base/params.yaml
- jupyter/jupyter-web-app/base/virtual-service.yaml
Fixes kubeflow/kubeflow#2964
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/39)
> Jupyter ISTIO manifest

- katib/base/katib-ui-virtual-service.yaml
- katib/base/kustomization.yaml
- katib/base/params.env
- katib/base/params.yaml
Fixes kubeflow/kubeflow#2963
/assign @kkasravi @hougangliu 
/cc @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/40)
> Katib UI ISTIO

- common/centraldashboard/base/kustomization.yaml
- common/centraldashboard/base/params.env
- common/centraldashboard/base/params.yaml
- common/centraldashboard/base/virtual-service.yaml
- kubebench/base/kustomization.yaml
- kubebench/base/params.env
- kubebench/base/params.yaml
- kubebench/base/virtual-service.yaml
- tensorboard/base/kustomization.yaml
- tensorboard/base/params.env
- tensorboard/base/params.yaml
- tensorboard/base/virtual-service.yaml
- tf-training/tf-job-operator/base/kustomization.yaml
- tf-training/tf-job-operator/base/params.env
- tf-training/tf-job-operator/base/params.yaml
- tf-training/tf-job-operator/base/virtual-service.yaml
Fixes kubeflow/kubeflow#2261 kubeflow/kubeflow#2978
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/46)
> finish ISTIO configs.

- common/basic-auth/base/gatekeeper-deployment.yaml
- common/basic-auth/base/gatekeeper-service.yaml
- common/basic-auth/base/kflogin-deployment.yaml
- common/basic-auth/base/kflogin-service.yaml
- common/basic-auth/base/kflogin-virtual-service.yaml
- common/basic-auth/base/kustomization.yaml
- common/basic-auth/base/params.env
- common/basic-auth/base/params.yaml
/cc @kkasravi @gabrielwen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/41)
> adds basic-auth

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/64)
> Add myself to OWNERS per Kam's request

- common/basic-auth/base/gatekeeper-deployment.yaml
- common/basic-auth/base/gatekeeper-service.yaml
- common/basic-auth/base/kflogin-deployment.yaml
- common/basic-auth/base/kflogin-service.yaml
- common/basic-auth/base/kflogin-virtual-service.yaml
- common/basic-auth/base/kustomization.yaml
- common/basic-auth/base/params.env
- common/basic-auth/base/params.yaml
- gcp/basic-auth-ingress/overlays/gcp/certificate.yaml
- gcp/basic-auth-ingress/overlays/gcp/cloud-endpoint.yaml
- gcp/basic-auth-ingress/overlays/gcp/cluster-role-binding.yaml
- gcp/basic-auth-ingress/overlays/gcp/cluster-role.yaml
- gcp/basic-auth-ingress/overlays/gcp/config-map.yaml
- gcp/basic-auth-ingress/overlays/gcp/deployment.yaml
- gcp/basic-auth-ingress/overlays/gcp/ingress.yaml
- gcp/basic-auth-ingress/overlays/gcp/job.yaml
- gcp/basic-auth-ingress/overlays/gcp/kustomization.yaml
- gcp/basic-auth-ingress/overlays/gcp/params.env
- gcp/basic-auth-ingress/overlays/gcp/params.yaml
- gcp/basic-auth-ingress/overlays/gcp/service-account.yaml
- gcp/basic-auth-ingress/overlays/gcp/service.yaml
- gcp/basic-auth-ingress/overlays/gcp/stateful-set.yaml
fixes #54, kubeflow/kubeflow/issues/3207
should be paired with kubeflow/kubeflow/pull/3108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/58)
> basic-auth-ingress is missing from gcp

- tests/scripts/run-tests.sh
now `make test` can work, so trigger prow job result (succeed or fail) depending on `make test`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/65)
> enable test

- gcp/iap-ingress/base/jwt-policy.yaml
- gcp/iap-ingress/base/kustomization.yaml
Relates kubeflow/kubeflow#3122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/69)
> JWT policy for IAP ingress

- pipeline/pipelines-ui/base/kustomization.yaml
- pipeline/pipelines-ui/base/service.yaml
- tests/pipelines-ui-base_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/95)
> Fix pipeline UI namespace

- profiles/base/crd.yaml
- profiles/base/role-binding.yaml
- profiles/base/role.yaml
- profiles/base/service-account.yaml
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
fixes #52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/76)
> Change the Role verbs of a Profile user to prevent the user from getting a Profile

- admission-webhook/webhook/base/cluster-role.yaml
- admission-webhook/webhook/base/crd.yaml
- admission-webhook/webhook/base/mutating-webhook-configuration.yaml
- jupyter/jupyter-web-app/base/cluster-role.yaml
- tests/jupyter-web-app-base_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/webhook-base_test.go
resolves https://github.com/kubeflow/kubeflow/issues/3249
related to https://github.com/kubeflow/kubeflow/pull/3320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/94)
> Renamed podpreset to poddefault

- gcp/cloud-endpoints/base/params.env
- gcp/iap-ingress/base/certificate.yaml
- gcp/iap-ingress/base/deployment.yaml
- gcp/iap-ingress/base/job.yaml
- gcp/iap-ingress/base/kustomization.yaml
- gcp/iap-ingress/base/params.env
- tests/cloud-endpoints-base_test.go
- tests/iap-ingress-base_test.go
Fixes #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/103)
> Fix admin-gcp-sa secretName

- pipeline/minio/overlays/minioPd/kustomization.yaml
- pipeline/minio/overlays/minioPd/params.env
- pipeline/minio/overlays/minioPd/params.yaml
- pipeline/minio/overlays/minioPd/persistent-volume-claim.yaml
- pipeline/minio/overlays/minioPd/persistent-volume.yaml
- pipeline/mysql/base/deployment.yaml
- pipeline/mysql/base/kustomization.yaml
- pipeline/mysql/base/params.env
- pipeline/mysql/base/params.yaml
- pipeline/mysql/overlays/mysqlPd/kustomization.yaml
- pipeline/mysql/overlays/mysqlPd/params.env
- pipeline/mysql/overlays/mysqlPd/params.yaml
- pipeline/mysql/overlays/mysqlPd/persistent-volume-claim.yaml
- pipeline/mysql/overlays/mysqlPd/persistent-volume.yaml
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
Fixes #97 
Fixes #100 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/104)
> Fix pipeline storage PVC overlay manifests

- metadata/base/kustomization.yaml
- metadata/base/metadata-db-deployment.yaml
- metadata/base/metadata-db-pvc.yaml
- metadata/base/metadata-db-secret.yaml
- metadata/base/metadata-db-service.yaml
- metadata/base/metadata-deployment.yaml
- tests/metadata-base_test.go
Add config for MySQL used by metadata service.
Update the cmd flags to connect to the mysql database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/107)
> Add config for MySQL used by metadata service

- argo/base/deployment.yaml
- argo/base/kustomization.yaml
- argo/base/params.env
- tests/argo-base_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/108)
> Update Argo version to v2.3.0

- pytorch-job/pytorch-job-crds/base/crd.yaml
- pytorch-job/pytorch-operator/base/deployment.yaml
- pytorch-job/pytorch-operator/base/kustomization.yaml
- pytorch-job/pytorch-operator/base/service.yaml
- tests/pytorch-job-crds-base_test.go
- tests/pytorch-operator-base_test.go
This contains minor version fixes and monitoring config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/125)
> Adding monitoring config to manifests

- gcp/iap-ingress/base/cloud-endpoint.yaml
- gcp/iap-ingress/base/config-map.yaml
- gcp/iap-ingress/base/kustomization.yaml
- gcp/iap-ingress/base/params.env
- gcp/istio-install/base/istio-noauth.yaml
- tests/iap-ingress-base_test.go
- remove the name prefix because components are referencing others, e.g. certificate --> ingress, service --> backendconfig.
For https://github.com/kubeflow/kubeflow/issues/3456
Also fix health check for https://github.com/kubeflow/kubeflow/issues/3459
/cc @kkasravi @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/129)
> Fix error in ingress component

- admission-webhook/bootstrap/base/stateful-set.yaml
- tests/bootstrap-base_test.go
- tests/katib-ui-base_test.go
- tests/katib-ui-overlays-istio_test.go
- tests/metrics-collector-base_test.go
- tests/studyjob-base_test.go
- tests/suggestion-base_test.go
- tests/vizier-core-base_test.go
- tests/vizier-db-base_test.go
fixes #133 
/cc @ashahba
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/134)
> Remove admission-webhook/bootstrap hard-coded selector

- jupyter/jupyter-web-app/overlays/istio/virtual-service.yaml
- pipeline/pipelines-ui/overlays/istio/virtual-service.yaml
- tests/jupyter-web-app-overlays-istio_test.go
- tests/pipelines-ui-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/155)
> fix istio virtual service mismatch

- profiles/base/crd.yaml
- profiles/base/deployment.yaml
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/156)
> Prof crd mismatch

- admission-webhook/webhook/base/deployment.yaml
- admission-webhook/webhook/base/kustomization.yaml
- common/basic-auth/base/gatekeeper-deployment.yaml
- common/basic-auth/base/kflogin-deployment.yaml
- gcp/istio/base/kf-istio-resources.yaml
- jupyter/jupyter-web-app/base/service-account.yaml
- jupyter/notebook-controller/base/deployment.yaml
- tests/basic-auth-base_test.go
- tests/basic-auth-overlays-istio_test.go
- tests/istio-base_test.go
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
- tests/notebook-controller-base_test.go
- tests/notebook-controller-overlays-application_test.go
- tests/notebook-controller-overlays-istio_test.go
- tests/webhook-base_test.go
Update images to latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/158)
> sync manifests with ksonnet config

- OWNERS
This PR adds me (@yanniszark) to the OWNERS file.
cc @kkasravi @jlewi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/160)
> OWNERS: add yanniszark

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
closes #143 
After this PR is merged, we can remove the hold from [kubeflow#3448](https://github.com/kubeflow/kubeflow/pull/3448). After this PR, the current UI will not render the submit form with this new config.
Will need a follow up PR then to update with the new image tag.
/assign @kkasravi 
/assign @yanniszark 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/163)
> jupyter-web-app: Update the manifests

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
To keep in sync with https://github.com/kubeflow/kubeflow/pull/3510
/cc @yanniszark @kimwnasptd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/165)
> Update jupyter web-app image

- profiles/base/kustomization.yaml
- tests/iap-ingress-base_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/162)
> update profile image

- jupyter/notebook-controller/base/kustomization.yaml
- pipeline/pipelines-viewer/base/kustomization.yaml
- pipeline/pipelines-viewer/base/params.env
- pipeline/pipelines-viewer/base/params.yaml
- tests/iap-ingress-base_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/notebook-controller-base_test.go
- tests/notebook-controller-overlays-application_test.go
- tests/notebook-controller-overlays-istio_test.go
- tests/pipelines-viewer-base_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
need a namespace defined in kustomization.yaml so that notbook-controller-role-binding adds a namespace to its subjects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/170)
> Notebook controller fix

- metadata/base/metadata-deployment.yaml
- metadata/base/metadata-service.yaml
- tests/metadata-base_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/168)
> Update metadata image to v0.1.5

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
- tests/metadata-base_test.go
Update the webapps image to use the new UI
/cc yanniszark
/cc kkasravi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/175)
> jupyter-web-app: Update the image tag

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/166)
> update central dashboard

- common/centraldashboard/overlays/application/application.yaml
- common/centraldashboard/overlays/application/kustomization.yaml
- tests/centraldashboard-overlays-application_test.go
fixes #126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/182)
> add centraldashboard application

- OWNERS
IronPan will approve changes mostly only for Kubeflow Pipeline components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/185)
> add IronPan to the approver list

- pipeline/api-service/base/deployment.yaml
- pipeline/api-service/base/kustomization.yaml
- pipeline/persistent-agent/base/deployment.yaml
- pipeline/persistent-agent/base/kustomization.yaml
- pipeline/pipelines-ui/base/deployment.yaml
- pipeline/pipelines-ui/base/kustomization.yaml
- pipeline/pipelines-viewer/base/deployment.yaml
- pipeline/pipelines-viewer/base/kustomization.yaml
- pipeline/scheduledworkflow/base/deployment.yaml
- pipeline/scheduledworkflow/base/kustomization.yaml
- tests/api-service-base_test.go
- tests/persistent-agent-base_test.go
- tests/pipelines-ui-base_test.go
- tests/pipelines-ui-overlays-istio_test.go
- tests/pipelines-viewer-base_test.go
- tests/scheduledworkflow-base_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/184)
> Update KFP manifests to use v0.1.23

- gcp/prometheus/base/kustomization.yaml
- gcp/prometheus/base/params.env
- gcp/prometheus/base/params.yaml
- gcp/prometheus/base/prometheus.yaml
- tests/iap-ingress-base_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/prometheus-base_test.go
fix https://github.com/kubeflow/manifests/issues/183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/187)
> add prometheus monitoring components

- metadata/base/kustomization.yaml
- metadata/base/metadata-deployment.yaml
- metadata/base/metadata-ui-deployment.yaml
- metadata/base/metadata-ui-role.yaml
- metadata/base/metadata-ui-rolebinding.yaml
- metadata/base/metadata-ui-sa.yaml
- metadata/base/metadata-ui-service.yaml
- metadata/base/params.env
- metadata/overlays/istio/kustomization.yaml
- metadata/overlays/istio/params.yaml
- metadata/overlays/istio/virtual-service.yaml
- tests/metadata-base_test.go
- tests/metadata-overlays-istio_test.go
Copy of https://github.com/kubeflow/manifests/pull/188 by @rileyjbauer with unit tests fixed.
Deploy the metadata UI service and configure istio routing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/191)
> Metadata UI manifests

- pipeline/pipelines-ui/base/role.yaml
- tests/pipelines-ui-base_test.go
- tests/pipelines-ui-overlays-istio_test.go
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/199)
> update KFP UI role to launch tensorboard

- katib-v1alpha2/katib-controller/base/kustomization.yaml
- katib-v1alpha2/katib-manager/base/kustomization.yaml
- katib-v1alpha2/katib-ui/base/kustomization.yaml
- katib-v1alpha2/metrics-collector/base/kustomization.yaml
- katib-v1alpha2/suggestion/base/kustomization.yaml
- pytorch-job/pytorch-operator/base/kustomization.yaml
- tests/katib-controller-base_test.go
- tests/katib-manager-base_test.go
- tests/katib-ui-base_test.go
- tests/katib-ui-overlays-istio_test.go
- tests/metrics-collector-base_test.go
- tests/pytorch-operator-base_test.go
- tests/pytorch-operator-overlays-application_test.go
- tests/seldon-core-operator-base_test.go
- tests/seldon-core-operator-overlays-application_test.go
- tests/suggestion-base_test.go
- tests/tf-job-operator-base_test.go
- tests/tf-job-operator-overlays-application_test.go
- tests/tf-job-operator-overlays-istio_test.go
- tf-training/tf-job-operator/base/deployment.yaml
Update v0.6 image for tf-operator; pytorch-operator and katib.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/192)
> update image for v0.6.0

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
/cc @yanniszark @kkasravi @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/201)
> jupyter-web-app: Update the image for PodDefaults

- common/ambassador/base/deployment.yaml
- common/ambassador/base/kustomization.yaml
- common/ambassador/base/service-account.yaml
- common/ambassador/base/service.yaml
- gcp/basic-auth-ingress/base/certificate.yaml
- gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
- gcp/basic-auth-ingress/base/kustomization.yaml
- gcp/basic-auth-ingress/base/params.yaml
- tests/ambassador-base_test.go
- tests/basic-auth-ingress-base_test.go
- tests/iap-ingress-base_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/workflows/app.yaml
- tests/workflows/components/workflows.libsonnet
Resolves https://github.com/kubeflow/kubeflow/issues/3562
Most changes are from https://github.com/kubeflow/kubeflow/pull/3404
Related: https://github.com/kubeflow/kubeflow/pull/3631
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/204)
> fix basic auth

- istio/istio/base/kf-istio-resources.yaml
- istio/istio/base/kustomization.yaml
- istio/istio/base/params.env
- istio/istio/base/params.yaml
- tests/istio-base_test.go
We need to be able to turn on/off Istio isolation.
Like in basic auth case, there's only one user so will turn off network isolation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/209)
> make ClusterRbacConfig configurable

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
Pick up new changes for  jupyter web app: 
https://github.com/kubeflow/kubeflow/commits/master/components
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/214)
> update jupyter web app image

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/215)
> Add myself to manifests OWNERS file

- metadata/OWNERS
Add OWNERS file to metadata/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/218)
> Add metadata OWNERS

- katib-v1alpha2/katib-controller/overlays/application/application.yaml
- katib-v1alpha2/katib-controller/overlays/application/kustomization.yaml
- katib-v1alpha2/katib-db/overlays/application/application.yaml
- katib-v1alpha2/katib-db/overlays/application/kustomization.yaml
- katib-v1alpha2/katib-manager/overlays/application/application.yaml
- katib-v1alpha2/katib-manager/overlays/application/kustomization.yaml
- katib-v1alpha2/katib-ui/overlays/application/application.yaml
- katib-v1alpha2/katib-ui/overlays/application/kustomization.yaml
- katib-v1alpha2/metrics-collector/overlays/application/application.yaml
- katib-v1alpha2/metrics-collector/overlays/application/kustomization.yaml
- katib-v1alpha2/suggestion/overlays/application/application.yaml
- katib-v1alpha2/suggestion/overlays/application/kustomization.yaml
- tests/katib-controller-overlays-application_test.go
- tests/katib-db-overlays-application_test.go
- tests/katib-manager-overlays-application_test.go
- tests/katib-ui-overlays-application_test.go
- tests/metrics-collector-overlays-application_test.go
- tests/suggestion-overlays-application_test.go
Resolves #117 
Add katib application CR
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/225)
> Add katib application CR

- metadata/base/metadata-deployment.yaml
- tests/iap-ingress-base_test.go
- tests/istio-base_test.go
- tests/metadata-base_test.go
- tests/metadata-overlays-istio_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/prometheus-base_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/210)
> Bump metadata version.

- metadata/base/metadata-deployment.yaml
- tests/metadata-base_test.go
cherry pick #210 into v0.6 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/239)
> Update metadata backend version nubmer

- gcp/basic-auth-ingress/base/cloud-endpoint.yaml
- gcp/basic-auth-ingress/base/kustomization.yaml
- gcp/basic-auth-ingress/base/params.env
- gcp/basic-auth-ingress/base/params.yaml
- tests/basic-auth-ingress-base_test.go
- tests/iap-ingress-base_test.go
- tests/istio-base_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
otherwise cloud endpoint controller might not find ingress.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/240)
> add istio namespace for cloud endpoint

- gcp/basic-auth-ingress/base/cloud-endpoint.yaml
- gcp/basic-auth-ingress/base/kustomization.yaml
- gcp/basic-auth-ingress/base/params.env
- gcp/basic-auth-ingress/base/params.yaml
- tests/basic-auth-ingress-base_test.go
Cherry pick #240 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/242)
> Cherry-pick #240 add istio namespace for cloud endpoint

- gcp/basic-auth-ingress/base/cloud-endpoint.yaml
- gcp/basic-auth-ingress/base/kustomization.yaml
- gcp/basic-auth-ingress/base/params.env
- gcp/basic-auth-ingress/base/params.yaml
- tests/basic-auth-ingress-base_test.go
**https://github.com/kubeflow/kubeflow/issues/3702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/244)
> cherry pick #243 patch appName to endpoint

- pytorch-job/pytorch-operator/overlays/application/application.yaml
- pytorch-job/pytorch-operator/overlays/application/kustomization.yaml
- tests/pytorch-operator-overlays-application_test.go
Partially fixes https://github.com/kubeflow/kubeflow/issues/3796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/250)
> Fix Pytorch operator application

- gcp/basic-auth-ingress/base/kustomization.yaml
- tests/basic-auth-ingress-base_test.go
- tests/basic-auth-ingress-overlays-gcp-credentials_test.go
Resolves https://github.com/kubeflow/kubeflow/issues/3828
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/257)
> fix routing under basic auth mode 

- OWNERS
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/258)
> Add zhenghuiwang to OWNERS

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/aws-alb-ingress-controller-base_test.go
- tests/aws-alb-ingress-controller-overlays-vpc_test.go
- tests/aws-efs-csi-driver-base_test.go
- tests/aws-fsx-csi-driver-base_test.go
- tests/basic-auth-ingress-overlays-gcp-credentials_test.go
- tests/cloud-endpoints-overlays-gcp-credentials_test.go
- tests/fluentd-cloud-watch-base_test.go
- tests/iap-ingress-base_test.go
- tests/iap-ingress-overlays-certmanager_test.go
- tests/iap-ingress-overlays-gcp-credentials_test.go
- tests/iap-ingress-overlays-managed-cert_test.go
- tests/istio-ingress-base_test.go
- tests/istio-ingress-overlays-cognito_test.go
- tests/istio-ingress-overlays-oidc_test.go
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/nvidia-device-plugin-base_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/prometheus-base_test.go
Update the jupyter-web-app image tag for [3845](https://github.com/kubeflow/kubeflow/pull/3845)
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/269)
> Update image to 9419d4d

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
Fix #3918
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/280)
> Automated cherry pick of #269: Update image to 9419d4d Cherry pick of #269 on v0.6-branch. #269: Update image to 9419d4d

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
CentralDashboard image made for https://github.com/kubeflow/kubeflow/pull/3933
/area centraldashboard
/priority p1
/assign @avdaredevil
/cc @prodonjs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/282)
> CentralDashboard Image for kubeflow/kubeflow#3933

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/294)
> Automated cherry pick of #282: CentralDashboard image made for Cherry pick of #282 on v0.6-branch. #282: CentralDashboard image made for

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
This release contains all the changes from: 
- https://github.com/kubeflow/kubeflow/pull/3980
- https://github.com/kubeflow/kubeflow/pull/3971
/area centraldashboard
/priority p1
/assign @avdaredevil
/cc @prodonjs @gabrielwen @kunmingg @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/301)
> [CentralDashboard v2] Post kubeflow/kubeflow#3980 changes now in the release

- common/centraldashboard/overlays/application/application.yaml
- jupyter/jupyter-web-app/overlays/application/application.yaml
- jupyter/notebook-controller/overlays/application/application.yaml
Related to: kubeflow/kubeflow#3875
Bump the version in the application specs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/307)
> Bump the application versions to v0.6.2 on the v0.6-branch.

- common/centraldashboard/base/kustomization.yaml
- tests/application-overlays-application_test.go
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
- tests/notebook-controller-overlays-application_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
apply PR #310 to v0.6 branch, and fix a bunch of tests
seems tests on v0.6 branch head is broken
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/311)
> apply PR #310 to v0.6 branch, and fix a bunch of tests

- jupyter/jupyter-web-app/base/kustomization.yaml
- tests/aws-alb-ingress-controller-base_test.go
- tests/aws-alb-ingress-controller-overlays-vpc_test.go
- tests/aws-efs-csi-driver-base_test.go
- tests/aws-fsx-csi-driver-base_test.go
- tests/fluentd-cloud-watch-base_test.go
- tests/istio-ingress-base_test.go
- tests/istio-ingress-overlays-cognito_test.go
- tests/istio-ingress-overlays-oidc_test.go
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
- tests/jupyter-web-app-overlays-istio_test.go
- tests/minio-base_test.go
- tests/minio-overlays-minioPd_test.go
- tests/mysql-base_test.go
- tests/mysql-overlays-mysqlPd_test.go
- tests/nvidia-device-plugin-base_test.go
- tests/profiles-base_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/prometheus-base_test.go
Image built from commit https://github.com/kubeflow/kubeflow/commit/9419d4d7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/320)
> [auto PR] Update the jupyter-web-app image to 9419d4d7

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
Updated version to include fixes from correct versioning and profile communication
/area centraldashboard
/priority p1
/assign @avdaredevil
/cc @prodonjs @gabrielwen @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/310)
> [Central-Dashboard v2] Stable Release - Version and Profile-Server fixes

- gatekeeper/README.md
- gatekeeper/constraint-template.yaml
- gatekeeper/ns-required-annotations.yaml
Resolves https://github.com/kubeflow/kubeflow/issues/3623
Design: https://bit.ly/2yJeU5u
Original PR: https://github.com/kubeflow/kubeflow/pull/3984
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/344)
> Restricting controller access with Gatekeeper

- gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
- tests/basic-auth-ingress-base_test.go
- tests/basic-auth-ingress-overlays-certmanager_test.go
- tests/basic-auth-ingress-overlays-gcp-credentials_test.go
- tests/basic-auth-ingress-overlays-managed-cert_test.go
Resolves https://github.com/kubeflow/manifests/issues/345
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/346)
> allow websocket redirect

- gcp/basic-auth-ingress/base/istio-mapping-svc.yaml
- tests/basic-auth-ingress-base_test.go
cherry pick https://github.com/kubeflow/manifests/pull/346 to v0.6 branch
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/347)
> allow websocket redirect (#346)

- istio/istio/base/kf-istio-resources.yaml
- istio/istio/base/kustomization.yaml
- istio/istio/base/params.env
- istio/istio/base/params.yaml
- tests/istio-base_test.go
we need this for anthos deployment
/cc @richardsliu @abhi-g 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/368)
> parameterize gateway selector

- metadata/base/kustomization.yaml
- metadata/base/metadata-deployment.yaml
- metadata/base/metadata-envoy-deployment.yaml
- metadata/base/metadata-envoy-service.yaml
- metadata/base/metadata-service.yaml
- tests/metadata-base_test.go
- tests/metadata-overlays-application_test.go
- tests/metadata-overlays-istio_test.go
Fixes https://github.com/kubeflow/metadata/issues/127
Updating metadata component to use mlmd gRPC server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/370)
> metadata: Updating metadata component to use mlmd-grpc server

- kfdef/kfctl_anthos.yaml
/cc @richardsliu @abhi-g 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/380)
> kfctl anthos config

- pytorch-job/pytorch-operator/base/deployment.yaml
- tests/pytorch-operator-base_test.go
- tests/pytorch-operator-overlays-application_test.go
- tests/tf-job-operator-base_test.go
- tests/tf-job-operator-overlays-application_test.go
- tests/tf-job-operator-overlays-istio_test.go
- tf-training/tf-job-operator/base/deployment.yaml
Update operator to latest available images
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/394)
> Update operator images to latest

- seldon/Makefile
- seldon/seldon-core-operator/base/Kube-descriptor.yaml
- seldon/seldon-core-operator/base/seldon-config-cm.yaml
- seldon/seldon-core-operator/base/seldon-manager-sa.yaml
- seldon/seldon-core-operator/base/seldon-operator-controller-manager-service-svc.yaml
- seldon/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
- seldon/seldon-core-operator/base/seldon-operator-manager-role-clusterrole.yaml
- seldon/seldon-core-operator/base/seldon-operator-manager-rolebinding-crb.yaml
- seldon/seldon-core-operator/base/seldondeployments.machinelearning.seldon.io-crd.yaml
- seldon/seldon-core-operator/base/webhook-server-service-svc.yaml
- seldon/values.yaml
- tests/seldon-core-operator-base_test.go
- tests/seldon-core-operator-overlays-application_test.go
* Update Seldon to 0.4.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/403)
> Seldon 0.4.1

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
Resolves #
kubeflow/kubeflow#3725
This PR updates the Jupyter notebook images.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/401)
> Add new updated Jupyter notebook images

- argo/overlays/application/application.yaml
- argo/overlays/application/kustomization.yaml
- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
- tests/argo-overlays-application_test.go
Resolves #454
adds the application CR and updates the config files under kfdef
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/455)
> add argo application overlay

- kubebench/overlays/application/application.yaml
- kubebench/overlays/application/kustomization.yaml
- tests/kubebench-overlays-application_test.go
Resolves #464
added application overlay for kubebench
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/465)
> add kubebench application overlay

- kfserving/kfserving-crds/base/crd.yaml
- kfserving/kfserving-install/base/cluster-role-binding.yaml
- kfserving/kfserving-install/base/cluster-role.yaml
- kfserving/kfserving-install/base/config-map.yaml
- kfserving/kfserving-install/base/kustomization.yaml
- kfserving/kfserving-install/base/statefulset.yaml
- kfserving/kfserving-install/overlays/application/application.yaml
- tests/kfserving-crds-base_test.go
- tests/kfserving-install-base_test.go
- tests/kfserving-install-overlays-application_test.go
Resolves https://github.com/kubeflow/kfserving/issues/399
Update kfserving manifests to 0.2.0 for kubeflow 0.7 release.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/461)
> Update kfserving manifests to 0.2.0

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
Fix: #463
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/478)
> Update the centraldashboard image to a newly built image.

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
- kfserving/kfserving-crds/overlays/application/application.yaml
- kfserving/kfserving-crds/overlays/application/kustomization.yaml
- kfserving/kfserving-install/overlays/application/application.yaml
- tests/kfserving-crds-overlays-application_test.go
- tests/kfserving-install-overlays-application_test.go
Resolves #474
```
└── kfserving
├── kfserving-crds
└── kfserving-install
```
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/475)
> add application overlays for kfserving

- gcp/cloud-endpoints/overlays/application/application.yaml
- gcp/cloud-endpoints/overlays/application/kustomization.yaml
- gcp/gpu-driver/overlays/application/application.yaml
- gcp/gpu-driver/overlays/application/kustomization.yaml
- gcp/iap-ingress/overlays/application/application.yaml
- gcp/iap-ingress/overlays/application/kustomization.yaml
- gcp/prometheus/overlays/application/application.yaml
- gcp/prometheus/overlays/application/kustomization.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- tests/cloud-endpoints-overlays-application_test.go
- tests/gpu-driver-overlays-application_test.go
- tests/iap-ingress-overlays-application_test.go
- tests/prometheus-overlays-application_test.go
Resolves #472
```
└── gcp
├── cloud-endpoints
├── gpu-driver
├── iap-ingress
└── prometheus
```
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/473)
> add application overlays for gcp

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
- profiles/overlays/application/application.yaml
- profiles/overlays/application/kustomization.yaml
- tests/profiles-overlays-application_test.go
Resolves #482 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/492)
> Add application overlays for profiles

- aws/aws-alb-ingress-controller/overlays/application/application.yaml
- aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
- aws/aws-alb-ingress-controller/overlays/vpc/kustomization.yaml
- aws/nvidia-device-plugin/overlays/application/application.yaml
- aws/nvidia-device-plugin/overlays/application/kustomization.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- tests/aws-alb-ingress-controller-overlays-application_test.go
- tests/aws-alb-ingress-controller-overlays-vpc_test.go
- tests/nvidia-device-plugin-overlays-application_test.go
Resolves #456
add application overlays for aws/aws-alb-ingress-controller, aws/nvidia-device-plugin
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/458)
> add application overlay to aws-alb-ingress-controller, nvidia-device-plugin

- tests/pipelines-viewer-overlays-application_test.go
- tests/scheduledworkflow-overlays-application_test.go
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/505)
> Fix broken presubmit tests

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
- pytorch-job/pytorch-job-crds/overlays/application/application.yaml
- pytorch-job/pytorch-job-crds/overlays/application/kustomization.yaml
- tests/aws-alb-ingress-controller-overlays-vpc_test.go
- tests/pytorch-job-crds-overlays-application_test.go
- tests/pytorch-operator-overlays-application_test.go
Resolves #483 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/504)
> Add overlays for Pytorch CRDS; update Pytorch version

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
Addresses kubeflow/kfserving#428
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/490)
> Updates KfDefs with kubeflow-roles

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-web-app-base_test.go
- tests/jupyter-web-app-overlays-application_test.go
Resolves #
kubeflow/kubeflow#4267
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/497)
> Update jupyter notebooks image tags

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
- tests/tf-job-crds-overlays-application_test.go
- tests/tf-job-operator-overlays-application_test.go
- tf-training/tf-job-crds/overlays/application/application.yaml
- tf-training/tf-job-crds/overlays/application/kustomization.yaml
Resolves #487 #488 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/507)
> TF Job overlays updates

- kfdef/kfctl_existing_arrikto.yaml
Specify packageManager: kustomize in existing_arrikto.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/519)
> kfdef: existing_arrikto: specify package manager

- gcp/basic-auth-ingress/overlays/application/application.yaml
- gcp/basic-auth-ingress/overlays/application/kustomization.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- tests/basic-auth-ingress-overlays-application_test.go
Resolves #467
added basic-auth-ingress application overlay and updated kfdef/kfctl_gcp_basic_auth.yaml
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/468)
> add gcp basic-auth-ingress application overlay

- common/spartakus/overlays/application/application.yaml
- common/spartakus/overlays/application/kustomization.yaml
- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
- tests/aws-alb-ingress-controller-overlays-application_test.go
- tests/aws-alb-ingress-controller-overlays-vpc_test.go
- tests/nvidia-device-plugin-overlays-application_test.go
- tests/spartakus-overlays-application_test.go
Resolves #479
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/494)
> add application overlay for spartakus

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_existing_arrikto.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_k8s_istio.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/545)
> Update manifest repos and versions for v0.7

- kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
- kfdef/kfctl_gcp_iap.0.7.0.yaml
- kfdef/kfctl_k8s_istio.0.7.0.yaml
Related to kubeflow/kubeflow#3703
Cherrypick of #542 and update the naming for release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/556)
> Cherry pick kfdef v1beta1 for gcp

- kfserving/kfserving-install/base/config-map.yaml
- tests/kfserving-install-base_test.go
- tests/kfserving-install-overlays-application_test.go
Resolves https://github.com/kubeflow/kfserving/issues/479
Sync configmap changes from kfserving repo
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/569)
> Sync configmap changes from kfserving repo

- profiles/base/crd.yaml
- profiles/base/kustomization.yaml
- tests/profiles-base_test.go
- tests/profiles-overlays-application_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/profiles-overlays-test_test.go
pick up https://github.com/kubeflow/kubeflow/pull/4396
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/574)
> update profile API

- gcp/iap-ingress/base/config-map.yaml
- tests/iap-ingress-base_test.go
- tests/iap-ingress-overlays-application_test.go
- tests/iap-ingress-overlays-certmanager_test.go
- tests/iap-ingress-overlays-gcp-credentials_test.go
- tests/iap-ingress-overlays-managed-cert_test.go
Resolves #561
Reset backendName each time so that it will pick up new changes.
**Checklist:**
3. `make test`
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/573)
> reset backend name

- common/centraldashboard/base/deployment.yaml
- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
* kubeflow/kubeflow#4281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/570)
> Update centraldashboard image to fix issue with 2 profiles being created by registration

- profiles/base/crd.yaml
- profiles/base/kustomization.yaml
- tests/profiles-base_test.go
- tests/profiles-overlays-application_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/profiles-overlays-test_test.go
cherry pick profile API change: https://github.com/kubeflow/manifests/pull/574
Orignal issue: https://github.com/kubeflow/kubeflow/pull/4396
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/578)
> update profile API (#574)

- kubebench/base/cluster-role-binding.yaml
- kubebench/base/cluster-role.yaml
- kubebench/base/config-map.yaml
- kubebench/base/crd.yaml
- kubebench/base/deployment.yaml
- kubebench/base/kustomization.yaml
- kubebench/base/service-account.yaml
- tests/kubebench-base_test.go
- tests/kubebench-overlays-application_test.go
- tests/kubebench-overlays-istio_test.go
- fix problems affecting installations
- update image versions
Resolves #216 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/223)
> Fix and update Kubebench manifests

- katib/katib-controller/base/katib-configmap.yaml
- katib/katib-controller/base/kustomization.yaml
- tests/katib-controller-base_test.go
- tests/katib-controller-overlays-application_test.go
- tests/katib-controller-overlays-istio_test.go
Signed-off-by: Ce Gao <gaoce@caicloud.io>
Resolves #
/hold 
/assign @johnugeorge @richardsliu 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/580)
> [0.7] chore: Use v0.7.0 in Katib

- katib/katib-controller/base/katib-configmap.yaml
- katib/katib-controller/base/kustomization.yaml
- tests/katib-controller-base_test.go
- tests/katib-controller-overlays-application_test.go
- tests/katib-controller-overlays-istio_test.go
Signed-off-by: Ce Gao <gaoce@caicloud.io>
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/582)
> [chore] Cherry-pick #580 to v0.7-branch

- README.md
Fix multiple overlays as title
Looks like it should be like this. Needs confirm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/584)
> Fix multiple overlays as title

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
Related: kubeflow/kubeflow#4415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/589)
> update central dashboard image

- common/centraldashboard/base/kustomization.yaml
- tests/centraldashboard-base_test.go
- tests/centraldashboard-overlays-application_test.go
- tests/centraldashboard-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/590)
> Automated cherry pick of #589: update central dashboard image for kubeflow/kubeflow#4415

- OWNERS
- cert-manager/OWNERS
- dex-auth/OWNERS
- istio/OWNERS
- kubeflow-roles/OWNERS
/assign @jlewi @kkasravi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/583)
> Add self to appropriate OWNERS files

- tests/workflows/components/kubeflow_workflow.libsonnet
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/598)
> Automated cherry pick of #596: Remove the tfjob tests. Cherry pick of #596 on v0.7-branch. #596: Remove the tfjob tests.

- gcp/basic-auth-ingress/base/cluster-role-binding.yaml
- gcp/basic-auth-ingress/base/params.yaml
- tests/basic-auth-ingress-base_test.go
- tests/basic-auth-ingress-overlays-application_test.go
- tests/basic-auth-ingress-overlays-certmanager_test.go
- tests/basic-auth-ingress-overlays-gcp-credentials_test.go
- tests/basic-auth-ingress-overlays-managed-cert_test.go
Related to https://github.com/kubeflow/manifests/issues/593
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/597)
> fix basic-auth role binding ns

- gcp/basic-auth-ingress/base/cluster-role-binding.yaml
- gcp/basic-auth-ingress/base/params.yaml
- tests/basic-auth-ingress-base_test.go
- tests/basic-auth-ingress-overlays-application_test.go
- tests/basic-auth-ingress-overlays-certmanager_test.go
- tests/basic-auth-ingress-overlays-gcp-credentials_test.go
- tests/basic-auth-ingress-overlays-managed-cert_test.go
Cherry pick https://github.com/kubeflow/manifests/pull/597
Related to https://github.com/kubeflow/manifests/issues/593
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/601)
> fix basic-auth role binding ns (#597)

- kubebench/base/cluster-role-binding.yaml
- kubebench/base/cluster-role.yaml
- kubebench/base/config-map.yaml
- kubebench/base/crd.yaml
- kubebench/base/deployment.yaml
- kubebench/base/kustomization.yaml
- kubebench/base/service-account.yaml
- tests/kubebench-base_test.go
- tests/kubebench-overlays-application_test.go
- tests/kubebench-overlays-istio_test.go
- fix problems affecting installations
- update image versions
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/581)
> Cherry-pick #223 to v0.7-branch: Fix and update Kubebench manifests

- istio-1-3-1/OWNERS
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/603)
> Create OWNERS for Istio 1.3.1

- katib/katib-crds/overlays/application/application.yaml
- katib/katib-crds/overlays/application/kustomization.yaml
- tests/katib-controller-overlays-application_test.go
- tests/katib-crds-overlays-application_test.go
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/607)
> Katib v0.7.0 crd application resource

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_istio_dex.yaml
- kfdef/kfctl_k8s_istio.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/608)
> Add katib crd application to kfdef files

- metadata/base/metadata-deployment.yaml
- tests/metadata-base_test.go
- tests/metadata-overlays-application_test.go
- tests/metadata-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/611)
> Automated cherry pick of #610: Reduce metadata

- kfdef/kfctl_anthos.0.7.0.yaml
- kfdef/kfctl_aws.0.7.0.yaml
- kfdef/kfctl_aws_cognito.0.7.0.yaml
- kfdef/kfctl_existing_arrikto.0.7.0.yaml
- kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
- kfdef/kfctl_gcp_iap.0.7.0.yaml
- kfdef/kfctl_k8s_istio.0.7.0.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/609)
> Add katib application cr to kfdef (v0.7-branch)

- pipeline/pipelines-runner/base/cluster-role.yaml
- tests/pipelines-runner-base_test.go
- tests/pipelines-runner-overlays-application_test.go
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/623)
> kfserving inferenceservice CRD cannot work in pipeline

- kfdef/kfctl_anthos.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_gcp_basic_auth.yaml
- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_istio_dex.yaml
- kfdef/kfctl_k8s_istio.yaml
Add metadata application overlay to kfdef.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/621)
> Add metadata application overlay to kfdef

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/634)
> adding self to owner file

- .github/workflows/triage_issues.yaml
* Related to kubeflow/community#306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/630)
> Add a GitHub action to auto add/remove issues to Needs Triage Project

- kfdef/kfctl_istio_dex.yaml
Resolves kubeflow/kubeflow#4501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/620)
> Upgrades Istio in kfctl_istio_dex kfdef

- kfdef/kfctl_anthos.0.7.0.yaml
- kfdef/kfctl_aws.0.7.0.yaml
- kfdef/kfctl_aws_cognito.0.7.0.yaml
- kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
- kfdef/kfctl_gcp_iap.0.7.0.yaml
- kfdef/kfctl_k8s_istio.0.7.0.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/635)
> Update kfdef versions to v0.7.0

- istio/oidc-authservice/base/deployment.yaml
- istio/oidc-authservice/base/kustomization.yaml
- tests/basic-auth-ingress-base_test.go
- tests/basic-auth-ingress-overlays-application_test.go
- tests/basic-auth-ingress-overlays-certmanager_test.go
- tests/basic-auth-ingress-overlays-gcp-credentials_test.go
- tests/basic-auth-ingress-overlays-managed-cert_test.go
- tests/istio-crds-base_test.go
- tests/istio-install-base_test.go
- tests/metadata-base_test.go
- tests/metadata-overlays-application_test.go
- tests/metadata-overlays-ibm-storage-config_test.go
- tests/metadata-overlays-istio_test.go
- tests/oidc-authservice-base_test.go
- tests/oidc-authservice-overlays-application_test.go
- tests/oidc-authservice-overlays-ibm-storage-config_test.go
Resolves https://github.com/kubeflow/manifests/issues/632
Hopefully a fix for https://github.com/arrikto/oidc-authservice/issues/2
Adds a readiness check to the OIDC authservice and updates image to new version.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/633)
> istio: oidc-authservice: add readiness probe and update image

- profiles/base/kustomization.yaml
- tests/profiles-base_test.go
- tests/profiles-overlays-application_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/profiles-overlays-test_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/649)
> Automated cherry pick of #646: update profile image Cherry pick of #646 on v0.7-branch. #646: update profile image

- kfdef/kfctl_anthos.0.7.1.yaml
- kfdef/kfctl_aws.0.7.1.yaml
- kfdef/kfctl_aws_cognito.0.7.1.yaml
- kfdef/kfctl_existing_arrikto.0.7.1.yaml
- kfdef/kfctl_gcp_basic_auth.0.7.1.yaml
- kfdef/kfctl_gcp_iap.0.7.1.yaml
- kfdef/kfctl_k8s_istio.0.7.1.yaml
https://github.com/kubeflow/kfserving/issues/568
https://github.com/kubeflow/kfctl/issues/124
Add 0.7.1 kfdef files
```
$ diff kfctl_gcp_iap.0.7.0.yaml kfctl_gcp_iap.0.7.1.yaml
399c399
<     uri: https://github.com/kubeflow/manifests/archive/c0e81bedec9a4df8acf568cc5ccacc4bc05a3b38.tar.gz
---
>     uri: https://github.com/kubeflow/manifests/archive/v0.7-branch.tar.gz
402c402
<   version: v0.7.0
---
>   version: v0.7.1
```
/cc @jlewi @richardsliu 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/656)
> Kfdef 0.7.1

- kfdef/kfctl_upgrade_gcp_iap_0.7.1.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/658)
> Add upgrade spec for v0.7.0 to v0.7.1

- jupyter/OWNERS
Resolves #677
Add owners file for jupyter
/cc @jlewi @kimwnasptd 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/678)
> add owners file for jupyter

- kfdef/OWNERS
Resolves #679 
/cc @yanniszark 
@jlewi let me know if this is appropriate or if I should add anyone else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/681)
> Create OWNERS for kfdef folder

- jupyter/jupyter-web-app/base/cluster-role.yaml
- tests/jupyter-jupyter-web-app-base_test.go
- tests/jupyter-jupyter-web-app-overlays-application_test.go
- tests/jupyter-jupyter-web-app-overlays-istio_test.go
Resolves #654
**Checklist:**
3. `make test`
/cc @yanniszark
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/655)
> Add permissions to JWA for SubjectAccessReviews

- kfdef/kfctl_istio_dex.yaml
/assign @yanniszark 
I've tested spark operator and I think we could include it in this configuration now.
#661 
/cc @holdenk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/674)
> Update istio_dex config to support Spark operator

- kfdef/kfctl_istio_dex.yaml
Resolves kubeflow/kfctl#175
Resolves kubeflow/kfctl#175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/704)
> Update kfctl_istio_dex.yaml with missing name 'istio'

- profiles/overlays/application/application.yaml
- tests/profiles-overlays-application_test.go
Resolves https://github.com/kubeflow/manifests/issues/343
profile application update
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/738)
> profile application update

- jupyter/notebook-controller/base/crd.yaml
- jupyter/notebook-controller/base/kustomization.yaml
- jupyter/notebook-controller/overlays/application/application.yaml
- jupyter/notebook-controller/overlays/application/kustomization.yaml
- tests/jupyter-notebook-controller-base_test.go
- tests/jupyter-notebook-controller-overlays-application_test.go
- tests/jupyter-notebook-controller-overlays-istio_test.go
Fixes https://github.com/kubeflow/kubeflow/issues/4621
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/742)
> Cherry pick of #739 on v1.0-branch. #739: update notebook manifest

- jupyter/notebook-controller/base/crd.yaml
- jupyter/notebook-controller/base/kustomization.yaml
- jupyter/notebook-controller/overlays/application/application.yaml
- jupyter/notebook-controller/overlays/application/kustomization.yaml
- tests/jupyter-notebook-controller-base_test.go
- tests/jupyter-notebook-controller-overlays-application_test.go
- tests/jupyter-notebook-controller-overlays-istio_test.go
https://github.com/kubeflow/kubeflow/issues/4621
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/739)
> Update Notebook Controller to v1.0.0

- profiles/base/crd.yaml
- profiles/base/deployment.yaml
- profiles/base/kustomization.yaml
- profiles/overlays/application/application.yaml
- tests/profiles-base_test.go
- tests/profiles-overlays-application_test.go
- tests/profiles-overlays-debug_test.go
- tests/profiles-overlays-devices_test.go
- tests/profiles-overlays-istio_test.go
- tests/profiles-overlays-test_test.go
Resolves https://github.com/kubeflow/manifests/issues/773
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/775)
> Sync profile change to v1.0

- metadata/base/kustomization.yaml
- metadata/base/metadata-deployment.yaml
- tests/metadata-base_test.go
- tests/metadata-overlays-application_test.go
- tests/metadata-overlays-db_test.go
- tests/metadata-overlays-ibm-storage-config_test.go
- tests/metadata-overlays-istio_test.go
Change to update Metadata gRPC server to get latest updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/811)
> Metadata: Updating gRPC server version to v0.21.1

- pipeline/api-service/base/kustomization.yaml
- pipeline/api-service/base/role.yaml
- pipeline/persistent-agent/base/kustomization.yaml
- pipeline/pipeline-visualization-service/base/kustomization.yaml
- pipeline/pipelines-ui/base/kustomization.yaml
- pipeline/pipelines-viewer/base/kustomization.yaml
- pipeline/scheduledworkflow/base/kustomization.yaml
- tests/pipeline-api-service-base_test.go
- tests/pipeline-api-service-overlays-application_test.go
- tests/pipeline-persistent-agent-base_test.go
- tests/pipeline-persistent-agent-overlays-application_test.go
- tests/pipeline-pipeline-visualization-service-base_test.go
- tests/pipeline-pipeline-visualization-service-overlays-application_test.go
- tests/pipeline-pipelines-ui-base_test.go
- tests/pipeline-pipelines-ui-overlays-application_test.go
- tests/pipeline-pipelines-ui-overlays-gcp_test.go
- tests/pipeline-pipelines-ui-overlays-istio_test.go
- tests/pipeline-pipelines-viewer-base_test.go
- tests/pipeline-pipelines-viewer-overlays-application_test.go
- tests/pipeline-scheduledworkflow-base_test.go
- tests/pipeline-scheduledworkflow-overlays-application_test.go
related to kubeflow/manifests#796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/802)
> Update pipeline images to the 0.2.0 release.

- common/centraldashboard/base/deployment.yaml
- tests/common-centraldashboard-base_test.go
- tests/common-centraldashboard-overlays-application_test.go
- tests/common-centraldashboard-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/817)
> Automated cherry pick of #777: centraldashboard livenessProbe Cherry pick of #777 on v1.0-branch. #777: centraldashboard livenessProbe

- kfdef/kfctl_upgrade_gcp_iap_1.0.0.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/827)
> Add upgrade spec for v0.7.1 to v1.0

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-jupyter-web-app-base_test.go
- tests/jupyter-jupyter-web-app-overlays-application_test.go
- tests/jupyter-jupyter-web-app-overlays-istio_test.go
* Related to kubeflow/manifests#792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/829)
> Update the notebook images for 1.0

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-jupyter-web-app-base_test.go
- tests/jupyter-jupyter-web-app-overlays-application_test.go
- tests/jupyter-jupyter-web-app-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/835)
> Automated cherry pick of #829: Update the notebook images for 1.0 Cherry pick of #829 on v1.0-branch. #829: Update the notebook images for 1.0

- hack/build_kfdef_specs.py
- kfdef/kfctl_aws.v1.0.0.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.v1.0.0.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/kfctl_ibm.v1.0.0.yaml
- kfdef/kfctl_ibm.yaml
- kfdef/kfctl_istio_dex.v1.0.0.yaml
- kfdef/kfctl_istio_dex.yaml
- kfdef/kfctl_k8s_istio.v1.0.0.yaml
- kfdef/kfctl_k8s_istio.yaml
- kfdef/source/master/kfctl_aws.yaml
- kfdef/source/master/kfctl_aws_cognito.yaml
- kfdef/source/master/kfctl_gcp_basic_auth.yaml
- kfdef/source/master/kfctl_gcp_iap.yaml
- kfdef/source/master/kfctl_ibm.yaml
- kfdef/source/master/kfctl_istio_dex.yaml
- kfdef/source/master/kfctl_k8s_istio.yaml
- kfdef/source/master/kustomization.yaml
- kfdef/source/v1.0.0/kfctl_aws.yaml
- kfdef/source/v1.0.0/kfctl_aws_cognito.yaml
- kfdef/source/v1.0.0/kfctl_gcp_basic_auth.yaml
- kfdef/source/v1.0.0/kfctl_gcp_iap.yaml
- kfdef/source/v1.0.0/kfctl_ibm.yaml
- kfdef/source/v1.0.0/kfctl_istio_dex.yaml
- kfdef/source/v1.0.0/kfctl_k8s_istio.yaml
- kfdef/source/v1.0.0/kustomization.yaml
* add v1.0.0 kfdef for all platforms with new kusotmize tool
* add kfctl-istio-dex
* keep _ in file name
* regenerate
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/836)
> cherry pick: add v1.0.0 kfdef for all platforms with new kusotmize tool (#826)

- jupyter/notebook-controller/base/deployment.yaml
- tests/jupyter-notebook-controller-base_test.go
- tests/jupyter-notebook-controller-overlays-application_test.go
- tests/jupyter-notebook-controller-overlays-istio_test.go
Resolves #https://github.com/kubeflow/kubeflow/issues/4060
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/845)
> cherry pick: livenessProbe for notebook-controller (#837)

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-jupyter-web-app-base_test.go
- tests/jupyter-jupyter-web-app-overlays-application_test.go
- tests/jupyter-jupyter-web-app-overlays-istio_test.go
copy of https://github.com/kubeflow/manifests/pull/798
plus test update
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/865)
> copy pr 798: Update JWAs config-map for GPU support

- jupyter/jupyter-web-app/base/config-map.yaml
- tests/jupyter-jupyter-web-app-base_test.go
- tests/jupyter-jupyter-web-app-overlays-application_test.go
- tests/jupyter-jupyter-web-app-overlays-istio_test.go
* Update JWAs config-map for GPU support
* Update notebook images
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/871)
> cherry pick #865: Update JWAs config-map for GPU support

- katib/katib-controller/base/katib-configmap.yaml
- katib/katib-controller/base/kustomization.yaml
- tests/katib-katib-controller-base_test.go
- tests/katib-katib-controller-overlays-application_test.go
- tests/katib-katib-controller-overlays-ibm-storage-config_test.go
- tests/katib-katib-controller-overlays-istio_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/881)
> Automated cherry pick of #877: Update Katib image tags Cherry pick of #877 on v1.0-branch. #877: Update Katib image tags

- metadata/OWNERS
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/888)
> Remove riley from owners

- gcp/deployment_manager_configs/cluster-kubeflow.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/912)
> Automated cherry pick of #882: unpin gke version Cherry pick of #882 on v1.0-branch. #882: unpin gke version

- experimental/mirror-images/mirror_task.yaml
update task name
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/914)
> udpate task name

- kfdef/kfctl_aws.v1.0.0.yaml
- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.v1.0.0.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/source/master/kfctl_aws.yaml
- kfdef/source/master/kfctl_aws_cognito.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/916)
> Automated cherry pick of #909: Add EnvoyFilter to add anonymous to all gateway requests

- metadata/base/kustomization.yaml
- metadata/base/metadata-deployment.yaml
- tests/metadata-base_test.go
- tests/metadata-overlays-application_test.go
- tests/metadata-overlays-db_test.go
- tests/metadata-overlays-ibm-storage-config_test.go
- tests/metadata-overlays-istio_test.go
Fixes https://github.com/kubeflow/metadata/issues/198 for v1.0
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/937)
> Automated cherry pick of #811: Metadata: Updating gRPC server version to v0.21.1

- aws/aws-istio-authz-adaptor/base/instance.yaml
- aws/aws-istio-authz-adaptor/base/kustomization.yaml
- aws/aws-istio-authz-adaptor/base/rule.yaml
- kfdef/kfctl_aws_cognito.v1.0.0.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/source/master/kfctl_aws_cognito.yaml
- tests/aws-aws-istio-authz-adaptor-base_test.go
- tests/aws-aws-istio-authz-adaptor-overlays-application_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/956)
> Automated cherry pick of #944: Remove envoyfilter in identity aware manifest and fix bugs

- aws/istio-ingress/overlays/oidc/ingress.yaml
- tests/aws-istio-ingress-overlays-oidc_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/985)
> Automated cherry pick of #982: Fix OIDC settings Cherry pick of #982 on v1.0-branch. #982: Fix OIDC settings

- kfdef/kfctl_anthos.v1.0.1.yaml
- kfdef/kfctl_aws.v1.0.1.yaml
- kfdef/kfctl_aws_cognito.v1.0.1.yaml
- kfdef/kfctl_gcp_basic_auth.v1.0.1.yaml
- kfdef/kfctl_gcp_iap.v1.0.1.yaml
- kfdef/kfctl_ibm.v1.0.1.yaml
- kfdef/kfctl_istio_dex.v1.0.1.yaml
- kfdef/kfctl_k8s_istio.v1.0.1.yaml
- kfdef/source/v1.0.1/kfctl_anthos.yaml
- kfdef/source/v1.0.1/kfctl_aws.yaml
- kfdef/source/v1.0.1/kfctl_aws_cognito.yaml
- kfdef/source/v1.0.1/kfctl_gcp_basic_auth.yaml
- kfdef/source/v1.0.1/kfctl_gcp_iap.yaml
- kfdef/source/v1.0.1/kfctl_ibm.yaml
- kfdef/source/v1.0.1/kfctl_istio_dex.yaml
- kfdef/source/v1.0.1/kfctl_k8s_istio.yaml
- kfdef/source/v1.0.1/kustomization.yaml
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/994)
> v1.0.1 patch manifests

- kfdef/kfctl_anthos.v1.0.1.yaml
- kfdef/kfctl_aws.v1.0.1.yaml
- kfdef/kfctl_aws_cognito.v1.0.1.yaml
- kfdef/kfctl_gcp_basic_auth.v1.0.1.yaml
- kfdef/kfctl_gcp_iap.v1.0.1.yaml
- kfdef/kfctl_ibm.v1.0.1.yaml
- kfdef/kfctl_istio_dex.v1.0.1.yaml
- kfdef/kfctl_k8s_istio.v1.0.1.yaml
- kfdef/source/v1.0.1/kfctl_anthos.yaml
- kfdef/source/v1.0.1/kfctl_aws.yaml
- kfdef/source/v1.0.1/kfctl_aws_cognito.yaml
- kfdef/source/v1.0.1/kfctl_gcp_basic_auth.yaml
- kfdef/source/v1.0.1/kfctl_gcp_iap.yaml
- kfdef/source/v1.0.1/kfctl_ibm.yaml
- kfdef/source/v1.0.1/kfctl_istio_dex.yaml
- kfdef/source/v1.0.1/kfctl_k8s_istio.yaml
- kfdef/source/v1.0.1/kustomization.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/995)
> Automated cherry pick of #994: v1.0.1 patch manifests Cherry pick of #994 on v1.0-branch. #994: v1.0.1 patch manifests

- pipeline/OWNERS
/assign @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/967)
> OWNERS for pipeline folder

- kfdef/kfctl_anthos.v1.0.0.yaml
- kfdef/kfctl_anthos.v1.0.1.yaml
- kfdef/kfctl_anthos.yaml
- kfdef/source/master/kfctl_anthos.yaml
Resolves #
**Checklist:**
3. `make test`
> Update anthos kfdef manifests

- gcp/v2/README.md
Add instructions for kubeflow setup on top of KCC & ASM
**Checklist:**
3. `make test`
> add instruction for kubeflow on KCC

- kfdef/kfctl_gcp_iap.yaml
- kfdef/kfctl_ibm.yaml
Part of https://github.com/kubeflow/kubeflow/issues/4803
Update generated kfdefs from kfdef source
**Checklist:**
3. `make test`
/assign @richardsliu @jlewi
> Update generated kfdefs

- kfdef/kfctl_upgrade_gcp_iap_1.0.2.yaml
Resolves #
**Checklist:**
3. `make test`
> Add upgrade spec for v1.0.0 to v1.0.2

- metadata/base/kustomization.yaml
- metadata/overlays/istio/virtual-service.yaml
- metadata/v3/kustomization.yaml
- metadata/v3/params.yaml
* v3 version combines the various overlays that  we need.
* The var names need to be unique enough not to conflict.
> Create a v3 version of the metadata package 

- OWNERS
- mpi-job/mpi-operator/overlays/application/application.yaml
- mxnet-job/mxnet-operator/overlays/application/application.yaml
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
Resolves #
/cc @richardsliu 
**Checklist:**
3. `make test`
> Update maintainers info for MPIJob and MXJob manifests

- mpi-job/mpi-operator/overlays/application/application.yaml
Resolves #
/cc @stpabhi @swiftdiaries 
**Checklist:**
3. `make test`
> Add Abhilash to MPIJob manifests maintainers

- gcp/v2/privateGKE/compute-network.yaml
- gcp/v2/privateGKE/dns-gcr.yaml
- gcp/v2/privateGKE/dns-google-apis.yaml
- gcp/v2/privateGKE/firewall.yaml
- gcp/v2/privateGKE/kustomization.yaml
Publish templates for creating private kubeflow cluster 
**Checklist:**
3. `make test`
> private GKE templates

- katib/OWNERS
- katib/katib-controller/overlays/application/application.yaml
- katib/katib-crds/overlays/application/application.yaml
- tests/tests/legacy_kustomizations/katib-controller/test_data/expected/app.k8s.io_v1beta1_application_katib-controller.yaml
- tests/tests/legacy_kustomizations/katib-crds/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
I added OWNERS file to Katib manifest folder.
Also, I added myself to Katib applications maintainers.
/assign @jlewi @gaocegege @johnugeorge 
**Checklist:**
3. `make test`
> Add OWNERS file to Katib manifests

- kubeflow-roles/README.md
Resolves #
Update path to example istio clusterRole. 
**Checklist:**
3. `make test`
> Update README.md with broken link.

- tests/OWNERS
Resolves https://github.com/kubeflow/manifests/pull/1210#issuecomment-637235442
Add me to test snapshot OWNERES, so I can approve pipeline related changes by myself.
**Checklist:**
3. `make test`
> Add Bobgy to tests/OWNERS

- kfserving/kfserving-install/base/config-map.yaml
- tests/tests/legacy_kustomizations/kfserving-install/test_data/expected/~g_v1_configmap_inferenceservice-config.yaml
Resolves #
https://github.com/kubeflow/kfserving/issues/859
Updates Alibi image for KFServing 0.3.0
**Checklist:**
- [ *] Unit tests have been rebuilt: 
3. `make test`
> Update Alibi image for kfserving 0.3.0

- README.md
Resolves https://github.com/kubeflow/manifests/issues/1217
Add kustomize version recommendation in README
**Checklist:**
3. `make test`
> Document recommendation of kustomize version

- tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-controller.yaml
- tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
- tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-ui.yaml
- tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
- tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_katib-config.yaml
- tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
- tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-controller.yaml
- tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
- tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-ui.yaml
- tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
- tests/stacks/generic/test_data/expected/~g_v1_configmap_katib-config.yaml
- tests/stacks/generic/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
Resolves #1254 
This is to address https://github.com/kubeflow/manifests/pull/1239#issuecomment-644477203
**Checklist:**
3. `make test`
> Fixes local tests

- pipeline/mysql/installs/gcp-pd/kustomization.yaml
- stacks/gcp/OWNERS
- tests/stacks/gcp/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
* Remove commented out code which turns out not to be needed
* Fix OWNERs file
> Follow up to #1288

- pipeline/installs/generic/kustomization.yaml
- tests/stacks/gcp/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
Resolves #
**Checklist:**
3. `make test`
> Generates and fixes unit-tests

- tests/go.mod
- tests/stacks/ibm/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
- tests/stacks/ibm/test_data/expected/apps_v1_deployment_pytorch-operator.yaml
- tests/stacks/ibm/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
- tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
- tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
- tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
- tests/stacks/ibm/test_data/expected/~g_v1_service_minio-service.yaml
- tests/stacks/ibm/test_data/expected/~g_v1_service_mysql.yaml
> Synchronize the tests

- gcp/v2/cnrm/iam/kf-admin-policy.yaml
- gcp/v2/cnrm/iam/kf-user-policy.yaml
- stacks/gcp/kustomization.yaml
- stacks/gcp/workload-identity-bindings-patch.yaml
- tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
- tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
- tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
- tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
- tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
- tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
- tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
- tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
Part of https://github.com/kubeflow/gcp-blueprints/issues/61
> Cherrypick "fix(gcp): default workload identity bindings (#1317)"

- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/source/master/kfctl_aws.yaml
- kfdef/source/master/kfctl_aws_cognito.yaml
Resolves #
Remove aws overlay for jupyter web app. kfctl seems have an issue and can not parse this correctly. We will fix issue and add it back in next release.
**Checklist:**
3. `make test`
> Remove aws overlay for jupyter web app

- kfdef/kfctl_aws.yaml
- kfdef/kfctl_aws_cognito.yaml
- kfdef/source/master/kfctl_aws.yaml
- kfdef/source/master/kfctl_aws_cognito.yaml
Resolves #
**Checklist:**
3. `make test`
> Remove aws overlay for jupyter web app (#1337)

- gcp/v2/cnrm/iam/admin-manages-user-policy.yaml
- gcp/v2/cnrm/iam/kf-admin-policy.yaml
- gcp/v2/cnrm/iam/kf-admin-workload-identity-bindings.yaml
- gcp/v2/cnrm/iam/kf-user-policy.yaml
- gcp/v2/cnrm/iam/kf-user-workload-identity-bindings.yaml
- gcp/v2/cnrm/iam/kustomization.yaml
Cherry picks #1347 
Related to https://github.com/kubeflow/gcp-blueprints/issues/61#issuecomment-654075129
> Cherry pick "fix(gcp): Use IAMPolicyMember for workload identity bindings #1347"

- aws/aws-istio-authz-adaptor/base/kustomization.yaml
Upgrade istio auth adapter version. 
Upgrade istio auth adapter version. 
**Checklist:**
3. `make test`
> [AWS] Upgrade istio auth adapter version

- kfdef/OWNERS
Add myself `adrian555` to the kfdef/OWNERS for approving IBM Cloud platform specific kfdef changes.
**Checklist:**
- [ x ] Unit tests have been rebuilt: 
3. `make test`
> add myself to kfdef/OWNERS

- knative/knative-serving-install/base/deployment.yaml
- tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_activator.yaml
- tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_autoscaler.yaml
Resolves #
**Checklist:**
3. `make test`
> Automated cherry pick of #1340 upstream v1.1 branch

- gcp/v2/management/cnrm-install/services/enable-services.yaml
Related to: kubeflow/gcp-blueprints#102
> Fix cloudresourcemanager service; missing ApiVersion.

- stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
- tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
Resolves #
Upgrade AWS jupyter images to 1.1.0
**Checklist:**
3. `make test`
> Upgrade AWS jupyter images to 1.1.0

- OWNERS
As discussed, to facilitate future management, it'll be better also adding me in root OWNERS.
> Add Bobgy to OWNERS

- admission-webhook/OWNERS
- jupyter/OWNERS
- mpi-job/OWNERS
- mxnet-job/OWNERS
- profiles/OWNERS
- pytorch-job/OWNERS
- spark/OWNERS
- tensorboard/OWNERS
- tf-training/OWNERS
- xgboost-job/OWNERS
Here's the contributions I made. https://github.com/kubeflow/manifests/pulls?page=2&q=is%3Apr+author%3AJeffwan+is%3Aclosed  Besides AWS changes, I make lots of contributions on common components like training operators, etc. I would like to become an approver to better help community members.
**Checklist:**
3. `make test`
> Add Jeffwan to OWNERS files

- admission-webhook/OWNERS
- jupyter/OWNERS
- mpi-job/OWNERS
- mxnet-job/OWNERS
- profiles/OWNERS
- pytorch-job/OWNERS
- spark/OWNERS
- tensorboard/OWNERS
- tf-training/OWNERS
- xgboost-job/OWNERS
Cherry pick of #1443 on v1.1-branch.
#1443: Add Jeffwan to OWNERS files
> Automated cherry pick of #1443: Add Jeffwan to OWNERS files

- gcp/v2/asm/istio-operator.yaml
> Cherry pick of "chore: upgrade istio to 1.4.10-asm.15 #1412"

- kfdef/OWNERS
- stacks/azure/OWNERS
Added the people responsible for manifests on Azure's side
> Add Azure owners

- cert-manager/cert-manager/overlays/application/application.yaml
- kfserving/kfserving-install/overlays/application/application.yaml
- mpi-job/mpi-operator/overlays/application/application.yaml
- seldon/seldon-core-operator/overlays/application/application.yaml
- tests/stacks/aws/application/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
- tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_mpi-operator.yaml
- tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
- tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
- tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
- tests/stacks/ibm/application/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
- tests/stacks/ibm/multi-user/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
- tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
- tests/stacks/kubernetes/application/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
- tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_mpi-operator.yaml
- tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
- tests/tests/legacy_kustomizations/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml
- tests/tests/legacy_kustomizations/kfserving-install/test_data/expected/app.k8s.io_v1beta1_application_kfserving.yaml
- tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/app.k8s.io_v1beta1_application_seldon-core-operator.yaml
* ensure descriptor field is correctly set
* ensure addOwnerRef=true
> fix application specs

- aws/OWNERS
Resolves #
To further maintain AWS resources, add PatrickXYS into AWS folders OWNERS
**Checklist:**
3. `make test`
> Add Myself into AWS OWNERS

- gcp/Kptfile
- gcp/v2/asm/istio-operator.yaml
- gcp/v2/cnrm/cluster/cluster.yaml
- gcp/v2/cnrm/cluster/nodepool.yaml
- gcp/v2/cnrm/pipelines/disk.yaml
- gcp/v2/management/cluster/cluster.yaml
- gcp/v2/management/cluster/nodepool.yaml
- gcp/v2/privateGKE/cluster-private-patch.yaml
- gcp/v2/privateGKE/compute-network.yaml
- gcp/v2/privateGKE/nat.yaml
- tests/Makefile
* Fix kubeflow/gcp-blueprints#117
* The pattern for the mesh id needs to be proj-${PROJECTNUMBER}
* Dedube the mesh substitutions; there were two different substitutions "mesh-id" and "asm-mesh-id" for the mesh id.
> ASM Mesh id should be proj-${PROJECTNUBMER}

- gcp/v2/management/cnrm-install/README.md
- gcp/v2/management/cnrm-install/install-system/0-cnrm-system.yaml
- gcp/v2/management/cnrm-install/install-system/crds.yaml
Related to kubeflow/gcp-blueprints#143
/assign @subodh101 
/assign @Bobgy
> Upgrade CNRM from 1.15 to 1.27.2

- jupyter/OWNERS
- tests/OWNERS
I need to be an approver so that I can resolve issues with @kimwnasptd (we are both leads of the Notebook WG)
> Update Notebook OWNERS

- kfdef/kfctl_aws.v1.2.0.yaml
- kfdef/kfctl_aws_cognito.v1.2.0.yaml
- kfdef/kfctl_ibm.v1.2.0.yaml
- kfdef/kfctl_ibm_dex_multi_user.v1.2.0.yaml
- kfdef/kfctl_istio_dex.v1.2.0.yaml
- kfdef/kfctl_k8s_istio.v1.2.0.yaml
- kfdef/kfctl_openshift.v1.2.0.yaml
> Automated cherry pick of #1620: Add kfdef 1.2 manifests

- OWNERS
Adding @pvaneck as a reviewer. Will be responsible for maintaining manifests for KFServing, OpenShift, IKS etc.
PRs merged: 
https://github.com/kubeflow/manifests/pull/1515
https://github.com/kubeflow/manifests/pull/1575
https://github.com/kubeflow/manifests/pull/1580
https://github.com/kubeflow/manifests/pull/1617
https://github.com/kubeflow/kfctl/pull/439
Reviews:
https://github.com/kubeflow/manifests/pull/1582
https://github.com/kubeflow/manifests/pull/1621
https://github.com/kubeflow/manifests/pull/1625
https://github.com/kubeflow/manifests/pull/1627
https://github.com/kubeflow/manifests/pull/1628
https://github.com/kubeflow/kfctl/pull/419
> Add Paul as a reviewer

- stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
- tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
Resolves #
Cherry-Pick #1637 PR into v1.2-branch
**Checklist:**
3. `make test`
> Cherry-Pick #1637 PR into v1.2-branch

- stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-24bth2gbkc.yaml
- tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-24bth2gbkc.yaml
Sync #1644
**Checklist:**
3. `make test`
> Update jupyter config with tolerations/selectors for aws

- pipeline/installs/generic/application.yaml
- tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/azure/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/generic/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-argo-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-argo/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-tekton/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/openshift/application/pipeline/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
Part of #1573
**Checklist:**
3. `make test`
> fix(kfp): fix application label selector. Part of #1573

- pipeline/installs/generic/application.yaml
- tests/stacks/aws/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/azure/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/examples/alice/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/gcp/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/generic/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-argo-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-argo/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/application/kfp-tekton/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/multi-user/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/ibm/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/kubernetes/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
- tests/stacks/openshift/application/pipeline/test_data/expected/app.k8s.io_v1beta1_application_kubeflow-pipelines.yaml
/assign @Jeffwan 
**Checklist:**
3. `make test`
> Cherry picks "fix(kfp): fix application label selector. Part of #1573"

- jupyter/jupyter-web-app/base/kustomization.yaml
- jupyter/jupyter-web-app/base_v3/kustomization.yaml
- stacks/azure/application/jupyter-web-app/base/kustomization.yaml
- stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
- tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
- tests/tests/legacy_kustomizations/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
(cherry picked from commit 9f52c781a95adf08c55377689642921da67fc94f)
> fix jupyter-web-app image tag (#1686)

- .github/pull_request_template.md
Resolves #
Add one comment to guide developers running generate test cases locally first.
**Checklist:**
3. `make test`
> Add comment for PR template

- contrib/seldon/Makefile
- contrib/seldon/seldon-core-operator/base/resources.yaml
- contrib/seldon/values.yaml
Resolves #
**Checklist:**
**Please make sure you have installed kustomize <= 3.2.1**
3. `make test`
> Update Seldon to 1.6.0

- .github/pull_request_template.md
- jupyter/OWNERS
Related to https://github.com/kubeflow/manifests/issues/1738
This PR makes some small changes, pertaining to issue https://github.com/kubeflow/manifests/issues/1738.
These are nitpicks that were forgotten in the original PR.
> Delete leftover jupyter folder and amend pr template

- apps/pipeline/upstream/installs/multi-user/pipelines-profile-controller/sync.py
- apps/pipeline/upstream/installs/tekton-multi-user/sync.py
Resolves #4530 in kubeflow/pipelines see: https://github.com/kubeflow/pipelines/issues/4530
**Checklist:**
2. `make test`
> feat(backend): Updated to make possible to evict pods even with empty dir. Fixes #4530 kubeflow/pipelines 

- contrib/feast/Makefile
- contrib/feast/OWNERS
- contrib/feast/README.md
- contrib/feast/feast/base/kustomization.yaml
- contrib/feast/feast/base/resources.yaml
- contrib/feast/feast/base/static.yaml
- contrib/feast/feast/overlays/application/application.yaml
- contrib/feast/feast/overlays/application/kustomization.yaml
- contrib/feast/values.yaml
For some reason #1733 was closed after I rebased. I'm reopening the same PR.
> Add Feast to Kubeflow Contrib

- contrib/feast/Makefile
- contrib/feast/feast/base/resources.yaml
Signed-off-by: ted chang <htchang@us.ibm.com>
Updated the helm repo url
/cc @woop
> Updated the feast helm repo url

- README.md
cc @kubeflow/wg-manifests-leads
> README: Small fixes

- README.md
Add a matrix with each component and the included manifests version.
Refs: https://github.com/kubeflow/manifests/issues/1775
> README: Add component version matrix

- README.md
cc @kubeflow/wg-manifests-leads
> README: Add FAQ, elaborate kustomize version, update version matrix

- README.md
- apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
- apps/pipeline/upstream/base/cache/kustomization.yaml
- apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/pipeline/upstream/base/installs/multi-user/istio-authorization-config.yaml
- apps/pipeline/upstream/base/metadata/base/kustomization.yaml
- apps/pipeline/upstream/base/metadata/options/istio/destination-rule.yaml
- apps/pipeline/upstream/base/metadata/options/istio/istio-authorization-policy.yaml
- apps/pipeline/upstream/base/metadata/options/istio/kustomization.yaml
- apps/pipeline/upstream/base/metadata/options/istio/virtual-service.yaml
- apps/pipeline/upstream/base/pipeline/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
- apps/pipeline/upstream/env/platform-agnostic-multi-user-legacy/kustomization.yaml
- apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml
- apps/pipeline/upstream/third-party/minio/options/istio/istio-authorization-policy.yaml
Sync manifests for application "Kubeflow Pipelines".
Upstream manifests are copied from:
- Repo: https://github.com/kubeflow/pipelines
- Path: manifests/kustomize
- Revision: 1.5.0
/assign @Bobgy
> Kubeflow Pipelines: Sync manifests

- README.md
> Cherry pick #1851: docs(kfp): introduce multi-user KFP dependencies and KFP standalone as alternative

- contrib/feast/OWNERS
@tedhtchang, adding you to the OWNERS file so that we can move a bit faster.
**Checklist:**
2. `make test`
> Add tedhtchang to Feast OWNERS

- README.md
To continue this PR: https://github.com/kubeflow/manifests/pull/1857 we should also update few user names in the README.
/cc @DavidSpek @yanniszark @pvaneck 
**Checklist:**
2. `make test`
> Change user name to user@example.com in README

- common/istio-1-9/cluster-local-gateway/base/cluster-local-gateway.yaml
- common/istio-1-9/istio-install/base/install.yaml
- common/istio-1-9/profile.yaml
Resolves #1924
Run the Istio guide to upgrade Istio to 1.9.6.
> common: Upgrade Istio to 1.9.6

- contrib/seldon/OWNERS
> Update Seldon OWNERS file

- common/knative/knative-eventing/base/kustomization.yaml
- common/knative/knative-eventing/base/patches/clusterrole-patch.yaml
- common/knative/knative-serving/base/kustomization.yaml
- common/knative/knative-serving/base/patches/clusterrole-patch.yaml
Resolves #1876
This PR aggregates knative namespaced roles to kubeflow roles.
**Checklist:**
2. `make test`
> fix(knative): aggregate knative namespaced roles to kubeflow roles

- common/knative/knative-eventing/base/kustomization.yaml
- common/knative/knative-eventing/base/patches/clusterrole-patch.yaml
- common/knative/knative-serving/base/kustomization.yaml
- common/knative/knative-serving/base/patches/clusterrole-patch.yaml
Cherry-pick https://github.com/kubeflow/manifests/pull/1877
cc @henrysecond1 @pvaneck 
/cc @elikatsis 
/assign @kimwnasptd
> cherry-pick: Permissions for Knative objects

- apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
- apps/pipeline/upstream/base/cache/kustomization.yaml
- apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/pipeline/upstream/base/metadata/base/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
- apps/pipeline/upstream/env/platform-agnostic-multi-user-emissary/workflow-controller-configmap-patch.yaml
- apps/pipeline/upstream/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
- apps/pipeline/upstream/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml
- apps/pipeline/upstream/third-party/argo/base/workflow-controller-configmap-patch.yaml
- apps/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
- apps/pipeline/upstream/third-party/argo/installs/cluster/kustomization.yaml
- apps/pipeline/upstream/third-party/argo/installs/cluster/workflow-controller-clusterrolebinding-patch.json
In response to https://github.com/kubeflow/manifests/issues/1959#issuecomment-905517223
/cc @Bobgy @zijianjoy
> Update pipelines to 1.7.0

- README.md
Follow up of #1997 
/cc @elikatsis
> Update README for pipelines 1.7.0

- distributions/stacks/openshift/application/pipeline-agnostic/kustomization.yaml
- distributions/stacks/openshift/application/pipeline-agnostic/metadata-gprc.yaml
- distributions/stacks/openshift/kustomization.yaml
Resolves #https://issues.redhat.com/browse/ODH-475
**Checklist:**
2. `make test`
> Adding Virtual Service to enable metadata

- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Use the images from our latest tag https://github.com/kubeflow/kubeflow/tree/v1.4-rc.1
/cc @elikatsis 
/assign @kimwnasptd
> Update Notebooks WG manifests from RC1

- .gitignore
I used the file from https://github.com/github/gitignore/blob/master/Global/Vim.gitignore
This should help to keep the repo clean from vim's swap files
/cc @elikatsis
> git: Ignore Vim files

- example/kustomization.yaml
No issue was created for this I believe, just noticed the "typo" when I was adjusting my kustomization.yaml.
Comments above Tensorboard Controller and Web App were swapped, so I just fixed that.
**Checklist:**
2. `make test`
> Fix apps description in example/kustomization.yaml

- README.md
- apps/training-operator/upstream/base/deployment.yaml
- apps/training-operator/upstream/base/service.yaml
- apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
- apps/training-operator/upstream/overlays/standalone/kustomization.yaml
cherry-pick #2024 to release branch
> Cherry pick of #2024: Update training operator to v1.3.0-rc.1

- README.md
- apps/kfserving/upstream/configmap/inferenceservice.yaml
- apps/kfserving/upstream/default/manager_image_patch.yaml
- apps/kfserving/upstream/web-app/deployment.yaml
I realized that KFServing was still in 0.6 and not 0.6.1
/cc @elikatsis
> Update KFServing to 0.6.1

- proposals/README.md
Moving forward we should have a slightly more formal process for evaluating more advanced features and requests. This was triggered by the tests discussion, where we will need to evaluate a lot of details https://github.com/kubeflow/manifests/issues/2099 for an engineering effort.
It will be more efficient for reviewing to have information in a more structured way, when evaluating bigger efforts.
I really liked the approach of [VMWare's Octant](https://github.com/vmware-tanzu/octant/blob/master/CONTRIBUTING.md#proposals) repo, and that's why the initial iteration is identical. It establishes a slightly more formal process, while still giving a lot of room on the structure. I think it's a good first step and we can further improve as we follow this more.
/cc @elikatsis @StefanoFioravanzo …
> Introduce a basic proposals flow for more advanced features

- tests/OWNERS
https://github.com/kubeflow/internal-acls/pull/524
> chore: remove Bobgy from OWNERS

- apps/katib/upstream/components/cert-generator/cert-generator.yaml
- apps/katib/upstream/components/cert-generator/rbac.yaml
- apps/katib/upstream/components/controller/controller.yaml
- apps/katib/upstream/components/controller/katib-config.yaml
- apps/katib/upstream/components/controller/rbac.yaml
- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/components/namespace/namespace.yaml
- apps/katib/upstream/components/webhook/webhooks.yaml
- apps/katib/upstream/installs/katib-cert-manager/certificate.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/leader-election-rbac.yaml
- apps/katib/upstream/installs/katib-leader-election/patches/controller.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
cc @kubeflow/wg-automl-leads 
/cc @StefanoFioravanzo @elikatsis
> Update kubeflow/katib manifests from v0.13.0-rc.0

- README.md
- contrib/kserve/OWNERS
- contrib/kserve/upstream/kserve.yaml
- contrib/kserve/upstream/kserve_kubeflow.yaml
- example/kustomization.yaml
Refs https://github.com/kubeflow/manifests/issues/2110
cc @yuzisun @pvaneck 
/cc @StefanoFioravanzo @elikatsis
> Update the KServe manifests

- README.md
Last item for cutting RC 0
/cc @StefanoFioravanzo @elikatsis 
> Update README for v1.5.0-rc.0

- README.md
- apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
- apps/kfp-tekton/upstream/base/cache/kustomization.yaml
- apps/kfp-tekton/upstream/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
- apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml
- apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
- apps/kfp-tekton/upstream/third-party/application/cluster-scoped/application-crd.yaml
- apps/kfp-tekton/upstream/third-party/metacontroller/base/crd.yaml
- apps/kfp-tekton/upstream/third-party/tekton-custom-task/kustomization.yaml
- hack/sync-kfp-tekton-manifests.sh
Refs https://github.com/kubeflow/manifests/issues/2112#issuecomment-1040564373
Updates the KFP Tekton component to `v1.1.1`. I'll also cherry-pick this into https://github.com/kubeflow/manifests/pull/2138
/cc @Tomcli @elikatsis @StefanoFioravanzo
> Update kubeflow/kfp-tekton manifests from v1.1.1

- README.md
- apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
- apps/pipeline/upstream/base/cache/kustomization.yaml
- apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/pipeline/upstream/base/metadata/base/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
Refs https://github.com/kubeflow/manifests/issues/2111#issuecomment-1055100631
Updates KFP to 1.8.1
/cc @elikatsis @StefanoFioravanzo 
cc @zijianjoy @chensun @kubeflow/release-team
> Update kubeflow/pipelines manifests from 1.8.1

- README.md
- apps/katib/upstream/components/controller/katib-config.yaml
- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
- hack/sync-katib-manifests.sh
Refs https://github.com/kubeflow/manifests/issues/2106
I also updated the hack script, so that it automatically updates the README as sell
cc @kubeflow/wg-automl-leads
> Sync kubeflow katib manifests v0.13.0

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/overlays/kserve/kustomization.yaml
- apps/centraldashboard/upstream/overlays/kserve/patches/configmap.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Refs: #2109 
cc @kubeflow/wg-notebooks-leads @kubeflow/release-team
> Update kubeflow/kubeflow manifests from v1.5.0-rc.2

- README.md
Added some info to the individual component section about KServe/KFServing.
> docs: Update KServe/KFServing section in README

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Refs #2109 
Use the final 1.5.0 tag for the Notebooks components
> Update kubeflow/kubeflow manifests from v1.5.0

- README.md
fix dex configmap path in documentation
> fix dex configmap path

- README.md
Resolves #
Update the istio version in the README to 1.14.1 (ref https://github.com/kubeflow/manifests/pull/2233)
**Checklist:**
2. `make test`
> Update README with Istio 1.4.1

- README.md
Make sure the README is up to date for the first RC
/cc @annajung
> readme: Update component versions

- contrib/networkpolicies/kustomization.yaml
@kimwnasptd please also cherry pick to 1.6
**Checklist:**
2. `make test`
> Fix typo in the networkpolicies

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/crd/bases/kubeflow.org_notebooks.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/profiles/upstream/samples/_v1_profile.yaml
- apps/profiles/upstream/samples/_v1_profile_aws_iam.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
> Update kubeflow/kubeflow manifests from v1.6.0-rc.2

- README.md
- apps/profiles/upstream/manager/manager.yaml
- Sync Notebook v1.6.0-rc.3
cc @kubeflow/release-team @gkcalat @kimwnasptd
> Update kubeflow/kubeflow manifests from v1.6.0-rc.3

- .github/workflows/train_operator_kind_test.yaml
- tests/gh-actions/kf-objects/tfjob.yaml
Refs https://github.com/kubeflow/manifests/issues/2248
> Extend Training Operator GH action to also apply a TFJob and assert it runs

- .github/workflows/centraldb_kind_test.yaml
- .github/workflows/dex_kind_test.yaml
- .github/workflows/jwa_kind_test.yaml
- .github/workflows/katib_kind_test.yaml
- .github/workflows/kserve_kind_test.yaml
- .github/workflows/nb_controller_kind_test.yaml
- .github/workflows/pipeline_kind_test.yaml
- .github/workflows/poddefaults_kind_test.yaml
- .github/workflows/profiles_kind_test.yaml
- .github/workflows/tb_controller_kind_test.yaml
- .github/workflows/train_operator_kind_test.yaml
- .github/workflows/twa_kind_test.yaml
- .github/workflows/vwa_kind_test.yaml
- tests/gh-actions/install_kind.sh
- tests/gh-actions/kind-cluster-1.25.yaml
Updating the KinD cluster version to K8s 1.25
Refs: https://github.com/kubeflow/manifests/issues/2325
> Use K8s 1.25 for the tests

- README.md
- apps/training-operator/upstream/base/cluster-role.yaml
- apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
- apps/training-operator/upstream/base/crds/kubeflow.org_paddlejobs.yaml
- apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
- apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
- apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
- apps/training-operator/upstream/base/crds/kustomization.yaml
- apps/training-operator/upstream/base/deployment.yaml
- apps/training-operator/upstream/overlays/kubeflow/kubeflow-training-roles.yaml
- apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
- apps/training-operator/upstream/overlays/standalone/kustomization.yaml
Update Training Operator manifests to v1.6.0-rc.0
@johnugeorge @andreyvelich @kimwnasptd
> Update kubeflow/training-operator manifests from v1.6.0-rc.0

- README.md
- apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
- apps/pipeline/upstream/base/cache/cache-deployment.yaml
- apps/pipeline/upstream/base/cache/kustomization.yaml
- apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/pipeline/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
- apps/pipeline/upstream/base/installs/multi-user/persistence-agent/deployment-patch.yaml
- apps/pipeline/upstream/base/installs/multi-user/persistence-agent/kustomization.yaml
- apps/pipeline/upstream/base/installs/multi-user/persistence-agent/params.env
- apps/pipeline/upstream/base/installs/multi-user/view-edit-cluster-roles.yaml
- apps/pipeline/upstream/base/metadata/base/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
- apps/pipeline/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
- apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
- apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml
Update manifests with pipelines version 2.0.0-alpha.6
@kimwnasptd @zijianjoy @connor-mccarthy @gkcalat
> Update kubeflow/pipelines manifests from 2.0.0-alpha.6

- README.md
Update the version in the README to reflect the `v1.7.0-rc.0` version
/cc @DomFleischmann
> README: Update the version for v1.7.0-rc.0

- README.md
- apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
- apps/training-operator/upstream/overlays/standalone/kustomization.yaml
- common/oidc-authservice/base/kustomization.yaml
Sync kubeflow training operator manifests v1.6.0 rc.1
> Sync kubeflow training operator manifests v1.6.0 rc.1

- README.md
- apps/katib/upstream/components/controller/katib-config.yaml
- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
- common/oidc-authservice/base/kustomization.yaml
Resolves #
Sync kubeflow katib manifests v0.15.0 rc.1
> Sync kubeflow katib manifests v0.15.0 rc.1

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/deployment.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/cluster-role.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Update kubeflow/kubeflow manifests from v1.7.0-rc.1
> Update kubeflow/kubeflow manifests from v1.7.0-rc.1

- README.md
Resolves https://github.com/kubeflow/manifests/issues/2358
Replaces https://github.com/kubeflow/manifests/pull/2373 (Discussed with @jbottum and the CNCF transition members in the last meeting)
- Add the release process to the README with reference to the release handbook
/hold for https://github.com/kubeflow/community/pull/610
cc @kimwnasptd @jbottum
> Document the release process for Manifest

- README.md
- apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
- apps/pipeline/upstream/base/cache/kustomization.yaml
- apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/pipeline/upstream/base/metadata/base/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
- apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml
cherrypick #2404 to 1.7 branch
> Update kubeflow/pipelines manifests from 2.0.0-alpha.7 (#2404)

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Update kubeflow/kubeflow manifests for v1.7.0
> Update kubeflow/kubeflow manifests from v1.7.0

- common/oidc-authservice/base/params.env
This PR should complete problem with default redirection after logout
##Issue:
https://github.com/kubeflow/manifests/issues/2431
> fix default after logout redirect

- contrib/ray/README.md
> documentation(ray): fix typo

- common/dex/base/deployment.yaml
Part of https://github.com/kubeflow/manifests/issues/2450
- Upgrade dex to 2.36.0
ref https://github.com/dexidp/dex/releases/tag/v2.36.0 
cc @kimwnasptd
> Upgrade dex to 2.36.0

- README.md
- tests/gh-actions/install_kustomize.sh
- Upgrade kustomize to 5.0.3 which contains a few CVE fixes and bug fix for "awk '!/well-defined/'"
- Remove "awk '!/well-defined/'" from the README
> Upgrade kustomize to 5.0.3

- README.md
- common/cert-manager/README.md
- common/cert-manager/cert-manager/base/cert-manager.yaml
Part of https://github.com/kubeflow/manifests/issues/2450
- Cert Manager to 1.12.2
cc @kimwnasptd
> Upgrade cert-manager to 1.12.2

- .github/workflows/katib_kind_test.yaml
- .github/workflows/train_operator_kind_test.yaml
- tests/gh-actions/install_istio.sh
Resolves https://github.com/kubeflow/manifests/issues/2507
Playing around with instructions found in https://kind.sigs.k8s.io/docs/user/known-issues/#apparmor and https://github.com/actions/runner-images/issues/181#issuecomment-610874237
> Update Katib tests for MySQL issue with GH Runner

- README.md
- contrib/kserve/kserve/kserve-runtimes.yaml
- contrib/kserve/kserve/kserve.yaml
- contrib/kserve/kserve/kserve_kubeflow.yaml
Sync kserve/kserve tag v0.11.0 manifests
WG leads @yuzisun
WG liaison @helloericsf 
> [kubeflow 1.8] Update kserve manifests from v0.11.0

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/deployment.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/cluster-role.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/cluster-role.yaml
- apps/volumes-web-app/upstream/base/deployment.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/viewer-spec.yaml
Sync kubeflow/kubeflow tag v1.8.0-rc.0 manifests.
WG leads @kimwnasptd  @thesuperzapper @kubeflow/wg-manifests-leads 
WG liaison @NohaIhab 
> Update kubeflow/kubeflow manifests from v1.8.0-rc.0

- example/kustomization.yaml
Add pvcviewer-controller to `example/kustomization.yaml`
Part of #2524 
This change should be forward ported to `master`
cc: @kimwnasptd
> chore: add pvcviewer-controller to `example/kustomization.yaml`

- contrib/seldon/Makefile
- contrib/seldon/OWNERS
- contrib/seldon/README.md
- contrib/seldon/example.yaml
- contrib/seldon/seldon-core-operator/base/resources.yaml
* Updating seldon core to v1.17.1
* fix CI test
* Adding SachinVarghese to seldon owners
---------
This PR is a backport of #2532 to `v1.8-branch`
cc: @kimwnasptd @annajung @juliusvonkohout
> Updating seldon core to v1.17.1 (#2532)

- README.md
- apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
- apps/kfp-tekton/upstream/base/cache/kustomization.yaml
- apps/kfp-tekton/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/kfp-tekton/upstream/base/installs/multi-user/persistence-agent/cluster-role.yaml
- apps/kfp-tekton/upstream/base/metadata/base/kustomization.yaml
- apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml
- apps/kfp-tekton/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
- apps/kfp-tekton/upstream/base/pipeline/ml-pipeline-persistenceagent-role.yaml
- apps/kfp-tekton/upstream/env/gcp/inverse-proxy/kustomization.yaml
- apps/kfp-tekton/upstream/env/plain-multi-user/kustomization.yaml
- apps/kfp-tekton/upstream/env/plain/kustomization.yaml
- apps/kfp-tekton/upstream/env/platform-agnostic-tekton-multi-user/kustomization.yaml
- apps/kfp-tekton/upstream/env/platform-agnostic-tekton/kustomization.yaml
- apps/kfp-tekton/upstream/env/platform-openshift-pipelines/kustomization.yaml
- apps/kfp-tekton/upstream/third-party/tekton-custom-task/kustomization.yaml
- apps/kfp-tekton/upstream/v1/base/installs/multi-user/istio-authorization-config.yaml
> Update kubeflow/kfp-tekton manifests from 2.0.1

- README.md
- contrib/kserve/kserve/kserve-runtimes.yaml
- contrib/kserve/kserve/kserve.yaml
- contrib/kserve/kserve/kserve_kubeflow.yaml
- tests/gh-actions/install_kserve.sh
Sync kserve/kserve tag v0.11.1 manifests
WG leads @yuzisun
WG liaison @helloericsf
> Update kserve manifests from v0.11.1

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/manager/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Sync kubeflow/kubeflow tag v1.8.0-rc.3 manifests.
WG leads @kimwnasptd @thesuperzapper @kubeflow/wg-notebooks-leads 
> Update kubeflow/kubeflow manifests from v1.8.0-rc.3

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
Sync kubeflow/kubeflow tag v1.8.0-rc.5 manifests.
WG leads @kimwnasptd @thesuperzapper @kubeflow/wg-notebooks-leads 
> Update kubeflow/kubeflow manifests from v1.8.0-rc.5

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
GA release of kubeflow/kubeflow 1.8.0
cc: @kimwnasptd @thesuperzapper
> Update kubeflow/kubeflow manifests from v1.8.0

- OWNERS
Remove myself from the OWNERS file due to no longer being able to commit as a reviewer.
cc @kubeflow/wg-manifests-leads
> Remove annajung from OWNERS file

- common/istio-1-17/istio-namespace/base/kustomization.yaml
Taking over the https://github.com/kubeflow/manifests/pull/2413
It was discussed during today's KF Manifests WG Meeting to make this small PR to achieve two goals:
* take over and finally merge changes made here: https://github.com/kubeflow/manifests/pull/2413
* ease addition of @kromanow94 to the Kubeflow Members group
Removes copyright headers.
> Remove copyright headers

- .github/pull_request_template.md
Resolves a match to the documentation on master branch
Change to kustomize 5.0.3 the template for the PR
**Checklist:**
- [ x ] Unit tests pass:
**Make sure you have installed kustomize == 5.0.1**
2. `make test`
> Change to kustomize 5.0.3

- apps/pipeline/update.sh
preparation for https://github.com/kubeflow/manifests/pull/2623
> Create update.sh for KFP

- OWNERS
Follow up of https://github.com/kubeflow/manifests/pull/2629#issuecomment-1967214668
> Update OWNERS with emeritus_approvers

- README.md
- common/knative/README.md
Resolves #
remove repetitive words 
**Checklist:**
2. `make test`
> chore: remove repetitive words

- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/katib-config.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
@rimolive @diegolovison 
maybe there are even more components that have been merged in the wrong order and left the master outdated.
> Synchronize katib and kubeflow/kubeflow

- README.md
Information about the minimum hardware to run Kubeflow locally
Information about the minimum hardware to run Kubeflow locally
**Checklist:**
- [ x ] Unit tests pass:
2. `make test`
> Hardware Prerequisites

- README.md
- contrib/kserve/kserve/kserve-cluster-resources.yaml
- contrib/kserve/kserve/kserve.yaml
- contrib/kserve/kserve/kserve_kubeflow.yaml
- contrib/kserve/kserve/kustomization.yaml
- hack/sync-kserve-kserve-manifests.sh
@rimolive 
supersedes https://github.com/kubeflow/manifests/pull/2692
> Sync kserve manifests 0.12.1

- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/katib-config.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
- hack/sync-katib-manifests.sh
- hack/sync-kserve-kserve-manifests.sh
- hack/sync-pipelines-manifests.sh
> Update kubeflow/katib manifests from V0.17.0 rc.0

- common/cert-manager/README.md
- common/cert-manager/cert-manager/base/cert-manager.yaml
@rimolive i hope that 1.14.x is what we planned for.
follow ups will cover knative, istio, seldon, bentoml
> update cert-manager to 1.14.5

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue-report.yml
- Created a Issue Template 
- Created issue templates
- Added contact links from `config.yml`
> Creating Issue templates

- README.md
- tests/gh-actions/kind-cluster.yaml
please /lgtm
@diegolovison @StefanoFioravanzo
> Kubernetes 1.29

- README.md
Resolves 
- https://github.com/kubeflow/manifests/issues/2216
- https://github.com/kubeflow/manifests/issues/2323
- https://github.com/kubeflow/manifests/issues/2495
- https://github.com/kubeflow/manifests/issues/2453
- https://github.com/kubeflow/manifests/issues/2518
@diegolovison @jbottum
> Upgrade guide

- .github/PULL_REQUEST_TEMPLATE.md
- [] 🛠️ Make sure you have installed kustomize == 5.2.1+     
- [] ✍️ Have you written new tests for your core changes, as applicable?      
- [] 🔄 Have you successfully run existing tests with your changes ?    
- [] 🚀 Have you successfully run existing and new tests with your changes ?
- [] All the commits have been _signed-off_  (To pass the `DCO` check)
- [] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the …
> Changed the checkbox style

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue-report.yml
- .github/PULL_REQUEST_TEMPLATE.md
> I fixed requested changes for the PR and ISSUE templates. Changed the slack channel to CNCF slack channel
---     
>You can join our slack channel **wg-manifests** [here](https://www.kubeflow.org/docs/about/community/). This link also contains our meeting schedule.
> Fix requested changes in pr issue templates

- example/kustomization.yaml
Resolves #
**Checklist:**
2. `make test`
> Remove 2 extra spaces

- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/katib-config.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
> Update kubeflow/katib manifests from v0.17.0-rc.1

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
- hack/synchronize-kubeflow-manifests.sh
@rimolive @thesuperzapper @kimwnasptd
> Update kubeflow/kubeflow manifests from 1.9.0-rc.2

- README.md
Improve docs
> I changed the documentation to avoid having extra parameters and moving local files
Fixes https://github.com/kubeflow/manifests/issues/2738
- [ X ] 🛠️ Make sure you have installed kustomize == 5.2.1+     
- [ X ] All the commits have been _signed-off_  (To pass the `DCO` check)
- [ X ] Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) (To pass the `cla/google` check)
---     
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/ …
> Remove --kubeconfig mycluster.yaml and use KUBECONFIG instead of moving files

- README.md
> I documented on how to o change the default dex password.
#2777 
---     
> Documented about how to change default password in README.md

- README.md
- hack/synchronize-katib-manifests.sh
- hack/synchronize-training-operator-manifests.sh
> Synchronize training operator and katib manifests fixes

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
- hack/synchronize-kubeflow-manifests.sh
> Update kubeflow/kubeflow manifests from v1.9.0

- README.md
- hack/synchronize-kserve-web-app-manifests.sh
> Update kserve models web application manifests from 0.13.0

- .github/workflows/kserve_m2m_test.yaml
- .github/workflows/model_registry_test.yaml
- .github/workflows/notebook_controller_m2m_test.yaml
- .github/workflows/pipeline_run_from_notebook.yaml
- .github/workflows/pipeline_test.yaml
> Did some typo changes to workflow YAML files  [https://github.com/kubeflow/manifests/pull/2779/files](https://github.com/kubeflow/manifests/pull/2779/files)
---     
> Typographical changes

- .github/workflows/linting_bash_python_yaml_files.yaml
> I fix the issue of trying to linting on files that were deleted in the PR
> #2824 
---     
> fix issue of trying to linting deleted files in PR

- .github/workflows/pss_test.yaml
> I cadded some changes to PSS workflow test to check for pods status.
---     
> Added changes to pss_test.yaml workflow

- .github/workflows/pss_test.yaml
> I added KF Pipelines to pss github workflow test.
---     
> Refactor .github/workflows/pss_test.yaml

- .github/workflows/dex_test.yaml
- tests/gh-actions/deploy-dex-login-environment/kustomization.yaml
- tests/gh-actions/test_dex_login.py
> re-enable more parts of the dex test

- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- hack/synchronize-kubeflow-manifests.sh
> I changed the script and tags
closes https://github.com/kubeflow/manifests/issues/2849
---     
@thesuperzapper
> Synchronize kubeflow kubeflow manifests v1.9.0

- README.md
- apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
- apps/training-operator/upstream/overlays/standalone/kustomization.yaml
- hack/synchronize-training-operator-manifests.sh
@rimolive @tarekabouzeid please /lgtm
> Synchronize kubeflow training operator manifests v1.8.1

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/deployment.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
- hack/synchronize-kubeflow-manifests.sh
@tarekabouzeid @rimolive for /lgtm
> Synchronize kubeflow/kubeflow manifests v1.9.2

- README.md
Use $HOME .docker/config.json
---     
> Use $HOME .docker/config.json

- common/oauth2-proxy/README.md
> update oauth2-proxy readme

- .github/workflows/pss_test.yaml
- contrib/security/PSS/patches/cluster-jwks-proxy.yaml
> I added a PSS patch yaml file to contrib/security/PSS/patches
---     
> Added a PSS patch for cluster-jwks-proxy deployment

- README.md
- apps/model-registry/upstream/base/kustomization.yaml
- apps/model-registry/upstream/base/model-registry-service.yaml
- apps/model-registry/upstream/options/csi/kustomization.yaml
- hack/synchronize-model-registry-manifests.sh
@tarekabouzeid @varodrig for /lgtm
> Synchronize kubeflow model registry manifests v0.2.12

- contrib/spark/Makefile
- contrib/spark/spark-operator/base/kustomization.yaml
- contrib/spark/spark-operator/base/resources.yaml
@tarekabouzeid  @varodrig for /lgtm
> update spark to 2.1.0

- common/oauth2-proxy/README.md
@tarekabouzeid  @varodrig for /lgtm
> Update oauth2-proxy README.md

- README.md
- apps/training-operator/upstream/overlays/kubeflow/kubeflow-training-roles.yaml
- hack/synchronize-training-operator-manifests.sh
@DnPlas @andreyvelich  for /lgtm and lets try to switch back to proper releases as soon as possible.
> Synchronize kubeflow training operator manifests 778cd72

- README.md
- apps/katib/upstream/components/controller/controller.yaml
- apps/katib/upstream/components/controller/rbac.yaml
- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/components/webhook/webhooks.yaml
- apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/katib-config.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
- hack/synchronize-katib-manifests.sh
@andreyvelich @tarekabouzeid please /lgtm
> Synchronize kubeflow katib manifests v0.18.0 rc.0

- README.md
- contrib/kserve/models-web-app/base/kustomization.yaml
- hack/synchronize-kserve-web-app-manifests.sh
> Synchronize kserve web app manifests v0.14.0 rc.0

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/patches/manager.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/patches/kfam.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
- contrib/ray/README.md
- hack/synchronize-kubeflow-manifests.sh
- tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
follow up of 
https://github.com/kubeflow/manifests/pull/3006
> Synchronize kubeflow kubeflow manifests v1.10.0 rc.1

- proposals/README.md
cc @kubeflow/kubeflow-steering-committee
> docs: Add information about KEP process

- README.md
- apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
- apps/pipeline/upstream/base/cache/kustomization.yaml
- apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
- apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/decorator-controller.yaml
- apps/pipeline/upstream/base/metadata/base/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/kustomization.yaml
- apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
- apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
- apps/pipeline/upstream/third-party/metacontroller/base/kustomization.yaml
- hack/synchronize-pipelines-manifests.sh
fixes https://github.com/kubeflow/manifests/issues/2982
fixes https://github.com/kubeflow/manifests/issues/2952
fixes https://github.com/kubeflow/manifests/issues/2982
fixes https://github.com/kubeflow/manifests/issues/2952
> Update kubeflow/pipelines manifests from 2.4.1

- apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
TO be closed when https://github.com/kubeflow/pipelines/pull/11669 is merged
> Dummy PR for integration tests

- README.md
- apps/model-registry/upstream/base/kustomization.yaml
- apps/model-registry/upstream/options/csi/kustomization.yaml
- apps/model-registry/upstream/options/ui/base/kustomization.yaml
- apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
Periodic update of manifest following periodic release of MR.
Please notice we do not "require" this as part of KF 1.10.rcX
none
none
---     
> Update kubeflow/model-registry manifests from v0.2.15

- README.md
> Update README.md with air gap hints

- experimental/ray/README.md
> Refactoring the experimental/ray README
> NA 
> NA
---     
> Formatted code block to the experimental/ray README

- README.md
- apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
- apps/training-operator/upstream/overlays/standalone/kustomization.yaml
- scripts/synchronize-training-operator-manifests.sh
@tarekabouzeid @andreyvelich for /lgtm
> Synchronize kubeflow training operator manifests v1.9.1

- README.md
- apps/katib/upstream/components/controller/controller.yaml
- apps/katib/upstream/components/controller/trial-templates.yaml
- apps/katib/upstream/components/db-manager/db-manager.yaml
- apps/katib/upstream/components/ui/ui.yaml
- apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
- apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
- apps/katib/upstream/installs/katib-external-db/katib-config.yaml
- apps/katib/upstream/installs/katib-external-db/kustomization.yaml
- apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/katib-config.yaml
- apps/katib/upstream/installs/katib-openshift/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
- apps/katib/upstream/installs/katib-standalone/katib-config.yaml
- apps/katib/upstream/installs/katib-standalone/kustomization.yaml
- apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
- scripts/synchronize-katib-manifests.sh
@andreyvelich @tarekabouzeid @varodrig
> Synchronize kubeflow katib manifests v0.18.0

- README.md
- apps/admission-webhook/upstream/base/kustomization.yaml
- apps/centraldashboard/upstream/base/kustomization.yaml
- apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
- apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
- apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
- apps/profiles/upstream/base/kustomization.yaml
- apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
- apps/pvcviewer-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
- apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
- apps/volumes-web-app/upstream/base/kustomization.yaml
- scripts/synchronize-kubeflow-manifests.sh
> Synchronize kubeflow kubeflow manifests v1.10.0

- README.md
> Update README.md for the 1.10 release

- experimental/ray/test.sh
> related to https://github.com/kubeflow/manifests/pull/3088
---     
> Fix Ray version mismatch in test script

- README.md
- apps/model-registry/upstream/README.md
- apps/model-registry/upstream/base/kustomization.yaml
- apps/model-registry/upstream/options/csi/kustomization.yaml
- apps/model-registry/upstream/options/ui/base/kustomization.yaml
- apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
Periodic update following a periodic MR release
none
none
---     
cc @Al-Pragliola
> Update kubeflow/model-registry manifests from v0.2.16

- README.md
- apps/kserve/models-web-app/base/deployment.yaml
- apps/kserve/models-web-app/base/kustomization.yaml
- scripts/synchronize-kserve-web-application-manifests.sh
> Synchronize kserve web appplication manifests v0.14.0

- common/istio-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
- common/istio-cni-1-24/cluster-local-gateway/base/cluster-local-gateway.yaml
- added `seccompProfile` config in cluster-local-gateway deployment
---     
> Fix PSS warning for cluster-local-gateway

- scripts/lib.sh
- scripts/synchronize-istio-cni-manifests.sh
- scripts/synchronize-istio-manifests.sh
- scripts/synchronize-katib-manifests.sh
- scripts/synchronize-knative-manifests.sh
- scripts/synchronize-kserve-kserve-manifests.sh
- scripts/synchronize-kserve-web-application-manifests.sh
- scripts/synchronize-kubeflow-manifests.sh
- scripts/synchronize-model-registry-manifests.sh
- scripts/synchronize-pipelines-manifests.sh
- scripts/synchronize-spark-operator-manifests.sh
- scripts/synchronize-training-operator-manifests.sh
- scripts/template.sh
> I have updated the synchronize scripts to make them simplified and consistent.
> I have introduced two new file lib.sh for the common functions shared across the scripts and template.sh which can be referred for the standard template
---     
> Making the synchronize scripts consistent

- README.md
- apps/training-operator/upstream/base/deployment.yaml
- apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
- apps/training-operator/upstream/overlays/standalone/kustomization.yaml
- scripts/synchronize-training-operator-manifests.sh
@tarekabouzeid @andreyvelich for /lgtm
> Synchronize training operator manifests v1.9.2

- common/istio-1-24/istio-install/base/gateway.yaml
- common/istio-cni-1-24/istio-install/base/gateway.yaml
- common/istio-cni-1-24/istio-install/base/kustomization.yaml
@tarekabouzeid 
see https://github.com/kubeflow/manifests/blob/533ca9f8c1c97836fae6f5946c76ce31f42dd2c9/common/istio-1-24/istio-install/base/kustomization.yaml#L4
> istio namespace missing

- README.md
> Adding OpenSSF Best Practices and build status

- tests/kserve_test.sh
PipeLine test failing with 503, checking the reason
none
none
---     
> test: Kserve test fail reason

- README.md
last change did not update the pipeline apply command correctly, missing out the applications directory
added the applications directory to the apply line
n/a
n/a
n/a
---     
> fix pipeline application command

- CONTRIBUTING.md
- README.md
- SECURITY.md
> security and contributors.md

- README.md
- tests/metrics-server_resource_table.py
> Add live PVC storage  to resource tracking script.
> Continuation of #3182
---     
> Live PVC storage

- .github/workflows/full_kubeflow_integration_test.yaml
- .github/workflows/pipeline_swfs_test.yaml
- .github/workflows/pipeline_test.yaml
- README.md
- applications/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
- applications/pipeline/upstream/third-party/argo/upstream/manifests/base/workflow-controller/workflow-controller-deployment.yaml
- scripts/synchronize-pipelines-manifests.sh
@HumairAK there seems to be a security regression in KFP, at least the seccomprofile setting for argo seems to be gone.
@akagami-harsh can you investigate?
> Synchronize kubeflow pipelines manifests 2.14.0

- common/oauth2-proxy/components/cluster-jwks-proxy/kustomization.yaml
@akagami-harsh @kunal-511 @tarekabouzeid
> bitnami deprecation

- README.md
- applications/kserve/models-web-app/base/kustomization.yaml
- applications/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
- applications/kserve/models-web-app/overlays/kubeflow/patches/web-app-sidecar.yaml
- scripts/synchronize-kserve-web-application-manifests.sh
@Griffin-Sullivan @LogicalGuy77 for /lgtm
> Synchronize kserve models web app manifests v0.15.0
