kubeflow/manifests

katib/v1alpha1/base/katib-ui-deployment.yaml

I think, we missed ServiceAccount in the Katib-ui manifest.
According to this: https://github.com/kubeflow/manifests/blob/master/katib/v1alpha1/base/katib-ui-rbac.yaml, we should connect Katib-ui ServiceAccount with corresponding deployment.
/assign @hougangliu 
/cc @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/16)

Add ServiceAccount to Katib-ui deploy

---

argo/base/kustomization.yaml
argo/base/service.yaml
common/centraldashboard/base/kustomization.yaml
common/centraldashboard/base/params.env
jupyter/jupyter-web-app/base/kustomization.yaml
jupyter/jupyter-web-app/base/params.env
jupyter/jupyter-web-app/base/service.yaml
jupyter/jupyter/base/kustomization.yaml
jupyter/jupyter/base/params.env
kubebench/base/kustomization.yaml
kubebench/base/params.yaml
kubebench/base/service.yaml
pipeline/pipelines-ui/base/kustomization.yaml
pipeline/pipelines-ui/base/params.yaml
pipeline/pipelines-ui/base/service.yaml
pipeline/pipelines-viewer/base/kustomization.yaml
pipeline/pipelines-viewer/base/params.yaml
pipeline/pipelines-viewer/base/service.yaml
tensorboard/base/kustomization.yaml
tensorboard/base/params.yaml
tensorboard/base/service.yaml
tf-training/tf-job-operator/base/kustomization.yaml
tf-training/tf-job-operator/base/params.yaml
tf-training/tf-job-operator/base/service.yaml

Now, if a service need to be routed by ambassador, $(service-name).$(service-namespace) is in need in its annotations. in kustonmize, service namespace is configured during build. so we'd better set service namespace in its annotations by a var.
before this PR, the namespace is set by configmap, so we must modify the configmap manually each time when we set a new namespace for the application. but if the namespace comes from its service metadata.namespace, we can never modify manually for it any more.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/30)

service namespace var in getambassador.io/config annotations

---

gcp/gcp-credentials-admission-webhook/base/config-map.yaml
hack/gen-test-target.sh
hack/gen-test-targets.sh
hack/utils.sh
tests/Makefile

fixes jupyter_test.go and profiles_test.go are replacing overlays and causing errors in run-tests #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/72)

jupyter_test.go and profiles_test.go are replacing overlays and causing errors in run-tests

---

jupyter/jupyter-web-app/base/cluster-role.yaml

This PR address rbac issue while accessing storageclasses in jupyter-web-app [here](https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/kubeflow_jupyter/default/app.py#L140)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/73)

jupyter-web-app requires access to storageclasses resources

---

jupyter/jupyter/base/stateful-set.yaml

This parameter should be STORAGE_CLASS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/68)

Fix typo of jupyter yaml

---

jupyter/notebook-controller/base/cluster-role.yaml

This PR addresses rbac issue when Notebook controller creates istio virtualservices [here](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/controller/notebook/notebook_controller.go#L249)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/78)

Notebook controller requires rbac to create istio virtualservices

---

tf-training/tf-job-operator/base/crd.yaml
tf-training/tf-job-operator/base/deployment.yaml

Fixes https://github.com/kubeflow/tf-operator/issues/991
Notes:
- Currently using a postsubmit image tag. This will be updated when tf-operator 0.6 image is tagged.
- Both v1beta2 and v1 versions are served for backward compatibility.
- V1beta1 is deprecated and no longer served.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/80)

Update tf-operator to v1

---

gcp/iap-ingress/base/stateful-set.yaml
pipeline/api-service/base/deployment.yaml
pipeline/api-service/base/kustomization.yaml
tests/api-service-base_test.go
tests/iap-ingress-base_test.go
tests/minio-base_test.go
tests/minio-overlays-minioPd_test.go
tests/mysql-overlays-mysqlPd_test.go

bump pipeline api-runner to 1.20 due to crash-loop-backoff
add   volumeClaimTemplates: [] to iap-ingress/base/stateful-set.yaml
regen tests so that things merged to master pass tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/91)

fixes to iap_ingress and pipeline, regenerated tests

---

gcp/iap-ingress/base/policy.yaml
tests/iap-ingress-base_test.go

For https://github.com/kubeflow/kubeflow/issues/3456
That issuer var was replaced by `letencrypt-prod`, which is the issuer for cert.
Here the issuer in the JWT is always going to be `https://cloud.google.com/iap` for IAP
/cc @jlewi @kunmingg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/141)

fix jwt validation

---

pipeline/minio/base/deployment.yaml
pipeline/minio/base/kustomization.yaml
pipeline/minio/base/params.env
pipeline/minio/base/params.yaml
pipeline/minio/base/persistent-volume-claim.yaml
pipeline/minio/overlays/minioPd/kustomization.yaml
pipeline/minio/overlays/minioPd/params.env
pipeline/minio/overlays/minioPd/persistent-volume-claim-patch.yaml
pipeline/mysql/base/kustomization.yaml
pipeline/mysql/base/params.yaml
pipeline/mysql/base/persistent-volume-claim.yaml
pipeline/mysql/overlays/mysqlPd/kustomization.yaml
pipeline/mysql/overlays/mysqlPd/persistent-volume-claim-patch.yaml
tests/iap-ingress-base_test.go
tests/minio-base_test.go
tests/minio-overlays-minioPd_test.go
tests/mysql-base_test.go
tests/mysql-overlays-mysqlPd_test.go

The MySQL, Minio components in the pipelines package need a PVC to work.
Currently, that PVC is created inside the minioPd, mySqlPd overlays.
This only works in GCP enviroments.
This PR refactors the components so that the PVC is created inside the base with a default StorageClass.
The overlays then edit the PVC with their custom values using a strategicMergePatch.
This means that:
* Base will work for clusters with a default storage class.
* The GCP overlay is still working as it was before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/140)

pipelines: add PVC with default StorageClass in MySQL, Minio bases

---

jupyter/jupyter-web-app/base/kustomization.yaml
tests/jupyter-web-app-base_test.go
tests/jupyter-web-app-overlays-application_test.go
tests/jupyter-web-app-overlays-istio_test.go

For https://github.com/kubeflow/kubeflow/issues/3502
/cc @kunmingg @kkasravi 
The new tag is built at 6/8. Old one is 5/2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/157)

update jupyter webapp image

---

common/centraldashboard/base/kustomization.yaml
tests/centraldashboard-base_test.go
tests/centraldashboard-overlays-istio_test.go

Ensures that ClusterRole and ClusterRoleBindings are created with the Central Dashboard deployment.
Fixes #152 
Fixes https://github.com/kubeflow/kubeflow/issues/3501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/159)

Include cluster role configs for Central Dashboard

---

metadata/base/metadata-deployment.yaml
tests/metadata-base_test.go

By default, all services should deploy to `kubeflow` namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/161)

Pointing to the metadata-db service in kubeflow namespace

---

pipeline/pipelines-viewer/base/kustomization.yaml
pipeline/pipelines-viewer/base/params.env
pipeline/pipelines-viewer/base/params.yaml
tests/iap-ingress-base_test.go
tests/minio-base_test.go
tests/minio-overlays-minioPd_test.go
tests/mysql-base_test.go
tests/mysql-overlays-mysqlPd_test.go
tests/pipelines-viewer-base_test.go
tests/profiles-base_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go

the kustomize var viewer-clusterDomain is never used in pipeline/pipelines-viewer/base resources
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/169)

remove unused variable viewer-clusterDomain from pipeline/pipelines-viewer/base/kustomization.yaml, regenerate tests

---

pipeline/pipelines-runner/base/cluster-role.yaml
tests/pipelines-runner-base_test.go

Supplement pipeline-runner permissions according to kubeflow/kubeflow#2556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/186)

Update pipeline-runner permissions

---

tests/tf-job-operator-overlays-application_test.go
tf-training/tf-job-operator/overlays/application/application.yaml

Resolves #
Fix tfjob application CR name.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/224)

Fix tfjob application CR name

---

gcp/iap-ingress/base/config-map.yaml
tests/iap-ingress-base_test.go

This should fix https://github.com/kubeflow/kubeflow/issues/3628. See also https://github.com/kubeflow/kubeflow/pull/3691 (which modified the wrong file).
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/219)

envoy-config: fix port name in setup_backend.sh

---

gcp/basic-auth-ingress/base/cloud-endpoint.yaml
gcp/basic-auth-ingress/base/kustomization.yaml
gcp/basic-auth-ingress/base/params.env
gcp/basic-auth-ingress/base/params.yaml
tests/basic-auth-ingress-base_test.go
tests/iap-ingress-base_test.go
tests/istio-base_test.go
tests/minio-base_test.go
tests/minio-overlays-minioPd_test.go
tests/mysql-base_test.go
tests/mysql-overlays-mysqlPd_test.go
tests/profiles-base_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go

Basic auth cloud endpoint missed target namespace and appName.
This PR patch them to cloud endpoint config.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/243)

Fix basic auth cloud endpoint missing target namespace and appName

---

gcp/cloud-endpoints/base/cluster-role.yaml
tests/cloud-endpoints-base_test.go

Fix an error in https://github.com/kubeflow/manifests/pull/238
The clusterrolebinding's roleref mismatches with clusterrole
https://github.com/kubeflow/manifests/blob/master/gcp/cloud-endpoints/base/cluster-role-binding.yaml#L8
/cc @jlewi 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/247)

Fix manifest for cloud-endpoint

---

prow_config.yaml
tests/workflows/components/kfctl_go_test.jsonnet
tests/workflows/components/params.libsonnet

fix presubmit kfctl
https://github.com/kubeflow/kubeflow/pull/3718 changes how we test presubmit.
We need to make some changes in kubeflow/manifest accordingly.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/249)

Fix presubmit

---

metadata/base/metadata-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-istio_test.go

Without a selector in the resource file itself, kustomize generates a resource that looks like:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
labels:
component: server
kustomize.component: metadata
name: metadata-deployment
namespace: kubeflow
spec:
replicas: 3
selector:
matchLabels:
kustomize.component: metadata
template:
metadata:
labels:
component: server
kustomize.component: metadata
```
this causes the Deployment to match all metadata-related pods (ui, db) which seems not desired.
Resolves #
**Checklist:**
3. `make test`
--- …

add missing selector to metadata-deployment

---

mpi-job/mpi-operator/base/cluster-role-binding.yaml
mpi-job/mpi-operator/base/cluster-role.yaml
mpi-job/mpi-operator/base/crd.yaml
mpi-job/mpi-operator/base/deployment.yaml
mpi-job/mpi-operator/base/kustomization.yaml
mpi-job/mpi-operator/base/params.env
mpi-job/mpi-operator/base/service-account.yaml
mpi-job/mpi-operator/overlays/application/application.yaml
mpi-job/mpi-operator/overlays/application/kustomization.yaml
tests/mpi-operator-base_test.go
tests/mpi-operator-overlays-application_test.go

Resolves #
#227 
mpi-operator kustomize manifests for v1alpha1
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/248)

Kustomize package for mpi-operator (v1alpha1)

---

common/centraldashboard/base/kustomization.yaml
tests/centraldashboard-base_test.go
tests/centraldashboard-overlays-application_test.go
tests/centraldashboard-overlays-istio_test.go

update centraldashboard image
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/263)

update centraldashboard image

---

common/centraldashboard/base/kustomization.yaml
tests/centraldashboard-base_test.go
tests/centraldashboard-overlays-application_test.go
tests/centraldashboard-overlays-istio_test.go

Cherry pick new central dashboard image to v0.6 brancg
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/265)

update centraldashboard image (#263)

---

gcp/basic-auth-ingress/overlays/gcp-credentials/kustomization.yaml
gcp/cloud-endpoints/overlays/gcp-credentials/kustomization.yaml
gcp/iap-ingress/overlays/gcp-credentials/kustomization.yaml
tests/basic-auth-ingress-overlays-gcp-credentials_test.go
tests/cloud-endpoints-overlays-gcp-credentials_test.go
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go

Fix gcp credential problem.
explicitly use patchStrategicMerge instead of patch.
Although kustomize supports patchStrategicMerge, patch, and patchJson6902,
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/glossary.md#patchstrategicmerge
Our kustomize.go only checks patchStrategicMerge and patchJson6902
https://github.com/kubeflow/kubeflow/blob/b376b38268ce6ccec2522aa7ab88c9ec36d705a6////bootstrap/pkg/kfapp/kustomize/kustomize.go#L979
related: https://github.com/kubeflow/kubeflow/issues/3905
**Checklist:**
3. `make test`
--- …

Fix gcp credential

---

argo/base/config-map.yaml
argo/base/kustomization.yaml
argo/base/params.env
tests/argo-base_test.go
tests/argo-overlays-istio_test.go

By default, Argo will use the `docker` containerRuntimeExecutor which it will not work on Kubernetes Cluster that doesn't use docker runtime. Therefore, we want to add the containerRuntimeExecutor field so that users who need different executor runtime can easily change the containerRuntimeExecutor params using kustomize. 
**Checklist:**
3. `make test`
cc: @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/259)

Add containerRuntimeExecutor field for other argo executors

---

application/application/base/stateful-set.yaml
tests/application-base_test.go
tests/application-overlays-application_test.go
tests/application-overlays-debug_test.go

Resolves kubeflow/kubeflow#3812
Added selector and corresponding labels (`app: application-controller`) for pods to the base kustomize package.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/261)

add selector for application controller StatefulSet

---

common/centraldashboard/base/deployment.yaml
common/centraldashboard/base/kustomization.yaml
common/centraldashboard/base/params.env
common/centraldashboard/base/params.yaml
jupyter/jupyter-web-app/base/deployment.yaml
jupyter/jupyter-web-app/base/kustomization.yaml
jupyter/jupyter-web-app/base/params.env
jupyter/jupyter-web-app/base/params.yaml
profiles/base/deployment.yaml
profiles/base/kustomization.yaml
profiles/base/params.env
profiles/base/params.yaml
tests/basic-auth-ingress-overlays-gcp-credentials_test.go
tests/basic-auth-ingress-overlays-managed-cert_test.go
tests/centraldashboard-base_test.go
tests/centraldashboard-overlays-application_test.go
tests/centraldashboard-overlays-istio_test.go
tests/cloud-endpoints-overlays-gcp-credentials_test.go
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go
tests/jupyter-web-app-base_test.go
tests/jupyter-web-app-overlays-application_test.go
tests/jupyter-web-app-overlays-istio_test.go
tests/profiles-base_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go

Resolves #177
Resolves #178
Resolves #179
Resolves #180
Resolves #181
Parameters to customize the userid header and prefix.
Essential for having multi-user capabilities in other-than-GCP platforms.
**Checklist:**
3. `make test`
/assign @kkasravi @jlewi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/274)

parameterize userid header and prefix

---

application/application/overlays/application/application.yaml

Relates to kubeflow/kubeflow#3875
Fix central dashboard version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/297)

fix central dashboard version

---

common/centraldashboard/base/deployment.yaml
tests/centraldashboard-base_test.go
tests/centraldashboard-overlays-application_test.go
tests/centraldashboard-overlays-istio_test.go

Added an environment variable to central dash to target the correct KFAM target
/area centraldashboard
/priority p0
/assign @avdaredevil
/cc @prodonjs @kunmingg @abhi-g
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/298)

[CentralDashboard v2] Added env_var for KFAM Server address

---

tests/scripts/run-tests.sh
tests/workflows/components/workflows.libsonnet

Resolves #
https://github.com/kubeflow/manifests/issues/296
Adds `make generate` as part of the test workflow after checkout of the manifests repo.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/299)

adds make generate to the test workflow

---

dex-auth/README.md
dex-auth/keycloak-gatekeeper/base/config-map.yaml
dex-auth/keycloak-gatekeeper/base/deployment.yaml
dex-auth/keycloak-gatekeeper/base/kustomization.yaml
dex-auth/keycloak-gatekeeper/base/namespace.yaml
dex-auth/keycloak-gatekeeper/base/params.env
dex-auth/keycloak-gatekeeper/base/params.yaml
dex-auth/keycloak-gatekeeper/base/service.yaml
dex-auth/keycloak-gatekeeper/base/virtualservice.yaml
tests/keycloak-gatekeeper-base_test.go

Related issues: #267 
This PR introduces Keycloak Gatekeeper as an OIDC Authenticator for Kubeflow central dashboard.
**Checklist:**
3. `make test`
/cc @swiftdiaries 
/assign @krishnadurai 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/337)

Adds keycloak-gatekeeper as OIDC Authenticator

---

tests/scripts/run-tests.sh
tests/workflows/components/kfctl_go_test.jsonnet
tests/workflows/components/workflows.libsonnet

* Presubmits on v0.6-branch are currently failing. It looks like the problem
is that they are using kubeflow/kubeflow @ master and not the v0.6-branch
of kubeflow/kubeflow.
* Fix #348
* Related to #296 
* Revert #299 - It looks like that PR broke the presubmits on the v0.6-branch.
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/350)

Fix v0.6-branch presubmits; use v0.6-branch of kubeflow/kubeflow

---

kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
prow_config.yaml
tests/workflows/components/kfctl_go_test.jsonnet

GCP KFDef specs should pull deployment manager configs from kubeflow/manifests
* No longer download the kubeflow/kubeflow repository
* Add a GCPPlugin spec.
Related to kubeflow/manifests#241
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/354)

GCP KfDef should pull deployment manager configs from kubeflow/manifests

---

hack/gen-test-target.sh
hack/gen-test-targets.sh
tests/Makefile
tests/basic-auth-ingress-overlays-certmanager_test.go
tests/basic-auth-ingress-overlays-gcp-credentials_test.go
tests/basic-auth-ingress-overlays-managed-cert_test.go
tests/cloud-endpoints-overlays-gcp-credentials_test.go
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go
tests/istio-ingress-overlays-cognito_test.go
tests/istio-ingress-overlays-oidc_test.go
tests/istio-install-base_test.go
tests/keycloak-gatekeeper-base_test.go
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go
tests/seldon-core-operator-base_test.go
tests/seldon-core-operator-overlays-application_test.go

Resolves #356
backticks are escaped as described in the issue.
a second fix is related to returning the earliest 'manifests' in a directory path rather than the latest. If a subdir ends with manifests you will get an error in unit test generation.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/358)

fix for backtick escape error

---

kfdef/kfctl_gcp_iap.yaml

Resolves IAP config's missing headers
Headers are required by Jupyter, Profiles and Central dashboard images
**Checklist:**
3. `make test`
/assign @jlewi @gabrielwen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/381)

Fixes gcp headers in IAP config

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

* 1.12 is now the oldest support version on GKE.
* We want to stay ahead of GKE deprecating the version we are using by
default so we don't get surprised.
* Related to kubeflow/kubeflow#417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/382)

Upgrade to Kubernetes 1.14 for GCP deployments.

---

kfdef/generic/istio/istio-noauth.yaml

PR #376 introduced changes that broke the kfdef/generic/istio package and consequently the kfctl_existing_arrikto config on master. (istio-egressgateway selector doesn't match labels).
This PR reverts the changes to kfdef/generic.
/cc @jlewi @jbrette 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/383)

kfdef: generic: revert #376 

---

kfdef/kfctl_aws_cognito.yaml
kfdef/kfctl_existing_arrikto.yaml
kfdef/kfctl_k8s_istio.yaml

* All the config/manifest files should now be in kubeflow/manifests
* kubeflow/kubeflow#4121 updated kfctl to change the hard coding of the
extra config files to kubeflow/manifests
* Fix #373 - Stop checking out kubeflow/kubeflow in KFDef
* Related to kubeflow/manifests#241 move configs to kubeflow/manifests
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/379)

KFDef specs should no longer be checking out the kubeflow repo.

---

kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml

Update the GCP KFDef specs to enable workload identity
* Related to kubeflow/kubeflow#3638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/390)

Enable workload identity in our KFDef specs.

---

pytorch-job/pytorch-operator/base/kustomization.yaml
tests/pytorch-operator-base_test.go
tests/pytorch-operator-overlays-application_test.go
tests/tf-job-operator-base_test.go
tests/tf-job-operator-overlays-application_test.go
tests/tf-job-operator-overlays-istio_test.go
tf-training/tf-job-operator/base/deployment.yaml
tf-training/tf-job-operator/base/kustomization.yaml

This PR  updates operator images
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/397)

Update operator images

---

metadata/base/kustomization.yaml
metadata/base/metadata-envoy-deployment.yaml
metadata/overlays/istio/virtual-service-metadata-grpc.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

Partially resolves kubeflow/pipelines#2239
Add virtual service for metadata grpc server and point mlmd grpc deployment to newer image with the right service name for the deployed grpc server.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/424)

Metadata fix

---

kfdef/kfctl_anthos.yaml
kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/kfctl_existing_arrikto.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_k8s_istio.yaml

As istio overlay has been removed in #432 , corresponding entry from config files are removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/433)

Remove istio overlay in tf-job-operator

---

kfdef/kfctl_anthos.yaml
kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/kfctl_existing_arrikto.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_k8s_istio.yaml

Katib installation is moved after job operators installation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/434)

Reorder katib manifests

---

katib-v1alpha2/katib-controller/base/katib-controller-rbac.yaml
kfserving/kfserving-install/base/cluster-role.yaml
pipeline/scheduledworkflow/base/cluster-role.yaml
pipeline/scheduledworkflow/base/kustomization.yaml
tests/katib-controller-base_test.go
tests/katib-controller-overlays-application_test.go
tests/kfserving-install-base_test.go
tests/kfserving-install-overlays-application_test.go
tests/pipelines-viewer-base_test.go
tests/scheduledworkflow-base_test.go

Partially Addresses: kubeflow/kubeflow#3938
Read Issue description: kubeflow/kubeflow#3938
Related Issues: kubeflow/kubeflow#4167 #374 
This PR enables a user created through Profiles or Kfam to access the following Custom Resouces within their namespace:
Experiments, Trials, KFServices, ScheduledWorkflows, Viewers
The above ClusterRoles are aggregated to Kubeflow Roles mentioned in #374
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/396)

K8s ClusterRoles for: Katib, Pipelines and KFServing Resources

---

kfdef/kfctl_existing_arrikto.yaml

Remove the metacontroller application from the existing_arrikto
config as it is no longer used.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/404)

kfdef: existing_arrikto: remove metacontroller application

---

tests/workflows/components/kfctl_go_test.jsonnet

* This is a quick fix for the failing presubmits #436
* A better fix would be to use E2E workflow as defined in kubeflow/kubeflow
rather than maintaining a separate copy of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/437)

Fix presubmits; pythonpath needs to include kubeflow/kubeflow/py

---

metadata/base/kustomization.yaml
metadata/base/metadata-envoy-deployment.yaml
metadata/overlays/istio/kustomization.yaml
metadata/overlays/istio/virtual-service-metadata-grpc.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

* Fix metadata deployment for KFP's UI
* Only update metadata test files
* This PR was originally committed as #424 but it got rolled back in #429
in order to fix master.
* This PR is rolling it forward.
* Related to #426
* Changes not in the original PR
* New virtual service needs to be listed in kustomization.yaml
* Port for the virtual service should be 9090 not 80
* Related to kubeflow/pipelines#2239 - update KFP to 0.31 for KF 0.7
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/430)

Restore Metadata fix (#424)

---

jupyter/jupyter-web-app/base/config-map.yaml
tests/jupyter-web-app-base_test.go
tests/jupyter-web-app-overlays-application_test.go

Original PR description
* update configmap to include new jupyter images
* remove signature
* update the required test
* improve the overlay test
This PR was originally rolled back as part of multiple PRs that got rolled back to fix master (#426)
* This PR was not related to the breakage but had to be rolled back in order to allow for a clean roll back
* Related to kubeflow/kubeflow#3725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/438)

Revert Rollback of Add new updated Jupyter notebook images (#401)

---

kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/kfctl_existing_arrikto.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_k8s_istio.yaml
pipeline/api-service/base/config-map.yaml
pipeline/api-service/base/deployment.yaml
pipeline/api-service/base/kustomization.yaml
pipeline/persistent-agent/base/deployment.yaml
pipeline/persistent-agent/base/kustomization.yaml
pipeline/pipeline-visualization-service/base/kustomization.yaml
pipeline/pipelines-ui/base/deployment.yaml
pipeline/pipelines-ui/base/kustomization.yaml
pipeline/pipelines-viewer/base/deployment.yaml
pipeline/pipelines-viewer/base/kustomization.yaml
pipeline/scheduledworkflow/base/deployment.yaml
pipeline/scheduledworkflow/base/kustomization.yaml
tests/api-service-base_test.go
tests/persistent-agent-base_test.go
tests/pipeline-visualization-service-base_test.go
tests/pipelines-ui-base_test.go
tests/pipelines-ui-overlays-istio_test.go
tests/pipelines-viewer-base_test.go
tests/scheduledworkflow-base_test.go

* Update the images to 0.1.31
* We need to include the pipeline-visualization-service
Related to kubeflow/pipelines#2239
Use a config map to specify the config for the ml-pipeline backend server
* Currently it is hardcoded to a config file baked into the docker image.
* Hardcoding a config into the dockerfile generally doesn't seem like a good
idea since its not easy to configure.
* Per kubeflow/pipelines#2101 the hard coded config is actually broken it
is not specifying the hostname and port of the visualization server.
**Which issue is resolved by th
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/392)

Update pipelines manifest to ship 0.1.31

---

jupyter/notebook-controller/base/kustomization.yaml
tests/notebook-controller-base_test.go
tests/notebook-controller-overlays-application_test.go
tests/notebook-controller-overlays-istio_test.go
tests/scripts/run-tests.sh

* It looks like the code may not have actually changed since we last
built the image. Nonethless, lets update the tag to use the sha
as opposed to a tag like v20190911-e8193317-dirty-cd2831
Related to: kubeflow/kubeflow#3655
* Disable the test that images are listed in kustomization.yaml because it doesn't work with digests
* Related to #449 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/443)

Update the notebook-controller image.

---

katib/katib-controller/base/katib-controller-rbac.yaml
tests/katib-controller-base_test.go
tests/katib-controller-overlays-application_test.go
tests/katib-controller-overlays-istio_test.go

Resolves
ClusterRoles were removed along with new manifests
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/448)

Restores Kubeflow based ClusterRoles for Katib in its newer manifests

---

katib/katib-controller/base/katib-manager-deployment.yaml
katib/katib-crds/base/trial-crd.yaml
tests/katib-controller-base_test.go
tests/katib-controller-overlays-application_test.go
tests/katib-controller-overlays-istio_test.go
tests/katib-crds-base_test.go

Related: https://github.com/kubeflow/katib/pull/851, https://github.com/kubeflow/katib/pull/864
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/457)

Minor changes to Katib manifests

---

katib/katib-controller/base/katib-db-deployment.yaml
katib/katib-controller/base/kustomization.yaml
tests/katib-controller-base_test.go
tests/katib-controller-overlays-application_test.go
tests/katib-controller-overlays-istio_test.go

Related: https://github.com/kubeflow/katib/pull/871
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/503)

Adding Katib db liveness check

---

admission-webhook/webhook/base/cluster-role.yaml
jupyter/notebook-controller/base/cluster-role.yaml
kfserving/kfserving-install/base/cluster-role.yaml
kubeflow-roles/base/cluster-roles.yaml
pipeline/pipelines-viewer/base/cluster-role.yaml
pipeline/scheduledworkflow/base/cluster-role.yaml
pytorch-job/pytorch-operator/base/cluster-role.yaml
tests/kfserving-install-base_test.go
tests/kfserving-install-overlays-application_test.go
tests/kubeflow-roles-base_test.go
tests/notebook-controller-base_test.go
tests/notebook-controller-overlays-application_test.go
tests/notebook-controller-overlays-istio_test.go
tests/pipelines-viewer-base_test.go
tests/pytorch-operator-base_test.go
tests/pytorch-operator-overlays-application_test.go
tests/scheduledworkflow-base_test.go
tests/tf-job-operator-base_test.go
tests/tf-job-operator-overlays-application_test.go
tests/webhook-base_test.go
tests/webhook-overlays-application_test.go
tf-training/tf-job-operator/base/cluster-role.yaml

Kustomize CLI manifest application, for e.g. `kustomize build . | kubectl apply -f -` fails with:
```
error validating "STDIN": error validating data: ValidationError(ClusterRole): missing required field "rules" in io.k8s.api.rbac.v1.ClusterRole; if you choose to ignore these errors, turn validation off with --validate=false
```
This seems to be a kubectl client-side validation bug as mentioned in this [comment](https://github.com/kubernetes/kubernetes/issues/73050#issuecomment-457068012)
Another problem is with `make test`, which warns about:
```
nil value at `rules.resourceNames` ignored in mutation attempt
```
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Replaces null values at ClusterRoles with [] - for kubectl CLI compatibility

---

kfserving/kfserving-install/base/cluster-role.yaml
tests/kfserving-install-base_test.go
tests/kfserving-install-overlays-application_test.go

Addresses kubeflow/kfserving#428
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/500)

Fix kfseving clusterrole's API group

---

common/centraldashboard/overlays/application/application.yaml
common/centraldashboard/overlays/application/kustomization.yaml
kfdef/kfctl_anthos.yaml
kfdef/kfctl_existing_arrikto.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_k8s_istio.yaml
tests/centraldashboard-overlays-application_test.go

Resolves #459
update version, instance tags for centraldashboard's application overlay
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/460)

update centraldashboard version, instance tags

---

hack/gen-test-targets.sh

Resolves #308
```
$ ☞  hack/gen-test-targets.sh --help
Usage: hack/gen-test-targets.sh [OPTIONS] <directory>
OPTIONS:
-h | --help
| --add-app <name=version>
| --dry-run
```
Don't specify any target directory, dry-run only
```
$ hack/gen-test-targets.sh --dry-run
generating api-service-overlays-application_test.go from manifests/pipeline/api-service/overlays/application
generating minio-overlays-application_test.go from manifests/pipeline/minio/overlays/application
generating mysql-overlays-application_test.go from manifests/pipeline/mysql/overlays/application
generating persistent-agent-overlays-application_test.go from manifests/pipeline/persistent-agent/overlays/application
generating …
```

Only generate what's changed. Add option to generate overlays/application

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml
gcp/deployment_manager_configs/cluster.jinja

* See https://github.com/kubeflow/kfctl/issues/48 1.14.6-gke-13 has
a bug with workload identity so to work around it we temporarily
pin to 1.14.6-gke-2.
* Fix node autoprovisioning defaults (kubeflow/kubeflow#4259) we need to set
the default service account otherwise we won't be able to
pull images from private GCR.
* Note: We can't set both service account and scopes so we only set
the service account.
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/498)

Workaround workload identity bug and fix node autoprovisioning.

---

gcp/iap-ingress/base/policy.yaml
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-application_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go

Issue: https://github.com/kubeflow/kubeflow/issues/4266
this path should match below two places
1. istio health check path - https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/status/server.go#L43
2. configured hc path for ingress - 
https://github.com/kubeflow/manifests/blob/master/gcp/iap-ingress/base/config-map.yaml#L186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/491)

update jwt excluded_paths

---

istio/istio-install/base/istio-noauth.yaml
tests/istio-install-base_test.go

Resolves #495
>> Documentation only <<
added 
```
- --enable-validation=true
```
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/496)

document istio workaround for 'Internal error occurred: failed calling admission webhook "pilot.validation.istio.io"'

---

common/ambassador/base/service.yaml
gcp/basic-auth-ingress/base/backend-config.yaml
gcp/basic-auth-ingress/base/config-map.yaml
gcp/basic-auth-ingress/base/kustomization.yaml
gcp/iap-ingress/base/config-map.yaml
tests/ambassador-base_test.go
tests/basic-auth-ingress-base_test.go
tests/basic-auth-ingress-overlays-application_test.go
tests/basic-auth-ingress-overlays-certmanager_test.go
tests/basic-auth-ingress-overlays-gcp-credentials_test.go
tests/basic-auth-ingress-overlays-managed-cert_test.go
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-application_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go

* As of GKE 1.13 we can now set the backend timeout using a BackendConfig
https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service
* BasicAuth doesn't have a backendconfig so we need to add one.
* In BasicAuth we are still using Ambassador to handle the auth.
* Improve the setup_backend.sh script for IAP
* This script is only updating the JWT based on IAP; there's no reason
the script should be checking if the backend timeout is set.
* Make the script run for ever to avoid confusing container restarts
* Related to kubeflow/kubeflow#4269 backend timeout not set
* Related to kubeflow/kubeflow#4043 crash looping of iap enabler and backend_updater pods.
* For the kustomize test target generation
* Add an option to regenerate all tests.
* use the current branch when …

On GCP use BackendConfig to set the backend timeout and other improvments

---

metadata/base/metadata-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

- Add the readiness probe so that the pods won't serve traffic until they are connected to the DB.
- Reduce the #replicas from 3 to 2.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/531)

Metadata add readiness probe & reduce replicas#

---

hack/gen-test-targets.sh

Resolves #528
filtering now excludes these directories
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/532)

go generates invalid tests for platform configs

---

pytorch-job/pytorch-operator/base/kustomization.yaml
tests/pytorch-operator-base_test.go
tests/pytorch-operator-overlays-application_test.go
tests/tf-job-operator-base_test.go
tests/tf-job-operator-overlays-application_test.go
tf-training/tf-job-operator/base/kustomization.yaml

Pin operator images to 0.7 tagged one. 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/535)

Update operator images to 0.7tag

---

jupyter/notebook-controller/base/kustomization.yaml
jupyter/notebook-controller/base/params.env
jupyter/notebook-controller/overlays/istio/deployment.yaml
jupyter/notebook-controller/overlays/istio/params.env
tests/notebook-controller-base_test.go
tests/notebook-controller-overlays-application_test.go
tests/notebook-controller-overlays-istio_test.go

As part of `kubeflow/kubeflow` PR [[3945] Configurable Istio Gateway for Notebook Controller](https://github.com/kubeflow/kubeflow/pull/4216), I am adding the possibility to configure which Istio Gateway the Notebook Controller can use for setting up Virtual Services on Istio.
It defaults to `kubeflow/kubeflow-gateway`, which is what is used by default on Kubeflow.
Original issue: `kubeflow/kubeflow` [#3945](https://github.com/kubeflow/kubeflow/issues/3945)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/499)

[3945] Configurable Istio Gateway for Notebook Controller

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml
tests/profiles-overlays-test_test.go

DM will create empty GPU pool by default when user deploy on GKE.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/541)

kubeflow on GCP: create empty GPU pool by default

---

dex-auth/dex-crds/base/kustomization.yaml
dex-auth/dex-crds/overlays/istio/kustomization.yaml
dex-auth/dex-crds/overlays/istio/params.env
dex-auth/dex-crds/overlays/istio/params.yaml
dex-auth/dex-crds/overlays/istio/virtual-service.yaml
istio/oidc-authservice/base/deployment.yaml
istio/oidc-authservice/base/envoy-filter.yaml
istio/oidc-authservice/base/kustomization.yaml
istio/oidc-authservice/base/params.env
istio/oidc-authservice/base/params.yaml
istio/oidc-authservice/base/pvc.yaml
istio/oidc-authservice/base/service.yaml
istio/oidc-authservice/overlays/application/application.yaml
istio/oidc-authservice/overlays/application/kustomization.yaml
kfdef/kfctl_existing_arrikto.yaml
tests/basic-auth-ingress-overlays-application_test.go
tests/dex-crds-overlays-istio_test.go
tests/dex-crds-overlays-ldap_test.go
tests/mxnet-operator-overlays-application_test.go
tests/notebook-controller-overlays-istio_test.go
tests/oidc-authservice-base_test.go
tests/oidc-authservice-overlays-application_test.go
tests/profiles-base_test.go
tests/profiles-overlays-application_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go
tests/profiles-overlays-test_test.go

Resolves #267
Resolves https://github.com/kubeflow/kubeflow/issues/3839
This PR adds the AuthService to manifests.
It also adds those new capabilities to the existing_arrikto config.
Some small changes that were made to the Dex application:
* Add VirtualService in istio overlay.
* Use the latest image built from master, so as to include https://github.com/dexidp/dex/pull/1554
**Checklist:**
3. `make test`
/cc @krishnadurai @elikatsis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/529)

oidc-authservice: add authservice to manifests

---

kfserving/kfserving-install/base/config-map.yaml
tests/kfserving-install-base_test.go
tests/kfserving-install-overlays-application_test.go

Resolves https://github.com/kubeflow/kfserving/issues/441
The explainer config map is missing the key with `alibi`
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/514)

Fix alibi explainer configmap

---

gcp/iap-ingress/base/config-map.yaml
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-application_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go

* Per kubeflow/kubeflow#4342 we have at least 1 report where the backend
id appeared to change over time leading to an invalid JWT policy.
* To address that modify the script that sets the JWT policy to set it
every 5 minutes to the latest value.
* Needs to be cherry-picked onto v0.7-branch.
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/551)

Periodically update the JWT policy for IAP.

---

kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_k8s_istio.yaml

Generated with command:
`kfdef-converter tov1beta1 <filename>`
Related to kubeflow/kubeflow#3703
Fixes #544 
TODOs:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/542)

Migrate KfDef to v1beta1

---

kfserving/kfserving-install/base/config-map.yaml
tests/kfserving-install-base_test.go
tests/kfserving-install-overlays-application_test.go

Update to 0.5.1 version - this version is required to work with the kfserving v1 dataplane
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/555)

Update KFServing ONNX version

---

admission-webhook/webhook/overlays/cert-manager/certificate.yaml
admission-webhook/webhook/overlays/cert-manager/deployment.yaml
admission-webhook/webhook/overlays/cert-manager/kustomization.yaml
admission-webhook/webhook/overlays/cert-manager/mutating-webhook-configuration.yaml
admission-webhook/webhook/overlays/cert-manager/params.env
admission-webhook/webhook/overlays/cert-manager/params.yaml
kfdef/kfctl_existing_arrikto.yaml
tests/webhook-overlays-cert-manager_test.go

Adds support for cert-manager certificate in admission webhook.
Adds support for cert-manager in existing_arrikto config.
/cc @ryandawsonuk @kkasravi 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/549)

existing_arrikto: add cert-manager

---

kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml

Resolves #517 
Add application name and make sure they're populated in `kfctl build`
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/518)

Add application name for seldon and mpi-operator

---

kfdef/kfctl_existing_arrikto.0.7.0.yaml

Pins existing_arrikto to a known and tested version of manifests.
Includes https://github.com/kubeflow/manifests/pull/549 which is not in v0.7-branch.
Will revert to a v0.7-branch commit when all the cherry picks are done.
/cc @ryandawsonuk @jlewi 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/571)

kfdef: existing_arrikto: add v0.7.0 config

---

istio/istio/overlays/https-gateway/kf-istio-resources.yaml
istio/istio/overlays/https-gateway/kustomization.yaml
istio/istio/overlays/https-gateway/params.env
istio/istio/overlays/https-gateway/params.yaml
tests/istio-overlays-https-gateway_test.go

Istio Gateway: kubeflow-gateway currently serves requests through HTTP port 80. This change adds an overlay to kubeflow's istio resources to have kubeflow-gateway serve through HTTPS port 443.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/562)

Configures Istio Gateway to serve through port 443 for HTTPS

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

Related to kubeflow/manifests#508
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/577)

Unpin from GKE 1.14.6-gke.2; 1.14.6 is no longer a valid master.

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml
kfserving/kfserving-install/base/kustomization.yaml
kfserving/kfserving-install/base/statefulset.yaml
tests/kfserving-install-base_test.go
tests/kfserving-install-overlays-application_test.go

* Related to kubeflow/kfserving#486
* The tag for the kfserving image, 0.2.0, this caused a breakage.
With the newest image there is a bug and the kfserving mutator starts
applying itself to non kfserving pods and ends up rejecting them.
* This change rolls back to an earlier image that was used yesterday in my
deployment.
* We remove the $(registry) parameter from kustomization.yaml
We don't want to treat registry as a parameter; this breaks the ability
to use kustomize's ability to override images.
Resolves #
**Checklist:**
3. `make test`
--- …

Fix KFServing preventing notebook (and other pods) form starting.

---

metadata/base/metadata-envoy-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

Fixes https://github.com/kubeflow/manifests/issues/585
The `apps/v1beta2` has been removed from Kubernetes 1.16, so we should stick to `apps/v1` from now on.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/586)

Update deployments to use `apps/v1` api version

---

metadata/base/metadata-envoy-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/588)

Automated cherry pick of #586: Update deployments to use `apps/v1` api version on v0.7-branch.

---

tests/workflows/components/kubeflow_workflow.libsonnet

* The test is running a test for the old ksonnet prototype for TFJob
that test was actually failing and doesn't make sense to continue running
* kubeflow/manifests should actually be updated to using python rather than
jsonnet to define the E2E test workflow and reusing the same python module,
kfctl_e2e_workflow.py, but this is a quick fix.
Related to kubeflow/manifests#595
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/596)

Remove the tfjob tests.

---

kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
pipeline/pipelines-ui/base/deployment.yaml
pipeline/pipelines-ui/overlays/gcp/deployment.yaml
pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
tests/iap-ingress-base_test.go
tests/iap-ingress-overlays-application_test.go
tests/iap-ingress-overlays-certmanager_test.go
tests/iap-ingress-overlays-gcp-credentials_test.go
tests/iap-ingress-overlays-managed-cert_test.go
tests/istio-ingress-overlays-cognito_test.go
tests/istio-ingress-overlays-oidc_test.go
tests/istio-overlays-https-gateway_test.go
tests/pipelines-ui-overlays-gcp_test.go
tests/profiles-base_test.go
tests/profiles-overlays-application_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go
tests/profiles-overlays-test_test.go

Related to https://github.com/kubeflow/pipelines/issues/2501
Mount gcp service account credentials to ml-pipeline-ui.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/594)

Fix ml-pipeline-ui doesn't have gcp permission bug

---

kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
kfdef/kfctl_gcp_iap.0.7.0.yaml
pipeline/pipelines-ui/overlays/gcp/deployment.yaml
pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
tests/basic-auth-ingress-base_test.go
tests/basic-auth-ingress-overlays-application_test.go
tests/basic-auth-ingress-overlays-certmanager_test.go
tests/basic-auth-ingress-overlays-gcp-credentials_test.go
tests/basic-auth-ingress-overlays-managed-cert_test.go
tests/istio-ingress-overlays-cognito_test.go
tests/istio-ingress-overlays-oidc_test.go
tests/mxnet-operator-overlays-application_test.go
tests/notebook-controller-overlays-istio_test.go
tests/pipelines-ui-overlays-gcp_test.go
tests/profiles-base_test.go
tests/profiles-overlays-application_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go
tests/profiles-overlays-test_test.go

* Fix ml-pipeline-ui doesn't have gcp permission bug
* Moved patch to gcp overlay
* Regenerated tests
Cherrypick of https://github.com/kubeflow/manifests/pull/594
Related to kubeflow/pipelines#2501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/602)

Cherrypick "Fix ml-pipeline-ui doesn't have gcp permission bug" (#594)

---

metadata/base/metadata-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

Mitigate issues in https://github.com/kubeflow/metadata/issues/138
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/610)

Reduce metadata #replicas

---

metadata/base/kustomization.yaml
metadata/base/metadata-db-configmap.yaml
metadata/base/metadata-db-deployment.yaml
metadata/base/metadata-db-secret.yaml
metadata/base/metadata-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

This change standardizes the way we specify metadata db configuration through creating a K8 configmap. The change also moves the db user name to metadata-db-secrets.
Resolves https://github.com/kubeflow/manifests/issues/591
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/624)

metadata: Stadardizing metadata db configs

---

metadata/base/kustomization.yaml
metadata/base/metadata-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-istio_test.go

Related to https://github.com/kubeflow/metadata/issues/138, which should be resolved after this PR is cherry-picked to v0.7-branch.
The new MLMD 0.15.1 disables DB table migration by default.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/626)

Update metadata images to use MLMD 0.15.1

---

dex-auth/dex-crds/base/kustomization.yaml
dex-auth/dex-crds/overlays/istio/kustomization.yaml
dex-auth/dex-crds/overlays/istio/params.env
dex-auth/dex-crds/overlays/istio/params.yaml
dex-auth/dex-crds/overlays/istio/virtual-service.yaml
istio/oidc-authservice/base/deployment.yaml
istio/oidc-authservice/base/envoy-filter.yaml
istio/oidc-authservice/base/kustomization.yaml
istio/oidc-authservice/base/params.env
istio/oidc-authservice/base/params.yaml
istio/oidc-authservice/base/pvc.yaml
istio/oidc-authservice/base/service.yaml
istio/oidc-authservice/overlays/application/application.yaml
istio/oidc-authservice/overlays/application/kustomization.yaml
tests/dex-crds-overlays-istio_test.go
tests/dex-crds-overlays-ldap_test.go
tests/oidc-authservice-base_test.go
tests/oidc-authservice-overlays-application_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/615)

Automated cherry pick of #529: istio: oidc-authservice Cherry pick of #529 on v0.7-branch. #529: istio: oidc-authservice

---

kfdef/kfctl_anthos.0.7.0.yaml
kfdef/kfctl_aws.0.7.0.yaml
kfdef/kfctl_aws_cognito.0.7.0.yaml
kfdef/kfctl_existing_arrikto.0.7.0.yaml
kfdef/kfctl_gcp_basic_auth.0.7.0.yaml
kfdef/kfctl_gcp_iap.0.7.0.yaml
kfdef/kfctl_k8s_istio.0.7.0.yaml

Resolves https://github.com/kubeflow/manifests/issues/643
also related: https://github.com/kubeflow/kfserving/issues/568#issuecomment-561974987
0.7.0 kfdef pin the commit of current 0.7 head.
/cc @jlewi @richardsliu 
existing arrikto is already pinning to an earlier commit.
Should we update it as well?
/cc @yanniszark 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/645)

kfdef 0.7.0 pin commit

---

prow_config.yaml

* We want to verify that changes to kubeflow/manifests don't break Kubeflow e2e
* We use to trigger the E2E tests on changes to kubeflow/manifests but we
disabled it because the test broke during the move of kfctl to
kubeflow/manifests
* This PR should fix that.
* Related to kubeflow/manifests#613
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/660)

Trigger kfctl e2e tests on kubeflow/manifests

---

jupyter/jupyter-web-app/base/cluster-role.yaml
jupyter/notebook-controller/base/cluster-role.yaml
tests/jupyter-web-app-base_test.go
tests/jupyter-web-app-overlays-application_test.go
tests/jupyter-web-app-overlays-istio_test.go
tests/notebook-controller-base_test.go
tests/notebook-controller-overlays-application_test.go
tests/notebook-controller-overlays-istio_test.go

Partial fix of https://github.com/kubeflow/kubeflow/issues/3772, used by already merged PR https://github.com/kubeflow/kubeflow/pull/4139
The `notebook-controller` reissues pods and statefulsets events as notebook events, hence, it needs permission to get/list/watch/create events otherwise:
```
Failed to list *v1.Event: events is forbidden: User "system:serviceaccount:kubeflow:notebook-controller-service-account" cannot list resource "events" in API group "" at the cluster scope
```
**Checklist:**
3. `make test`
--- …

Allow nb-controller get/list/watch/create events

---

kfdef/kfctl_anthos.yaml
kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_istio_dex.yaml
kfdef/kfctl_k8s_istio.yaml

Resolves kubeflow/kfctl#73
Update KfDef API version.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/684)

update apiVersion kfdef

---

istio/oidc-authservice/base/envoy-filter.yaml
tests/istio-oidc-authservice-base_test.go
tests/istio-oidc-authservice-overlays-application_test.go
tests/istio-oidc-authservice-overlays-ibm-storage-config_test.go

In the authservice we allow user to set the token in the header **"X-Auth-Token"** to pass the authentication
according to: https://github.com/arrikto/ambassador-auth-oidc/blob/feature-kubeflow/auth.go#L111
This is useful when using command line to interact with Kubeflow service
For example you have to access kubeflow endpoint to do the inference using kfserving, [example](https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow) 
which you can't do the authn against dex within curl command.
In order to allow the  "X-Auth-Token" value to be passed to authservice we have to add  **"X-Auth-Token"** in the `AllowHeaders` field in the envoy-filter
**Checklist:**
2. `make …

Add allowheader X-Auth-Token in authn-filter

---

istio/oidc-authservice/base/kustomization.yaml
istio/oidc-authservice/base/params.yaml
istio/oidc-authservice/base/service.yaml
istio/oidc-authservice/base/statefulset.yaml
istio/oidc-authservice/overlays/application/application.yaml
istio/oidc-authservice/overlays/ibm-storage-config/kustomization.yaml
istio/oidc-authservice/overlays/ibm-storage-config/statefulset.yaml
tests/istio-oidc-authservice-base_test.go
tests/istio-oidc-authservice-overlays-application_test.go
tests/istio-oidc-authservice-overlays-ibm-storage-config_test.go

Resolves https://github.com/kubeflow/kubeflow/issues/4517
Resolves https://github.com/kubeflow/manifests/issues/636
- Change Deployment to StatefulSet as only 1 process can have the
database file open.
- Add `publishNotReadyEndpoints` option to authservice Service, since we
want the whitelisted paths to be served even if the OIDC setup hasn't
completed.
/cc @krishnadurai @ryandawsonuk 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/702)

oidc-authservice: Various fixes

---

argo/base/deployment.yaml
tests/argo-base_test.go
tests/argo-overlays-application_test.go
tests/argo-overlays-istio_test.go
tests/tf-training-tf-job-operator-base_test.go
tests/tf-training-tf-job-operator-overlays-application_test.go
tf-training/tf-job-operator/base/deployment.yaml

Example of https://github.com/kubeflow/manifests/pull/700
Add istio disable injection annotations for two deployments.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/703)

Two examples for disabling istio injection in kubeflow namespace

---

admission-webhook/bootstrap/base/stateful-set.yaml
application/application/base/stateful-set.yaml
application/application/overlays/debug/stateful-set.yaml
aws/aws-efs-csi-driver/base/csi-controller-stateful-set.yaml
aws/aws-fsx-csi-driver/base/csi-controller-stateful-set.yaml
kfserving/kfserving-install/base/statefulset.yaml
metacontroller/base/stateful-set.yaml
seldon/seldon-core-operator/base/seldon-operator-controller-manager-statefulset.yaml
tests/admission-webhook-bootstrap-base_test.go
tests/admission-webhook-bootstrap-overlays-application_test.go
tests/application-application-base_test.go
tests/application-application-overlays-application_test.go
tests/application-application-overlays-debug_test.go
tests/aws-aws-efs-csi-driver-base_test.go
tests/aws-aws-fsx-csi-driver-base_test.go
tests/kfserving-kfserving-install-base_test.go
tests/kfserving-kfserving-install-overlays-application_test.go
tests/metacontroller-base_test.go
tests/seldon-seldon-core-operator-base_test.go
tests/seldon-seldon-core-operator-overlays-application_test.go

Part of https://github.com/kubeflow/pipelines/issues/1223
Unblocks https://github.com/kubeflow/kfctl/pull/131
Add the annotation to disable istio sidecar injection for these stateful sets.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/711)

Add sidecar.istio.io/inject false annotations to all stateful sets in kubeflow ns

---

kfdef/kfctl_ibm.yaml

Resolves #
Currently we need to manually change certain setup on the default kfdef in order to deploy it on IBM Cloud Kubernetes Service. Therefore, we want to include a kfdef that's working with IBM Cloud Kubernetes Service out of the box. We have tested it on our IBM Cloud.
cc @animeshsingh 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/691)

Add kfdef for IBM Cloud Kubernetes Service

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

Resolves #
Thank you for always maintenance and thanks for the review!! 🎉 
Field of `users` exists in `deployment_manager_configs/cluster-kubeflow.yaml`.
But it isn't used in `cluster.jinja` template! (Unless my understanding is wrong)
Unnecessary settings cause misleading, so I want to delete them.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/708)

remove users

---

profiles/base/crd.yaml
profiles/base/deployment.yaml
profiles/base/kustomization.yaml
tests/profiles-base_test.go
tests/profiles-overlays-application_test.go
tests/profiles-overlays-debug_test.go
tests/profiles-overlays-devices_test.go
tests/profiles-overlays-istio_test.go
tests/profiles-overlays-test_test.go

Resolves #
* In kubeflow/kubeflow#707 the path of the binary in the docker image
was changed so we need to update the command in the manifest.
* Fix #724 command is incorrect in kfam image
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/734)

profile & kfam: add livenessProbe; update image

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

for https://github.com/kubeflow/kubeflow/issues/4693
GKE 1.14.9 and 1.14.10 currently incompatible with workload identity
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/741)

kubeflow v0.7 use GKE 1.14.8

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

Related to kubeflow/kubeflow#4693
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/758)

Pin GKE to 1.14.8 because the latest 1.14 release breaks workload identity

---

common/centraldashboard/base/deployment.yaml
tests/common-centraldashboard-base_test.go
tests/common-centraldashboard-overlays-application_test.go
tests/common-centraldashboard-overlays-istio_test.go

Resolves https://github.com/kubeflow/kubeflow/issues/4022
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/777)

centraldashboard livenessProbe

---

tests/tf-training-tf-job-operator-base_test.go
tests/tf-training-tf-job-operator-overlays-application_test.go
tf-training/tf-job-operator/base/deployment.yaml
tf-training/tf-job-operator/base/kustomization.yaml

* The path in the image changed.
* Switch to using args so the manifest is more independent of the binary
location.
* Related to kubeflow/manifests#794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/795)

Update TFJob manifest to work with new distroless image.

---

hack/gen-test-target.sh
metadata/base/metadata-deployment.yaml
metadata/base/metadata-envoy-deployment.yaml
metadata/base/metadata-ui-deployment.yaml
metadata/overlays/db/metadata-db-deployment.yaml
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-db_test.go
tests/metadata-overlays-ibm-storage-config_test.go
tests/metadata-overlays-istio_test.go

Unblocks https://github.com/kubeflow/kfctl/pull/131
Part of kubeflow/pipelines#1223
Supercedes https://github.com/kubeflow/manifests/pull/716
1. Added istio sidecar injection false annotation to metadata deployments
2. Fixed test generation script to also take care of `grpc-params.env`. I'm not sure when was that introduced.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/804)

Added istio sidecar false annotation to metadata deployments

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml
gcp/deployment_manager_configs/cluster.jinja

* kubeflow/kubeflow#4259 GKE now allows setting oauthscopes and VM service
account for NAP pools. We need to use this otherwise private images
won't be accessible.
* kubeflow/kubeflow#3930 Bump NAP resource constraints because these
are global constraints not per node constraints.
* Bump max CPU to 128 CPUs
* Bump memory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/801)

Fix autoprovisioning settings.

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml
gcp/deployment_manager_configs/cluster.jinja

* kubeflow/kubeflow#4259 GKE now allows setting oauthscopes and VM service
account for NAP pools. We need to use this otherwise private images
won't be accessible.
* kubeflow/kubeflow#3930 Bump NAP resource constraints because these
are global constraints not per node constraints.
* Bump max CPU to 128 CPUs
* Bump memory
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/809)

Automated cherry pick of #801: Fix autoprovisioning settings. Cherry pick of #801 on v1.0-branch. #801: Fix autoprovisioning settings.

---

hack/build_kfdef_specs.py
kfdef/kfctl_anthos.v1.0.0.yaml
kfdef/kfctl_anthos.yaml
kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.v1.0.0.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/source/README.md
kfdef/source/master/kfctl_anthos.yaml
kfdef/source/master/kfctl_aws.yaml
kfdef/source/master/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_gcp_basic_auth.yaml
kfdef/source/master/kfctl_gcp_iap.yaml
kfdef/source/master/kfctl_ibm.yaml
kfdef/source/master/kfctl_k8s_istio.yaml
kfdef/source/master/kustomization.yaml
kfdef/source/v1.0.0/kfctl_anthos.yaml
kfdef/source/v1.0.0/kfctl_gcp_basic_auth.yaml
kfdef/source/v1.0.0/kfctl_gcp_iap.yaml
kfdef/source/v1.0.0/kustomization.yaml

* For each KF release we need to define a KFDef spec that overrides certain
values (e.g. the repo of kubeflow/manifests it uses)
* Previously we just did this by modifying the KFDef specs on the release
branch. But this was very costly to maintain; i.e. backporting changes
on master to the release branch
* To make that easier we can generate the KFDef YAML files using kustomize;
this allows us to use overlays to define the changes needed to customize
the specs for a particular version
* We can keep these versioned overlays on master so that the divergence between
master and the branches is very low
* To preserve existing behavior we still check in YAML files. a simple
script build_kfdef_specs.py is provided to generate them.
Related to: kubeflow/kubeflow#4685
Some History:
@kkasravi …

Use kustomize to make it easier to maintain the versioned KFDef specs.

---

jupyter/jupyter-web-app/base/cluster-role.yaml
tests/jupyter-jupyter-web-app-base_test.go
tests/jupyter-jupyter-web-app-overlays-application_test.go
tests/jupyter-jupyter-web-app-overlays-istio_test.go

* Related to #4699: Notebook web server gives error unable to list events
* This error occurs because the notebook UI does a subject access review
on the user. As a result, the user needs to be able to list events.
* To fix this we need to define appropriate view,edit,admin roles that
will be aggregated into the Kubeflow view,edit,admin roles so that
when a user is granted access to a namespace they will get the appropriate
binding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/816)

Address #4699 RBAC permissions for Jupyter web app

---

gcp/basic-auth-ingress/base/ingress.yaml
gcp/basic-auth-ingress/base/kustomization.yaml
gcp/basic-auth-ingress/base/params.env
gcp/iap-ingress/base/ingress.yaml
gcp/iap-ingress/base/kustomization.yaml
gcp/iap-ingress/base/params.env
tests/gcp-basic-auth-ingress-base_test.go
tests/gcp-basic-auth-ingress-overlays-application_test.go
tests/gcp-basic-auth-ingress-overlays-certmanager_test.go
tests/gcp-basic-auth-ingress-overlays-gcp-credentials_test.go
tests/gcp-basic-auth-ingress-overlays-managed-cert_test.go
tests/gcp-iap-ingress-base_test.go
tests/gcp-iap-ingress-overlays-application_test.go
tests/gcp-iap-ingress-overlays-certmanager_test.go
tests/gcp-iap-ingress-overlays-gcp-credentials_test.go
tests/gcp-iap-ingress-overlays-managed-cert_test.go

* On GCP we stopped using certmanager for certificates and switched
to managed certificates
* Users are reporting warnings on the ingress like
Could not determine issuer for ingress due to bad annotations: failed to determine issuer name to be used for ingress resource
* This is coming from cert manager. which was recently added back for Seldon:
kubeflow/manifests#806. So if we remove the annotation that should
prevent cert-manager from trying to provision certificates and hopefully
generating this warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/828)

Remove certmanager annoations on GCP ingress; kubeflow/kubeflow#4716

---

kfdef/kfctl_ibm.yaml

This is related to #717 change. We need to update the same changes to the kubeflow configure file for IBM Cloud Kubernetes Cluster.
Without this change, when you deploy kubeflow to the IBM Cloud K8s Cluster, you will get this error.
`failed to apply: (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize: (kubeflow.error): Code 500 with message: Apply.Run Error [unable to recognize "/tmp/kout661839236": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2", unable to recognize "/tmp/kout661839236": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"]`
--- …

Adding cert manager for the seldon changes

---

jupyter/notebook-controller/base/deployment.yaml
tests/jupyter-notebook-controller-base_test.go
tests/jupyter-notebook-controller-overlays-application_test.go
tests/jupyter-notebook-controller-overlays-istio_test.go

Related to https://github.com/kubeflow/kubeflow/issues/4060
Use default run time metrics path as livenessProbe target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/837)

livenessProbe for notebook-controller

---

gcp/basic-auth-ingress/base/ingress.yaml
gcp/iap-ingress/base/ingress.yaml
tests/gcp-basic-auth-ingress-base_test.go
tests/gcp-basic-auth-ingress-overlays-application_test.go
tests/gcp-basic-auth-ingress-overlays-certmanager_test.go
tests/gcp-basic-auth-ingress-overlays-gcp-credentials_test.go
tests/gcp-basic-auth-ingress-overlays-managed-cert_test.go
tests/gcp-iap-ingress-base_test.go
tests/gcp-iap-ingress-overlays-application_test.go
tests/gcp-iap-ingress-overlays-certmanager_test.go
tests/gcp-iap-ingress-overlays-gcp-credentials_test.go
tests/gcp-iap-ingress-overlays-managed-cert_test.go

* It looks like the annotation `kubernetes.io/tls-acme` is also
a cert-manager annotation.
https://cert-manager.io/docs/usage/ingress/#supported-annotations
* We want to get rid of it since we use managed certificates;
if we don't get rid of it; cert-manager will issue warnings about
bad configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/842)

Remove more cert-manager annotations kubeflow/kubeflow#4716

---

common/centraldashboard/base/deployment.yaml
tests/common-centraldashboard-base_test.go
tests/common-centraldashboard-overlays-application_test.go
tests/common-centraldashboard-overlays-istio_test.go

* centraldashboard should use the new /healthz endpoint for liveness.
* The current endpoint depends on other services like the profile controller
so the liveness probe ends up being a liveness check for those other
services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/846)

centraldashboard use /healthz for liveness probe kubeflow/kubeflow#4022

---

jupyter/jupyter-web-app/base/cluster-role.yaml
tests/jupyter-jupyter-web-app-base_test.go
tests/jupyter-jupyter-web-app-overlays-application_test.go
tests/jupyter-jupyter-web-app-overlays-istio_test.go

* There were some labels that shouldn't have added; they were left over
from bad copy and paste.
* Get rid of events permission; this doesn't actually fix kubeflow/kubeflow#4699
events are cluster scoped resources. So creating a rolebinding has no effect.
* We primarily use Kubeflow roles as rolebindings not clusterrolebindings
so including cluster scoped resources doesn't make much sense.
* Related to kubeflow/kubeflow#4699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/821)

Cleanup notebook UI kubeflow user roles (related to kubeflow/kubeflow#4699)

---

hack/update-instance-labels.sh
pipeline/api-service/overlays/application/application.yaml
pipeline/api-service/overlays/application/kustomization.yaml
pipeline/minio/overlays/application/application.yaml
pipeline/minio/overlays/application/kustomization.yaml
pipeline/mysql/overlays/application/application.yaml
pipeline/mysql/overlays/application/kustomization.yaml
pipeline/persistent-agent/overlays/application/application.yaml
pipeline/persistent-agent/overlays/application/kustomization.yaml
pipeline/pipeline-visualization-service/overlays/application/application.yaml
pipeline/pipeline-visualization-service/overlays/application/kustomization.yaml
pipeline/pipelines-runner/overlays/application/application.yaml
pipeline/pipelines-runner/overlays/application/kustomization.yaml
pipeline/pipelines-ui/overlays/application/application.yaml
pipeline/pipelines-ui/overlays/application/kustomization.yaml
pipeline/pipelines-viewer/overlays/application/application.yaml
pipeline/pipelines-viewer/overlays/application/kustomization.yaml
pipeline/scheduledworkflow/overlays/application/application.yaml
pipeline/scheduledworkflow/overlays/application/kustomization.yaml
tests/pipeline-api-service-overlays-application_test.go
tests/pipeline-minio-overlays-application_test.go
tests/pipeline-mysql-overlays-application_test.go
tests/pipeline-persistent-agent-overlays-application_test.go
tests/pipeline-pipeline-visualization-service-overlays-application_test.go
tests/pipeline-pipelines-runner-overlays-application_test.go
tests/pipeline-pipelines-ui-overlays-application_test.go
tests/pipeline-pipelines-viewer-overlays-application_test.go
tests/pipeline-scheduledworkflow-overlays-application_test.go

* We had previously updated the docker images to 0.2.0 but we
hadn't updated the version specified in the Application resources
because of a lack of tooling.
* Uses the script in kubeflow/testing#596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/848)

Set Pipelines Application versiont to 0.2.0; kubeflow/manifests#796

---

kfserving/kfserving-crds/overlays/application/application.yaml
kfserving/kfserving-crds/overlays/application/kustomization.yaml
kfserving/kfserving-install/overlays/application/application.yaml
kfserving/kfserving-install/overlays/application/kustomization.yaml
tests/kfserving-kfserving-crds-overlays-application_test.go
tests/kfserving-kfserving-install-overlays-application_test.go

* The version of KFServing in 1.0 is 0.2.2; set the application resources
accordingly
* Uses the script kubeflow/testing#596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/849)

Set KFServing version to 0.2.2 in application resources; kubeflow/manifests#834

---

hack/gen-test-target.sh
hack/generate_tests.py
tests/kfserving-kfserving-crds-base_test.go
tests/kfserving-kfserving-crds-overlays-application_test.go
tests/kfserving-kfserving-install-base_test.go
tests/kfserving-kfserving-install-overlays-application_test.go
tests/metadata-base_test.go
tests/metadata-overlays-application_test.go
tests/metadata-overlays-db_test.go
tests/metadata-overlays-ibm-storage-config_test.go
tests/metadata-overlays-istio_test.go

- Exclude kfdef
- Account for directory name with dot
- Rerun generation
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/831)

Regenerate tests

---

katib/katib-controller/overlays/application/application.yaml
katib/katib-controller/overlays/application/kustomization.yaml
katib/katib-crds/overlays/application/application.yaml
katib/katib-crds/overlays/application/kustomization.yaml
metadata/overlays/application/application.yaml
metadata/overlays/application/kustomization.yaml
seldon/seldon-core-operator/overlays/application/application.yaml
seldon/seldon-core-operator/overlays/application/kustomization.yaml
tests/katib-katib-controller-overlays-application_test.go
tests/katib-katib-crds-overlays-application_test.go
tests/metadata-overlays-application_test.go
tests/seldon-seldon-core-operator-overlays-application_test.go

* The version in the application CR should be the version of the application
not Kubeflow
* Since Katib and metadata aren't going 1.0 we should bump the version to
"0.8.0"
* Seldon's version is 1.15
* Note: I'm not including the "v" prefix in the version number. I'm not sure
where that started or why we did it but it looks like a bug. We are
following semantic versioning. So the version is X.Y.Z.
Most likely the v was included as some sort of prefix as part of some larger
tag e.g. to ensure it was interpreted as a string and not an integer.
* Related to kubeflow/manifests#834
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/860)

Set the correct version for Katib,Seldon,metadata kubeflow/manifests#834

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

Related to https://github.com/kubeflow/manifests/issues/757
`1.14.10-gke.21` is available
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/882)

unpin gke version

---

README.md

[ kfctl_default.yaml](https://github.com/kubeflow/manifests) link is broken in the manifest's readme
the kfDef has been changed to v1, updated the example and link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/874)

Update manifest readme

---

istio/cluster-local-gateway/base/cluster-role-binding.yaml
istio/cluster-local-gateway/base/cluster-role.yaml
istio/cluster-local-gateway/base/deployment.yaml
istio/cluster-local-gateway/base/horizontal-pod-autoscaler.yaml
istio/cluster-local-gateway/base/kustomization.yaml
istio/cluster-local-gateway/base/namespace.yaml
istio/cluster-local-gateway/base/params.env
istio/cluster-local-gateway/base/params.yaml
istio/cluster-local-gateway/base/pod-disruption-budget.yaml
istio/cluster-local-gateway/base/service-account.yaml
istio/cluster-local-gateway/base/service.yaml
kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_ibm.yaml
kfdef/kfctl_k8s_istio.yaml
tests/istio-cluster-local-gateway-base_test.go

Parially addresses kubeflow/kfserving#652
**Checklist:**
3. `make test`
/cc @yuzisun @animeshsingh 
/hold
For testing in a Kubeflow cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/876)

Cluster Local Gateway for Istio 1.1.6 - for KFServing

---

istio/add-anonymous-user-filter/base/envoy-filter.yaml
istio/add-anonymous-user-filter/base/kustomization.yaml
kfdef/kfctl_k8s_istio.yaml
tests/istio-add-anonymous-user-filter-base_test.go

Related to kubeflow/kubeflow#4731
Anonymous user anonymous@kubeflow.org added through this manifest to Istio gateway based requests.
Note that this implementation spoofs a user to enable non-auth setups with an anonymous user.
**Checklist:**
3. `make test`
/assign @jlewi @swiftdiaries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/885)

EnvoyFilter to add anonymous@kubeflow.org user to all gateway requests

---

hack/generate_tests.py
istio/istio/base/cluster-roles.yaml
tests/istio-istio-base_test.go
tests/istio-istio-overlays-https-gateway_test.go

* ISTIO rbac roles need to include the API group networking.istio.io
* Otherwise we won't be able to create virtualservices inside notebooks.
We want to do this to deploy things like the mnist frontend and tensorboard
from notebooks.
* Add an option to the regenerate tests script to use an environment
variable to explicitly set the name of the origin repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/896)

ISTIO rbac roles should include networking.istio.io; #891

---

aws/aws-alb-ingress-controller/base/cluster-role.yaml
aws/aws-alb-ingress-controller/base/deployment.yaml
aws/aws-alb-ingress-controller/base/kustomization.yaml
aws/fluentd-cloud-watch/base/configmap.yaml
aws/fluentd-cloud-watch/base/daemonset.yaml
aws/fluentd-cloud-watch/base/kustomization.yaml
aws/infra_configs/cluster_config.yaml
aws/nvidia-device-plugin/base/daemonset.yaml
aws/nvidia-device-plugin/base/kustomization.yaml
tests/aws-aws-alb-ingress-controller-base_test.go
tests/aws-aws-alb-ingress-controller-overlays-application_test.go
tests/aws-aws-alb-ingress-controller-overlays-vpc_test.go
tests/aws-aws-efs-csi-driver-base_test.go
tests/aws-aws-fsx-csi-driver-base_test.go
tests/aws-fluentd-cloud-watch-base_test.go
tests/aws-istio-ingress-overlays-cognito_test.go
tests/aws-istio-ingress-overlays-oidc_test.go
tests/aws-nvidia-device-plugin-base_test.go
tests/aws-nvidia-device-plugin-overlays-application_test.go

Resolves #889 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/890)

Upgrade aws component version

---

kfdef/kfctl_aws.v1.0.0.yaml
kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.v1.0.0.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

Resolves https://github.com/kubeflow/kubeflow/issues/4731
Apply the fix https://github.com/kubeflow/manifests/pull/885 on aws manifest without auth. 
This change needs to be cherry-pick back to v1.0-branch
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/909)

Add EnvoyFilter to add anonymous to all gateway requests in aws no-auth manifest

---

kfdef/kfctl_aws.v1.0.0.yaml
kfdef/kfctl_aws_cognito.v1.0.0.yaml
kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
kfdef/kfctl_gcp_iap.v1.0.0.yaml
kfdef/kfctl_ibm.v1.0.0.yaml
kfdef/kfctl_istio_dex.v1.0.0.yaml
kfdef/kfctl_k8s_istio.v1.0.0.yaml
kfdef/source/master/kfctl_aws.yaml
kfdef/source/master/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_gcp_basic_auth.yaml
kfdef/source/master/kfctl_gcp_iap.yaml
kfdef/source/master/kfctl_ibm.yaml
kfdef/source/master/kfctl_istio_dex.yaml
kfdef/source/master/kfctl_k8s_istio.yaml

Removes drift from source master for these configs
Updates v1.0.0 configs with build_kfdef script
Resolves #
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/913)

Updates and synchronizes config files

---

aws/infra_configs/iam_profile_controller_policy.json

Resolves https://github.com/kubeflow/kubeflow/issues/4403
Policy will be added to IAM role and profile controller service account can talk to AWS to get Role and update policy doc. 
Kfctl has corresponding change as well. 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/917)

Add policy profile controller plugin needs

---

README.md

The kubeflow/manifest readme's [config](https://github.com/kubeflow/kubeflow/tree/master/bootstrap/config) is broken. 
The bootstrap/config folder has been removed, I have updated the link and doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/854)

Fix the broken link for config

---

admission-webhook/webhook/overlays/application/application.yaml
profiles/overlays/application/application.yaml
tests/admission-webhook-webhook-overlays-application_test.go
tests/profiles-overlays-application_test.go

* See kubeflow/kubeflow#4767 - If applications try to take ownership
of cluster scoped resources or resources in other namespaces
this can violate requirements of the K8s GC and lead to unpredictable
behavior.
* It looks like this might be causing the profile controller deployment
to get GC'd after 24 hours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/921)

Applications should not try to take ownership of cluster scoped resources

---

kfdef/kfctl_aws.v1.0.0.yaml
kfdef/kfctl_aws_cognito.v1.0.0.yaml
kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
kfdef/kfctl_gcp_iap.v1.0.0.yaml
kfdef/kfctl_ibm.v1.0.0.yaml
kfdef/kfctl_istio_dex.v1.0.0.yaml
kfdef/kfctl_k8s_istio.v1.0.0.yaml
kfdef/source/v1.0.0/kfctl_aws.yaml
kfdef/source/v1.0.0/kfctl_aws_cognito.yaml
kfdef/source/v1.0.0/kfctl_gcp_basic_auth.yaml
kfdef/source/v1.0.0/kfctl_gcp_iap.yaml
kfdef/source/v1.0.0/kfctl_ibm.yaml
kfdef/source/v1.0.0/kfctl_istio_dex.yaml
kfdef/source/v1.0.0/kfctl_k8s_istio.yaml

* We want to start pinning the v1.0.0 configs to a specific commit
of kubeflow/manifests so that we get stability. This is discussed
more in #4685.
* We will create patch releases 1.0.X as needed.
* I created a release tag which points at the appropriate stable release.
* Related to #4685 cut 1.0 RC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/940)

Pin the 1.0.0 manifests to a specific commit.

---

hack/build_kfdef_specs.py
kfdef/kfctl_ibm.v1.0.0.yaml
kfdef/kfctl_ibm.yaml
kfdef/source/master/kfctl_ibm.yaml

Resolves #
We want to add the envoyfilter fixes at #885 to our IBM kfdef config.
Also fixing a bug on the yaml formatting.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/942)

Update ibm kfdef config with the new envoyfilter

---

aws/aws-istio-authz-adaptor/base/instance.yaml
aws/aws-istio-authz-adaptor/base/kustomization.yaml
aws/aws-istio-authz-adaptor/base/rule.yaml
kfdef/kfctl_aws_cognito.v1.0.0.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws_cognito.yaml
tests/aws-aws-istio-authz-adaptor-base_test.go
tests/aws-aws-istio-authz-adaptor-overlays-application_test.go

Resolves https://github.com/kubeflow/kubeflow/issues/4792
- Remove envoy filter in AWS identity aware manifest
- Add  `name: namespace value: istio-system` to make sure mix adaptor are installed inside istio-system namespace
- optimize parameters
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/944)

Remove envoyfilter in identity aware manifest and fix bugs

---

tests/OWNERS

Current problem is if user change aws manifest, I can not approve PRs.
This allows me to approve changes under `aws` folder. 
Add OWNERS file under `test` folder
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/947)

Add OWNERS file under test folder

---

aws/istio-ingress/base/ingress.yaml
aws/istio-ingress/base/kustomization.yaml
aws/istio-ingress/base/params.yaml
tests/aws-istio-ingress-base_test.go
tests/aws-istio-ingress-overlays-cognito_test.go
tests/aws-istio-ingress-overlays-oidc_test.go
tests/aws-istio-ingress-overlays-secure_test.go

Resolves #946
Fixing loadBalancerScheme issue in ingress annotation.
`loadBalancerScheme` was introduced in the base manifest but there's no `params.yaml` for base and annotation doesn't get updated. no-auth `kfctl_aws.yaml` is affected. Thus, I added one `params.yaml` and modified `kustomization.yaml` file.
**Checklist:**
- [Done] Unit tests have been rebuilt: 
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/952)

Fixing loadBalancerScheme issue in ingress annotation

---

aws/istio-ingress/overlays/oidc/ingress.yaml
tests/aws-istio-ingress-overlays-oidc_test.go

Resolves #945
Since we have the issues like:
```
time="2020-02-23T06:33:18Z" level=error msg="Email doesn't exist in user's claim map[exp:1.582439718e+09 iss:https://kubeflow.auth0.com/ sub:github|4739316]. This is not supported"
time="2020-02-23T06:33:18Z" level=error msg="Email doesn't exist in user's claim map[exp:1.582439718e+09 iss:https://kubeflow.auth0.com/ sub:github|4739316]. This is not supported"
```
We need to add auth scope to override default setting, which is:
```
alb.ingress.kubernetes.io/auth-scope: 'openid email profile'
```
Modified `ingress.yaml`, `kustomize.yaml`, and `params.env` files to fulfill the functionality.
**Checklist:** …

Fix AWS OIDC settings

---

pipeline/pipelines-ui/base/kustomization.yaml
pipeline/pipelines-ui/base/params.yaml
pipeline/pipelines-ui/base/service.yaml
tests/pipeline-pipelines-ui-base_test.go
tests/pipeline-pipelines-ui-overlays-application_test.go
tests/pipeline-pipelines-ui-overlays-gcp_test.go
tests/pipeline-pipelines-ui-overlays-istio_test.go

Resolves #671 
Remove the ambassador annotations from the manifest of the pipelines-ui service
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/951)

remove ambassador annotations from pipelines-ui manifest

---

istio-1-3-1/istio-install-1-3-1/base/daemon-set.yaml
tests/istio-1-3-1-istio-install-1-3-1-base_test.go

Resolves #923.
This adds the following toleration configuration to the `istio-nodeagent` daemonset so that it gets installed in GKE node pools with GPUs:
```
tolerations:
- effect: NoExecute
operator: Exists
- effect: NoSchedule
operator: Exists
```
Issue #923 details the problem in detail.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/941)

Configure tolerations for istio-nodeagent so that it gets installed in GKE GPU node pools

---

pipeline/api-service/base/config-map.yaml
pipeline/api-service/overlays/external-mysql/config-map.yaml
pipeline/pipelines-runner/base/cluster-role-binding.yaml
tests/pipeline-api-service-base_test.go
tests/pipeline-api-service-overlays-application_test.go
tests/pipeline-api-service-overlays-external-mysql_test.go
tests/pipeline-pipelines-runner-base_test.go
tests/pipeline-pipelines-runner-overlays-application_test.go

Resolves https://github.com/kubeflow/kubeflow/issues/4803
1. Use `kf-user` as pipeline default sa.
2. Bind `pipeline-runner` clusterrole to `kf-user` to avoid breaking existing usages.
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/969)

Fix pipeline default service account

---

pipeline/pipelines-ui/overlays/gcp/configmap.yaml
pipeline/pipelines-ui/overlays/gcp/deployment.yaml
pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
tests/pipeline-pipelines-ui-overlays-gcp_test.go

/area pipelines
Resolves https://github.com/kubeflow/kubeflow/issues/4795
* Override KFP tensorboard pod template to use `kf-user` sa so it has GCP permissions.
**Checklist:**
3. `make test`
/cc @amygdala
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/970)

Fix KFP tensorboard no GCP permission

---

aws/istio-ingress/overlays/oidc/ingress.yaml
tests/aws-istio-ingress-overlays-oidc_test.go

To fix a YAML annotation settings in OIDC 
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/982)

Change AWS OIDC manifest settings from auth-idp-cognito to auth-idp-oidc

---

gcp/deployment_manager_configs/cluster-kubeflow.yaml

cherry pick: GKE deprecated version 1.14.8
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/987)

unpin gke version (#882)

---

istio/kfserving-gateway/base/deployment.yaml
istio/kfserving-gateway/base/horizontal-pod-autoscaler.yaml
istio/kfserving-gateway/base/kustomization.yaml
istio/kfserving-gateway/base/service.yaml
kfdef/kfctl_gcp_basic_auth.v1.0.0.yaml
kfdef/kfctl_gcp_basic_auth.yaml
kfdef/kfctl_gcp_iap.v1.0.0.yaml
kfdef/kfctl_gcp_iap.yaml
kfdef/kfctl_ibm.v1.0.0.yaml
kfdef/kfctl_ibm.yaml
kfdef/kfctl_k8s_istio.v1.0.0.yaml
kfdef/kfctl_k8s_istio.yaml
kfdef/source/master/kfctl_gcp_basic_auth.yaml
kfdef/source/master/kfctl_gcp_iap.yaml
kfdef/source/master/kfctl_ibm.yaml
kfdef/source/master/kfctl_k8s_istio.yaml
kfserving/kfserving-install/base/config-map.yaml
knative/knative-serving-install/base/config-map.yaml
knative/knative-serving-install/base/gateway.yaml
tests/istio-kfserving-gateway-base_test.go
tests/kfserving-kfserving-install-base_test.go
tests/kfserving-kfserving-install-overlays-application_test.go
tests/knative-knative-serving-install-base_test.go
tests/knative-knative-serving-install-overlays-application_test.go

Modifies KFServing and KNative Serving config-maps to use this gateway
Addresses: kubeflow/manifests#924
This implementation introduces an alternative Kubeflow ingress-gateway for KFServing. This route was chosen because the existing Kubeflow gateway is protected by Auth in several configurations. The Knative service readiness prober requests fail when they try to probe a KFServing InferenceService since those prober requests are not backed with Authentication credentials.
This implementation is a temporary solution until KNative introduces a solution for probing services behind an authenticated gateway as mentioned in this issue: knative/serving#6829
Related issues:
kubeflow/kfserving#668
/cc @yuzisun …

Adds kfserving ingressgateway for Istio 1.1.6

---

experimental/gcp/template/openapi.yaml

This template is for users who need to create GCP cloud endpoint manually.
Replace Host & Ip before submit
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/996)

publish cloud endpoint API spec template

---

gcp/privateutil/base/iap-jwt-key.yaml
gcp/privateutil/base/kustomization.yaml

When Istio is configured to use IAP jwt, istio need to access
`jwksUri: https://www.gstatic.com/iap/verify/public_key-jwk` for jwt verification.
However above uri is not accessible from a private network.
This PR contains a k8s service that host the same public key as `https://www.gstatic.com/iap/verify/public_key-jwk` to allow jwt verification within cluster.
Note: the config map need update if the IAP public key rotate.
To apply the new pkg, user can either add it to kfdef or directly 
`kustomize build ... | kubectl apply ...`
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/999)

iap jwt public key service

---

spark/spark-operator/base/kustomization.yaml
spark/spark-operator/base/role.yaml
spark/spark-operator/base/rolebinding.yaml
spark/spark-operator/base/spark-sa.yaml
tests/spark-spark-operator-base_test.go
tests/spark-spark-operator-overlays-application_test.go

Spark Operator's example SparkApplication CR fails with an error failing to list or create pods with the service account ~~`spark-sa`.~~
Updates:
- Renames the service account to `spark` as mentioned in spark-operator examples.
This PR adds the necessary role and roleBinding to `spark-sa`
**Checklist:**
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/661)

Adds necessary roles and roleBinding to Spark service account

---

prow_config.yaml

* The PR numbers are now 4 digits (XXXX) as a result the worklfow names
exceeded the Kubernetes limits and the tests aren't running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/1020)

Shorten the name of the workflows to fix the tests #1012.

---

aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
aws/aws-alb-ingress-controller/overlays/vpc/kustomization.yaml
prow_config.yaml
tests/aws-aws-alb-ingress-controller-overlays-application_test.go
tests/aws-aws-alb-ingress-controller-overlays-vpc_test.go

* It looks like there is a bug in the VPC overlay for AWS. It looks like
VPC is a patch but it is listed as a resource.
* This PR changes the kustomization.yaml file to list VPC.yaml as a patch
and not a resource.
* In kustomize "bases" is deprecated. The newer syntax is to just list bases as resources.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/1011)

Fix the aws vpc over manifest.

---

tests/pipeline/OWNERS

This replicates OWNER permissions for pipeline folder. In order to truly let us approve our own changes. See https://github.com/kubeflow/manifests/pull/950#issuecomment-603688741
/cc @rmgogogo @IronPan 
**Checklist:**
3. `make test`

OWNERS for tests/pipeline folder

---

pipeline/api-service/base/config-map.yaml
tests/pipeline/api-service/base/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
tests/pipeline/api-service/overlays/application/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml
tests/pipeline/api-service/overlays/use-kf-user/test_data/expected/~g_v1_configmap_ml-pipeline-config.yaml

Currently the apiserver uses secure=false by default. That means people
using S3 for instance will default to not using TLS which is a security
issue.
Since the bundled minio doesn't support TLS, we should explicitly set
secure=false here and change the apiserver's defaults to secure=true.
**Checklist:**
- [z] Unit tests have been rebuilt: 
3. `make test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/manifests/950)

pipeline/api-service: Set minio secure=false

---

kfdef/kfctl_aws.v1.0.0.yaml
kfdef/kfctl_aws.v1.0.1.yaml
kfdef/kfctl_aws.yaml
kfdef/source/master/kfctl_aws.yaml

Resolves #
Remove istio-ingress component in kfctl_aws
**Checklist:**
3. `make test`

Remove istio-ingress component in kfctl_aws

---

kfdef/source/master/kfctl_gcp_iap.yaml
pipeline/api-service/overlays/use-kf-user/deployment.yaml
pipeline/api-service/overlays/use-kf-user/kustomization.yaml
pipeline/pipelines-runner/overlays/use-kf-user/cluster-role-binding.yaml
pipeline/pipelines-runner/overlays/use-kf-user/kustomization.yaml
tests/pipeline-api-service-overlays-use-kf-user_test.go
tests/pipeline-pipelines-runner-overlays-use-kf-user_test.go

Part of https://github.com/kubeflow/kubeflow/issues/4803
Cherry pick of https://github.com/kubeflow/manifests/commit/ad38b41ae5dce1fd5c77a6c5f69d499c9c157718 and 
https://github.com/kubeflow/manifests/commit/9e6ef8681003c195560fb7b3b75211830c19b7a0
**Checklist:**
3. `make test`
/assign @richardsliu @jlewi

Cherry pick of #969 and #997: fix pipeline default sa

---

pipeline/pipelines-ui/overlays/gcp/configmap.yaml
pipeline/pipelines-ui/overlays/gcp/deployment.yaml
pipeline/pipelines-ui/overlays/gcp/kustomization.yaml
tests/pipeline-pipelines-ui-overlays-gcp_test.go

Resolves #https://github.com/kubeflow/kubeflow/issues/4795
Cherry pick KFP tensorboard permission fix
**Checklist:**
3. `make test`

Cherry pick of Fix KFP tensorboard no GCP permission (#970)

---

kfdef/kfctl_anthos.v1.0.2.yaml
kfdef/kfctl_aws.v1.0.2.yaml
kfdef/kfctl_aws_cognito.v1.0.2.yaml
kfdef/kfctl_gcp_basic_auth.v1.0.2.yaml
kfdef/kfctl_gcp_iap.v1.0.2.yaml
kfdef/kfctl_ibm.v1.0.2.yaml
kfdef/kfctl_istio_dex.v1.0.2.yaml
kfdef/kfctl_k8s_istio.v1.0.2.yaml
kfdef/source/v1.0.2/kfctl_anthos.yaml
kfdef/source/v1.0.2/kfctl_aws.yaml
kfdef/source/v1.0.2/kfctl_aws_cognito.yaml
kfdef/source/v1.0.2/kfctl_gcp_basic_auth.yaml
kfdef/source/v1.0.2/kfctl_gcp_iap.yaml
kfdef/source/v1.0.2/kfctl_ibm.yaml
kfdef/source/v1.0.2/kfctl_istio_dex.yaml
kfdef/source/v1.0.2/kfctl_k8s_istio.yaml
kfdef/source/v1.0.2/kustomization.yaml

Part of https://github.com/kubeflow/kubeflow/issues/4929
I am pinning the manifests to v1.0-branch head for now. When we have cut a release (i.e. created a tag), I will update this again.

v1.0.2 manifests

---

tests/workflows/components/workflows.libsonnet

* Presubmits are broken #1103.
* There is an error fetching go modules. The error appears to be related
to using go 1.12. This PR updates the worker image to a newly built test
worker image which uses go 1.14. When I ran the tests in the newly
built image they passed.

Fix unittests by upgrading to go 1.14

---

pipeline/pipelines-runner/base/cluster-role.yaml
tests/tests/legacy_kustomizations/pipelines-runner/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pipeline-runner.yaml

Sync permissions to manifest.
Related issues: 
https://github.com/kubeflow/pipelines/issues/3389
https://github.com/kubeflow/pipelines/issues/2455
Sync the permission from kubeflow/pipeline to kubeflow/manifests
**Checklist:**
3. `make test`

Update resources in pipeline-runner role

---

common/spartakus/base/deployment.yaml
common/spartakus/base/kustomization.yaml
default-install/base/kustomization.yaml
stacks/examples/kfctl_gcp_stacks.experimental.yaml
stacks/gcp/kustomization.yaml
tests/legacy_kustomizations/default-install/kustomization.yaml
tests/legacy_kustomizations/spartakus/kustomization.yaml
tests/stacks/examples/alice_gcp/test_data/expected/kubeflow.org_v1beta1_profile_anonymous.yaml
tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-admin.yaml
tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-edit.yaml
tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-admin.yaml
tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-edit.yaml
tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-view.yaml
tests/stacks/examples/alice_gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-view.yaml
tests/stacks/examples/alice_gcp/test_data/expected/~g_v1_configmap_default-install-config-h877hbtmf7.yaml
tests/stacks/gcp/test_data/expected/kubeflow.org_v1beta1_profile_anonymous.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-admin.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-edit.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-admin.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-edit.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-kubernetes-view.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-view.yaml
tests/stacks/gcp/test_data/expected/~g_v1_configmap_default-install-config-h877hbtmf7.yaml
tests/tests/legacy_kustomizations/default-install/test_data/expected/~g_v1_configmap_default-install-config-6mcgbmmtg6.yaml
tests/tests/legacy_kustomizations/spartakus/test_data/expected/apps_v1_deployment_spartakus-volunteer.yaml
tests/tests/legacy_kustomizations/spartakus/test_data/expected/~g_v1_configmap_spartakus-config.yaml

* Convert default-install and spartakus to v3.
* For default-install we need to change the name of the configmap to match
the configmap that will be generated by kfctl.
* Modify spartakus to work with v3 and stacks; we need to change the
config map name to match the config map generated by kfctl with
application parameters.
* To fix the tests we need to change the name of the config maps.
Related to #1062

v3 versions of default-install, kubeflow-roles, and spartakus

---

mpi-job/mpi-operator/base/cluster-role.yaml
mxnet-job/mxnet-operator/base/cluster-role.yaml

Resolves #1107
I add aggregation rules to `mpi-operator` and `mxnet-operator`, thus, we can then create `mpijobs` and `mxjobs` resources within Kubeflow notebook. 
**Checklist:**
3. `make test`

Add aggregation rule for mpi-operator and mxnet-operator clusterroles

---

mpi-job/mpi-operator/base/cluster-role.yaml
mpi-job/mpi-operator/base/crd.yaml
mpi-job/mpi-operator/base/deployment.yaml
mpi-job/mpi-operator/base/kustomization.yaml
mpi-job/mpi-operator/base/params.env
mpi-job/mpi-operator/overlays/application/application.yaml
mpi-job/mpi-operator/overlays/application/kustomization.yaml

Resolves https://github.com/kubeflow/mpi-operator/issues/227.
This PR upgrades mpi-operator manifests to v1
**Checklist:**
3. `make test`

upgrade mpi-operator manifests to v1

---

metadata/overlays/google-cloudsql/README.md
metadata/overlays/google-cloudsql/kustomization.yaml
metadata/overlays/google-cloudsql/metadata-deployment.yaml
metadata/overlays/google-cloudsql/params.env

This PR adds an overlay for metadata to use Google CloudSQL.
**Checklist:**
3. `make test`

Add google-cloudsql overlay for metadata

---

hack/generate_tests.py
tests/Makefile

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
Resolves #
This allows users to specify paths to different Python and Kustomize binary in case they want to test out using different versions of Python or Kustomize.
**Checklist:**
3. `make test`

Allow to specify paths to different Python and Kustomize binary

---

metadata/base/metadata-deployment.yaml
tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-deployment.yaml

This fixes https://github.com/kubeflow/metadata/issues/198 partially. It only addresses the metadata server deployment, not the grpc one.
The grpc deployment doesn't seem to have a health endpoint. I've tried running https://github.com/grpc-ecosystem/grpc-health-probe to see if that's an option but getting an error that `grpc.health.v1.Health` isn't supported. So this is more involved and IMO should be addressed in another PR.
Copy readiness probe as liveness probe.
**Checklist:**
3. `make test`
--- …

metadata deployment: Add liveness probe

---

xgboost-job/xgboost-operator/base/cluster-role-binding.yaml
xgboost-job/xgboost-operator/base/cluster-role.yaml
xgboost-job/xgboost-operator/base/crd.yaml
xgboost-job/xgboost-operator/base/deployment.yaml
xgboost-job/xgboost-operator/base/kustomization.yaml
xgboost-job/xgboost-operator/base/params.yaml
xgboost-job/xgboost-operator/base/service-account.yaml
xgboost-job/xgboost-operator/base/service.yaml
xgboost-job/xgboost-operator/overlays/application/application.yaml
xgboost-job/xgboost-operator/overlays/application/kustomization.yaml

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
Resolves #1112
This adds the manifests for v1alpha1 XGBoostJob. 
**Checklist:**
3. `make test`

Add v1alpha1 XGBoostJob manifests

---

gcp/v2/management/cluster/cluster.yaml
gcp/v2/management/cluster/nodepool.yaml

* Use name; not cluster-name
* Use location; not zone
* Fix the nodepool otherwise anthoscli will give an error.

Standardize names for management blueprint.

---

cert-manager/cert-manager/kubeflow-issuer/kustomization.yaml
cert-manager/cert-manager/overlays/application/application.yaml
cert-manager/cert-manager/overlays/application/kustomization.yaml
cert-manager/cert-manager/overlays/self-signed/kustomization.yaml
cert-manager/cert-manager/v3/kustomization.yaml
tests/tests/legacy_kustomizations/cert-manager/test_data/expected/app.k8s.io_v1beta1_application_cert-manager.yaml

* To fix the race condition with certmanager (#1121) we move the KF
issuer into a separate package from the package deploying kubeflow.
This way we can wait for cert-manager to start before deploying resources.
* Labels need to be immutable otherwise upgrades won't work (see #1131).
So remove version number from common labels and application selector
so that apply will work to update resources.

Fix certmanager race condition and version numbers.

---

README.md
docs/KustomizeBestPractices.md

* See http://bit.ly/kf_kustomize_v3
* Its been over a year since we started migrating to kustomize. In that time
kustomize has evolved and we have learned a lot about how to use
kustomize effectively.
* Some of the initial usage patterns have turned out to be problematic (e.g. vars) and there are now better options.
* Update the style guide to better document best practices.
Related to #1062

Create an updated style/best practices guide for kustomize packages.

---

prow_config.yaml

Resolves #
This script has been moved to a new location.
**Checklist:**
3. `make test`

Fix the link to run_e2e_workflow.py script

---

aws/aws-efs-csi-driver/overlays/application/application.yaml
aws/aws-efs-csi-driver/overlays/application/kustomization.yaml
aws/aws-fsx-csi-driver/overlays/application/application.yaml
aws/aws-fsx-csi-driver/overlays/application/kustomization.yaml
aws/aws-istio-authz-adaptor/overlays/application/application.yaml
aws/fluentd-cloud-watch/overlays/application/application.yaml
aws/fluentd-cloud-watch/overlays/application/kustomization.yaml
aws/nvidia-device-plugin/overlays/application/application.yaml
aws/nvidia-device-plugin/overlays/application/kustomization.yaml

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
Resolves #
In progress of moving to v3 compatible manifest, I'd like to submit this as independent changes.
Add and update application overlays for aws components.
**Checklist:**
3. `make test`

Update applications overlays for aws components

---

jupyter/jupyter-web-app/overlays/aws/kustomization.yaml
jupyter/jupyter-web-app/overlays/aws/spawner_ui_config.yaml
kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

Resolves #1125 
AWS users require to have a by-default ECR image when creating JupyterNotebook Server. 
Add on overlay folder called `aws`, and create `kustomization.yaml` and `configmap_patch.yaml` files to patch the jupyter-web-app's configmap with AWS ECR Container image.
**Checklist:**
3. `make test`

Add support for AWS JupyterNotebook Image

---

mpi-job/mpi-operator/base/crd.yaml

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>
Resolves #1166
/cc @apryiomka @stpabhi
Fixes the following issue:
```
time="2020-05-14T22:16:48Z" level=warning msg="Encountered error applying application mpi-operator: (kubeflow.error): Code 500 with message: Apply.Run Error unable to recognize "/tmp/kout844630924": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"" filename="kustomize/kustomize.go:202"
```
**Checklist:**
3. `make test`

Correct MPIJob CRD's apiVersion

---

gcp/v2/management/cluster/cluster.yaml

* Releated to kubeflow/gcp-blueprints#12

Use stable release channel for the GKE management cluster.

---

spark/spark-operator/base/deploy.yaml
tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml

Resolves #
Initializers have been deprecated and removed. Check [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/678)
**Checklist:**
3. `make test`

remove initializers from deployment.

---

application/application-crds/base/crd.yaml
aws/aws-istio-authz-adaptor/overlays/application/application.yaml
aws/nvidia-device-plugin/overlays/application/application.yaml
cert-manager/cert-manager-crds/base/crd.yaml
jupyter/notebook-controller/base/crd.yaml
kfserving/kfserving-crds/base/crd.yaml
profiles/base/crd.yaml
spark/spark-operator/base/scheduledsparkapplications.sparkoperator.k8s.io-crd.yaml
spark/spark-operator/base/sparkapplications.sparkoperator.k8s.io-crd.yaml
tests/stacks/examples/alice_gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_notebooks.kubeflow.org.yaml
tests/stacks/examples/alice_gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_profiles.kubeflow.org.yaml
tests/stacks/gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_notebooks.kubeflow.org.yaml
tests/stacks/gcp/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_profiles.kubeflow.org.yaml
tests/tests/legacy_kustomizations/application-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_applications.app.k8s.io.yaml
tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_certificaterequests.cert-manager.io.yaml
tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_certificates.cert-manager.io.yaml
tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_challenges.acme.cert-manager.io.yaml
tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_issuers.cert-manager.io.yaml
tests/tests/legacy_kustomizations/cert-manager-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_orders.acme.cert-manager.io.yaml
tests/tests/legacy_kustomizations/kfserving-crds/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_inferenceservices.serving.kubeflow.org.yaml
tests/tests/legacy_kustomizations/notebook-controller/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_notebooks.kubeflow.org.yaml
tests/tests/legacy_kustomizations/profiles/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_profiles.kubeflow.org.yaml
tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
tests/tests/legacy_kustomizations/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
tests/validate_resources_test.go
xgboost-job/xgboost-operator/base/crd.yaml

* kubeflow/manifests#1174 lots of CRDs have status fields which
causes ACM to complain that the CRD is invalid.
* This PR cleans up those CRDs and adds an appropriate validation test.
* Fix typos in AWS application specs (kubeflow/testing#668)

CRDs should not have status field.

---

gcp/v2/asm/istio-operator.yaml

Deploy by https://github.com/kubeflow/gcp-blueprints got this problem
**Checklist:**
3. `make test`

Fix meshID and gcloud.compute.zone parameter set by kpt

---

gcp/v2/cnrm/cluster/cluster.yaml

* For the GCP blueprint the Kubeflow cluster should use the
stable release channel rather than using minMasterVersion
* Also add node autoprovisioning settings.

GCP CNRM should use release channels and autoprovisioning

---

plugins/kustomize/plugin/kfdef.apps.kubeflow.org/v1alpha1/KfDef

* Remove the plugins directory; I don't know what purpose it was intended
for but I don't think we are using it anymore.
* plugins contains a .so which based on the comments looks like it
might be the application controller.
* This .so is 28Mb. This is almost 50% of the total size of the manifest
repo which is 72 M
* We want to remove it because we want to make it more lightweight for
people to fetch and check in forks of the manifests repo.
* Fix #1173

Remove plugins; applications.so

---

gcp/OWNERS
gcp/v2/cnrm/cluster/cluster.yaml

* Add GCS scope to the VM service account otherwise we won't be
able to pull private images.
* Create an OWNERs file inside the GCP directory.

Add GCS scope to the cluster; create an OWNERs file.

---

katib/components/katib-crds/kustomization.yaml
katib/components/katib-db-manager/kustomization.yaml
katib/components/katib-db-mysql/kustomization.yaml
katib/installs/katib-external-db/kustomization.yaml
katib/installs/katib-standalone/kustomization.yaml
tests/katib/installs/katib-external-db/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
tests/katib/installs/katib-external-db/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
tests/katib/installs/katib-external-db/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
tests/katib/installs/katib-external-db/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml
tests/katib/installs/katib-standalone/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_experiments.kubeflow.org.yaml
tests/katib/installs/katib-standalone/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_suggestions.kubeflow.org.yaml
tests/katib/installs/katib-standalone/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_trials.kubeflow.org.yaml
tests/katib/installs/katib-standalone/test_data/expected/app.k8s.io_v1beta1_application_katib-crds.yaml

I added Katib CRDs to components, see discussion: https://github.com/kubeflow/manifests/pull/1124#issuecomment-618634808.
Also, I added `commonLabels` to `components/katib-db-manager` and `components/katib-db-mysql` and I removed `commonLabels` from `installs/katib-standalone` since it is not required.
@jlewi What do you think about Katib manifests v3 version? `katib/installs` and `katib/components` satisfies the V3 manifests rules.
I can delete current v3 manifests and make `installs` and `components` under `v3` folder.
/assign @jlewi @gaocegege @johnugeorge 
**Checklist:**
3. `make test`

Add Katib CRD to components

---

pipeline/pipeline-visualization-service/base/kustomization.yaml
tests/tests/legacy_kustomizations/pipeline-visualization-service/test_data/expected/apps_v1_deployment_ml-pipeline-visualizationserver.yaml
tests/tests/legacy_kustomizations/pipeline-visualization-service/test_data/expected/~g_v1_service_ml-pipeline-visualizationserver.yaml

Signed-off-by: Ilias Katsakioris <elikatsis@arrikto.com>
---
Related to kubeflow/pipelines#3849.
**Checklist:**
3. `make test`

KFP visualization-service: Fix double ml-pipeline- prefix in names

---

aws/istio-ingress/base/ingress.yaml

Resolves #869 
NetworkPolicy in the extensions/v1beta1 API version is no longer served is 1.16. We migrate to use the networking.k8s.io/v1 API version, available since v1.8. 
**Checklist:**
3. `make test`

[AWS] Upgrade ingress APIVersion to support k8s 1.16

---

katib/components/katib-controller/kustomization.yaml
katib/components/katib-db-manager/kustomization.yaml
katib/katib-controller/base/katib-configmap.yaml
katib/katib-controller/base/katib-ui-rbac.yaml
katib/katib-controller/base/kustomization.yaml
katib/katib-controller/base/trial-template-configmap-labeled.yaml
tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-controller.yaml
tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
tests/katib/installs/katib-external-db/test_data/expected/apps_v1_deployment_katib-ui.yaml
tests/katib/installs/katib-external-db/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
tests/katib/installs/katib-external-db/test_data/expected/~g_v1_configmap_katib-config.yaml
tests/katib/installs/katib-external-db/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-controller.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-ui.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/~g_v1_configmap_katib-config.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-controller.yaml
tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-ui.yaml
tests/katib/installs/katib-standalone/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
tests/katib/installs/katib-standalone/test_data/expected/~g_v1_configmap_katib-config.yaml
tests/katib/installs/katib-standalone/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-controller.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-ui.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-ui.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/~g_v1_configmap_katib-config.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/~g_v1_configmap_trial-template-labeled.yaml

Part of: https://github.com/kubeflow/katib/issues/1211.
This is the manifests changes for Katib in Kubeflow 1.1.
I updated images version to the latest commit and I made few changes according to the Katib release issue.
/assign @jlewi @johnugeorge @gaocegege 
**Checklist:**
3. `make test`

Katib manifests for Kubeflow 1.1

---

xgboost-job/xgboost-operator/base/deployment.yaml

Resolves #
unmatched label for deployment config
I updated the deployment config file two weeks ago, but I ignore a mistake, I found it when I test the xgboost-operator V1. Sorry about that.

unmatched label for deployment config

---

kfdef/kfctl_istio_dex.yaml

Resolves https://github.com/kubeflow/kfserving/issues/874
In the [istio resource](https://github.com/kubeflow/manifests/blob/5b2ecb760b36cd95fea1071a761b2659225eb0e2/istio/istio/base/kf-istio-resources.yaml#L111) we are whitelisting `istio-system`, so the rbac mode should be `ON_WITH_EXLUSION` instead of `ON`
**Checklist:**
3. `make test`

Use ON_WITH_EXCLUSION for istio dex

---

pytorch-job/pytorch-operator/base/cluster-role.yaml
tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml
tests/tests/legacy_kustomizations/pytorch-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-edit.yaml
tests/tests/legacy_kustomizations/pytorch-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_kubeflow-pytorchjobs-view.yaml
tests/tests/legacy_kustomizations/pytorch-operator/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_pytorch-operator.yaml

I added `pytorchjobs/finalizers` resource to RBAC for PyTorch operator.
See this PR: https://github.com/kubeflow/pytorch-operator/pull/276.
/assign @johnugeorge 
/cc @jlewi @vpavlin @gaocegege 
**Checklist:**
3. `make test`

Update PyTorch operator RBAC for Kubeflow 1.1

---

admission-webhook/webhook/base/mutating-webhook-configuration.yaml
profiles/base/kustomization.yaml
tests/stacks/examples/alice/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
tests/stacks/generic/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
tests/tests/legacy_kustomizations/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/tests/legacy_kustomizations/webhook/test_data/expected/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_admission-webhook-mutating-webhook-configuration.yaml
tests/validate_resources_test.go

Resolves #1213 
Resolves kubeflow/kubeflow#4808
- Update the profile control to the latest version, which includes the `app.kubernetes.io/part-of: kubeflow-profile` label when creating a new namespace
- Update admission mutating webhook with namespaceSelector using the new label.
- Add new unit case to make sure all the mutating webhooks that change the pod will need to have either namespaceSelector or objectSelector.
**Checklist:**
3. `make test`

Add namespace selector and test case for admission

---

pytorch-job/OWNERS
tests/OWNERS
tf-training/OWNERS

I added OWNERS file for TF and PyTorch operators.
See comment: https://github.com/kubeflow/manifests/pull/1283#issuecomment-646598494
/cc @gaocegege @johnugeorge 
**Checklist:**
3. `make test`

OWNERS for TF and PyTorch operators

---

aws/istio-ingress/base/ingress.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_tf-job-operator.yaml

Resolves #1291
Fix ingress api version from v1 to v1beta1. This is bug found by Jeremy. Appreciate that!
**Checklist:**
3. `make test`

Fix aws ingress api version bug

---

aws/aws-alb-ingress-controller/overlays/application/kustomization.yaml
kfdef/kfctl_aws.yaml
kfdef/source/master/kfctl_aws.yaml

Resolves #1164 
Integrated Dex as basic authentication option in AWS Kubeflow.
**Checklist:**
3. `make test`

Add Support For AWS Dex Basic-Authentication

---

xgboost-job/xgboost-operator/base/cluster-role.yaml
xgboost-job/xgboost-operator/base/crd.yaml
xgboost-job/xgboost-operator/overlays/application/application.yaml

Resolves https://github.com/kubeflow/xgboost-operator/issues/94
**Checklist:**
3. `make test`

Correct XGBoostJob CRD group name and add singular name

---

kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

Resolves https://github.com/kubeflow/kubeflow/issues/5057
Upgrade istio in aws cognito kfdef from 1.1.x to 1.3.1
**Checklist:**
3. `make test`

Upgrade aws cognito manifest istio version to 1.3.1

---

mxnet-job/mxnet-operator/base/crd.yaml
mxnet-job/mxnet-operator/base/deployment.yaml
mxnet-job/mxnet-operator/base/kustomization.yaml
mxnet-job/mxnet-operator/overlays/application/application.yaml

Upgrade MXNet operator manifest to v1.
Upgrade MXNet operator manifest to v1.
**Checklist:**
3. `make test`

Update mxnet-operator manifest to v1

---

kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

Resolves part of  https://github.com/kubeflow/kubeflow/issues/5057
Add mxnet-operator to aws kfdefs
**Checklist:**
3. `make test`

Add mxnet-operator to aws kfdefs

---

kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

Resolves https://github.com/kubeflow/kubeflow/issues/5057
Enable IRSA by default for AWS users
**Checklist:**
3. `make test`

Enable IRSA by default for AWS users

---

gcp/v2/cnrm/iam/kf-admin-policy.yaml
gcp/v2/cnrm/iam/kf-user-policy.yaml
stacks/gcp/kustomization.yaml
stacks/gcp/workload-identity-bindings-patch.yaml
tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
tests/stacks/examples/alice/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml
tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-ui.yaml
tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_ml-pipeline-visualizationserver.yaml
tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_pipeline-runner.yaml
tests/stacks/gcp/test_data/expected/~g_v1_serviceaccount_profiles-controller-service-account.yaml

Related to https://github.com/kubeflow/gcp-blueprints/issues/61
Add default workload identity bindings for GSAs.
**Checklist:**
3. `make test`

fix(gcp): default workload identity bindings

---

kfserving/OWNERS
knative/OWNERS

KFServing and KNative manifests Owners files

---

katib/katib-controller/base/katib-controller-rbac.yaml
tests/katib/installs/katib-external-db/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/katib/installs/katib-standalone/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_katib-controller.yaml

Resolves #1323 
This is necessary for being able to run Katib on OpenShift
Adding resource/finalizers to the Role
**Checklist:**
3. `make test`

Add missing finalizers for Katib experiment

---

knative/knative-serving-install/base/deployment.yaml
tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_activator.yaml
tests/tests/legacy_kustomizations/knative-install/test_data/expected/apps_v1_deployment_autoscaler.yaml

Resolves https://github.com/kubeflow/manifests/issues/1339
**Checklist:**
3. `make test`

Disable sidecar for activator and autoscaler

---

common/centraldashboard/base/deployment_patch.yaml
common/centraldashboard/base/kustomization.yaml
common/centraldashboard/base/params.env
tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/~g_v1_configmap_parameters.yaml

Resolves # https://github.com/kubeflow/kubeflow/issues/4889
This addresses the support needed to disable the registration flow on issue 4889. 
I modified the deployment patch, base kustomization and params.env for /common/centraldashboard to add another environment variable called REGISTRATION_FLOW which by default is set to "true". If the user wants to disable the registration flow they have to modify the definitions for the central-dashboard, add the registration-flow variable and set it to "false".
```
- kustomizeConfig:
overlays:
- istio
- application
parameters:
- name: userid-header
value: kubeflow-userid
- name: registration-flow
value: "false"
repoRef:
name: manifests
path: common/centraldashboard …
```

added support for registration flow env variable

---

aws/aws-istio-authz-adaptor/base/kustomization.yaml

Cherry pick of #1353 on v1.1-branch.
#1353: Upgrade istio auth adapter version

Automated cherry pick of #1353: Upgrade istio auth adapter version

---

kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

1.3.1 doesn't enable template CRD which means auth adapter will meet some issues. 
We will fix this after 1.1 release
[AWS] Revert istio version in cognito manifest back to 1.1.x
**Checklist:**
3. `make test`

[AWS] Revert istio version in cognito manifest back to 1.1.x

---

kfdef/kfctl_aws_cognito.yaml
kfdef/source/master/kfctl_aws_cognito.yaml

Cherry pick of #1360 on v1.1-branch.
#1360: Revert istio version in cognito manifest back to 1.1.x

Automated cherry pick of #1360: Revert istio version in cognito manifest back to 1.1.x

---

gcp/v2/cnrm/cluster/cluster.yaml

* Stable is still on 1.14 which is getting to be quite old.
Tekton for example requires 1.15 at least.
Related to: kubeflow/gcp-blueprints#67

Switch GCP to regular channel which is on GKE 1.16

---

pipeline/installs/multi-user/api-service/deployment-patch.yaml
pipeline/installs/multi-user/pipelines-ui/deployment-patch.yaml

Part of https://github.com/kubeflow/manifests/issues/1364
This let KFP servers read from common configuration for userid prefix and userid header.

Use kubeflow userid header and prefix config for KFP servers

---

pipeline/installs/multi-user/pipelines-profile-controller/deployment.yaml
pipeline/installs/multi-user/pipelines-profile-controller/sync.py

pipelines profile controller should get minio access keys from the secret.
This resolves the concern raised in https://github.com/kubeflow/manifests/pull/1342#discussion_r450852695.
Now users can customize the access key and secret in one place and the entire system should still work.
**Checklist:**
3. `make test`

refactor: pipelines profile controller should get minio access keys from the secret

---

namespaces/base/namespaces.yaml

Related: https://github.com/kubeflow/manifests/issues/1380.
I deleted `katib-metricscollector-injection: enabled` label from Kubeflow namespace. 
I believe in kfctl this label was added in this PR: https://github.com/kubeflow/kfctl/pull/72.
Let me know if we need to update kfctl also.
/cc @gaocegege @johnugeorge 
**Checklist:**
3. `make test`

Remove katib-metricscollector-injection label from Kubeflow namespace

---

namespaces/base/namespaces.yaml

Related: https://github.com/kubeflow/manifests/pull/1387#issuecomment-658466481.
**Checklist:**
3. `make test`

Automated cherry-pick of #1387: Remove katib-metricscollector-injection label from Kubeflow namespace on v1.1-branch

---

seldon/seldon-core-operator/base/resources.yaml
tests/stacks/ibm/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
tests/tests/legacy_kustomizations/seldon-core-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml
tests/validate_resources_test.go

Resolves #1386 
* Revert exception in manifest test to again enforce status for all resources
* Remove `status` section from Seldon CRD.
**Checklist:**
3. `make test`

Revert CRD status exception and remove status from Seldon CRD

---

common/centraldashboard/base/deployment_patch.yaml
common/centraldashboard/base/links-configmap.yaml
common/centraldashboard/base/role.yaml
tests/stacks/examples/alice/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
tests/stacks/gcp/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
tests/stacks/generic/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
tests/stacks/ibm/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/tests/legacy_kustomizations/centraldashboard/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml

Related to https://github.com/kubeflow/kubeflow/pull/5147 (To be merged after central dashboard PR merges)
**Checklist:**
3. `make test`

Moving central dashboard links to configmap

---

OWNERS
tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml

Hi all, I have continuously contributed to kubeflow/manifests repo and excited to continue working on it.
Thus, I want to add myself into reviewer list to help manifests grow fast.
The list of my PR on manifests:
https://github.com/kubeflow/manifests/pull/1410
https://github.com/kubeflow/manifests/pull/1330
https://github.com/kubeflow/manifests/pull/1155
https://github.com/kubeflow/manifests/pull/982
https://github.com/kubeflow/manifests/pull/953
https://github.com/kubeflow/manifests/pull/952
**Checklist:**
3. `make test`

Add PatrickXYS into reviewer list

---

kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
stacks/aws/kustomization.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-envoy-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-grpc-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-ui.yaml
tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-grpc.yaml
tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-ui.yaml
tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_role_metadata-ui.yaml
tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_rolebinding_metadata-ui.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-db-parameters.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-grpc-configmap.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-ui-parameters.yaml
tests/stacks/aws/test_data/expected/~g_v1_persistentvolumeclaim_metadata-mysql.yaml
tests/stacks/aws/test_data/expected/~g_v1_secret_metadata-db-secrets.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-db.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-envoy-service.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-grpc-service.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-service.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-ui.yaml
tests/stacks/aws/test_data/expected/~g_v1_serviceaccount_metadata-ui.yaml

Resolves #1427
Bring back components whose namespace is kubeflow into `stacks/aws/kustomization.yaml`.
So for now, we're able to see `Artifact Store` page under KF dashboard.
**Checklist:**
3. `make test`

Bring back some istio virtual services back to kubeflow namespace

---

kfdef/kfctl_aws.yaml
kfdef/kfctl_aws_cognito.yaml
stacks/aws/kustomization.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-envoy-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-grpc-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-ui.yaml
tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-grpc.yaml
tests/stacks/aws/test_data/expected/networking.istio.io_v1alpha3_virtualservice_metadata-ui.yaml
tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_role_metadata-ui.yaml
tests/stacks/aws/test_data/expected/rbac.authorization.k8s.io_v1beta1_rolebinding_metadata-ui.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-db-parameters.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-grpc-configmap.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_metadata-ui-parameters.yaml
tests/stacks/aws/test_data/expected/~g_v1_persistentvolumeclaim_metadata-mysql.yaml
tests/stacks/aws/test_data/expected/~g_v1_secret_metadata-db-secrets.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-db.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-envoy-service.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-grpc-service.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-service.yaml
tests/stacks/aws/test_data/expected/~g_v1_service_metadata-ui.yaml
tests/stacks/aws/test_data/expected/~g_v1_serviceaccount_metadata-ui.yaml

Cherry-pick AWS change https://github.com/kubeflow/manifests/pull/1429 into v1.1-branch. 
**Checklist:**
3. `make test`

Cherry-pick #1429 into v1.1-branch

---

kfdef/kfctl_aws.v1.1.0.yaml
kfdef/kfctl_aws_cognito.v1.1.0.yaml

Resolves https://github.com/kubeflow/kubeflow/issues/5022
Release AWS v1.1.0 Kfdef manifests.
We didn't use v1.1.0 tag in this kfdef manifest, the major reason is some of our manifest v3 changes and multi-user pipeline changes are not included in v1.1.0. We still like to ship these features and that's the reason we use v1.1-branch. This will be reflected on the docs in kuebflow/website as well. 
After community plans to cut a 
**Checklist:**
3. `make test`

Create v1.1.0 AWS Kfdef manifests

---

aws/aws-istio-authz-adaptor/base/params.env

Correct AWS authz adaptor header.  Change from `x-amzn-oidc-header` to `x-amzn-oidc-data`. `x-amzn-oidc-header` is incorrect. We used overrides in the past, however, this was not taken care of during manifest v3 upgrade and brings some regression issue. 
https://github.com/kubeflow/manifests/search?q=x-amzn-oidc-data&unscoped_q=x-amzn-oidc-data
Issues:
```
ERROR User None is not authorized to list kubeflow.org.v1beta1.notebooks for namespace: admin
```
**Checklist:**
3. `make test`

Correct AWS authz adaptor header

---

aws/aws-istio-authz-adaptor/base/params.env

Cherry pick of #1435 on v1.1-branch.
#1435: Correct AWS authz adaptor header

Automated cherry pick of #1435: Correct AWS authz adaptor header

---

stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-57ddmh4ht8.yaml

Cherry pick of #1442 on v1.1-branch.
#1442: Upgrade AWS jupyter images to 1.1.0

Automated cherry pick of #1442: Upgrade AWS jupyter images to 1.1.0

---

stacks/ibm/application/profiles/base/deployment_patch.yaml
tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml

Need `userid-header` param to use proper header when handling
the API calls. Default header value: `x-goog-authenticated-user-email`
would be used if this param doesn't present. It may only work on GCP.
Therefore, we do need this param to be properly passed to kfam.
Resolves #
**Checklist:**
3. `make test`

Pass userid-header param to kfam

---

kfdef/kfctl_ibm.v1.1.0.yaml
kfdef/kfctl_ibm_dex_multi_user.v1.1.0.yaml

The multi-user kfdef configuration has been cherry-picked into `v1.1-branch` but not `v1.1.0` release. For now, instead of using the repo archive from `v1.1.0`, switch to use `v1.1-branch`.
**Checklist:**
- [ x ] Unit tests have been rebuilt: 
3. `make test`

[IBM] update manifests repo link

---

gcp/kustomize-fns/remove_namespace.yaml
gcp/v2/cnrm/gcp-services.yaml

* This is needed to produce YAMLs that are compatible with ACM related to
* kubeflow/gcp-blueprints#27 kustomize function to remove namespace
* kubeflow/gcp-blueprints#4 instructions for ACM

Add a kustomize function to remove namespace

---

tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-controller.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-db-manager.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-ui.yaml
tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_katib-config.yaml

After https://github.com/kubeflow/manifests/pull/1440 was merged, some unit test was not generated and post-submit fails: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_manifests/kubeflow-manifests-postsubmit/1290236501023526912/.
We had to re-generate tests after https://github.com/kubeflow/manifests/pull/1428 was merged.
This PR should fix unit-test.
/cc @johnugeorge @jlewi @adrian555 
**Checklist:**
3. `make test`

Update unit test for the latest changes

---

namespaces/base/namespaces.yaml

* cert-manager namespace needs the control-plane label to prevent
application of kfserving webhooks.
related to: #1450

cert-manager namespace needs label control-plane

---

gcp/kustomize-fns/virtual_service_config.yaml

* Related to kubeflow/manifests#1169 we should be using the gateway
in the istio-system namespace and not the gateway in the kubeflow
namespace
* kubeflow/gcl-blueprints#22 With ACM we want to use
istio-system/ingressgateway and stop using the kubeflow-gateway.
Resolves #
**Checklist:**
3. `make test`

Create a kustomize function to change the gateway of virtual services.

---

xgboost-job/xgboost-operator/base/cluster-role.yaml
xgboost-job/xgboost-operator/base/crd.yaml
xgboost-job/xgboost-operator/base/kustomization.yaml
xgboost-job/xgboost-operator/overlays/application/application.yaml

Resolves #https://github.com/kubeflow/xgboost-operator/issues/99
xgboost-operator now point user to use manifest in kubeflow/manifest to install operator. There's issue like code changes in xgboost-operator auto trigger images building here.  Sometimes, we might not want to update image tags for those dev changes. 
I add `xgboostjob` back from https://github.com/kubeflow/manifests/pull/1313/files. master xgboost-operator code changes has been changed to v1. However, the examples have not been updated yet. That's the reason I change to previous stable manifest with v1alpha1. 
Once we fully migrate to v1, we can update manifest here. 
/cc @terrytangyuan 
**Checklist:**
2. `make …

Fix XGBoost Operator manifest issue

---

OWNERS

Resolves #
Based on the discussion, https://github.com/kubeflow/manifests/pull/1443#issuecomment-668617654
we plan to clean up some inactive approvers. I check last 6 months histories and seems there're no issues or PR created by following contributors. You may still help on issue triage and PR review & approve. However, I don't have a way to check all activities in this repo. If you still working on this repo, let us know and I will remove from the list.  Keep PR for a week to make sure users are notified. 
/hold
/cc @jlewi 
@abhi-g @ashahba @gabrielwen @hougangliu @IronPan @kkasravi @lluunn 
**Checklist:**
3. `make test`

Clean up inactive approvers

---

istio/oidc-authservice/base/envoy-filter.yaml
istio/oidc-authservice/base/kustomization.yaml
istio/oidc-authservice/base/params.env
istio/oidc-authservice/base/params.yaml
tests/stacks/aws/application/oidc-authservice/test_data/expected/~g_v1_configmap_oidc-authservice-parameters.yaml
tests/stacks/ibm/application/oidc-authservice/test_data/expected/~g_v1_configmap_oidc-authservice-parameters.yaml
tests/stacks/kubernetes/application/oidc-authservice/test_data/expected/~g_v1_configmap_oidc-authservice-parameters.yaml

this allows the use of non-default istio ingress gateways, by implementing a kustomize parameter
**Checklist:**
3. `make test`

add parameter for istio gateway in oidc-authservice

---

gcp/iap-ingress/base/ingress.yaml
tests/go.mod
tests/stacks/kubernetes/application/add-anonymous-user-filter/kustomize_test.go
tests/tests/legacy_kustomizations/iap-ingress/test_data/expected/networking.k8s.io_v1beta1_ingress_envoy-ingress.yaml

* Ref https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http force all traffic from client to ingress to be https.
* Fix kubeflow/gcp-blueprints#116
* Explicitly set the default backend to the ISTIO ingress gateway.

Remove http from the GCP ingress and explicitly set the default backend.

---

kfdef/kfctl_k8s_istio.v1.1.0.yaml
stacks/kubernetes/application/spark-operator/kustomization.yaml
stacks/kubernetes/application/spartakus/kustomization.yaml
tests/stacks/kubernetes/application/spark-operator/kustomize_test.go
tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/app.k8s.io_v1beta1_application_spark-operator.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_spark-operatoroperator-cr.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_spark-operatorsparkoperator-crb.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_role_spark-operatorspark-role.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_spark-operatorspark-role-binding.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatoroperator-sa.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatorspark.yaml
tests/stacks/kubernetes/application/spartakus/kustomize_test.go
tests/stacks/kubernetes/application/spartakus/test_data/expected/app.k8s.io_v1beta1_application_spartakus.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/apps_v1_deployment_spartakus-volunteer.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_spartakus.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrolebinding_spartakus.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_configmap_spartakus-config.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_serviceaccount_spartakus.yaml

Running through install instructions for using the `kfctl_k8s_istio.v1.1.0.yaml` KFDef file, I was running into issues with some manifests missing. This PR creates those missing files, following the current paradigm of having these exist in the `stacks/kubernetes/application` directory. Once I added these, Kubeflow deployed successfully.
Also removed Tensorboard from the KFDef. (see https://github.com/kubeflow/manifests/issues/415)
Can generate tests if these changes make sense.
**Checklist:**
3. `make test`

Add missing files for k8s_istio.v1.1.0 KFDef

---

kfdef/kfctl_k8s_istio.v1.1.0.yaml
stacks/kubernetes/application/spark-operator/kustomization.yaml
stacks/kubernetes/application/spartakus/kustomization.yaml
tests/stacks/kubernetes/application/spark-operator/kustomize_test.go
tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_scheduledsparkapplications.sparkoperator.k8s.io.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/apiextensions.k8s.io_v1beta1_customresourcedefinition_sparkapplications.sparkoperator.k8s.io.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/app.k8s.io_v1beta1_application_spark-operator.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/apps_v1_deployment_spark-operatorsparkoperator.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_spark-operatoroperator-cr.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_spark-operatorsparkoperator-crb.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_role_spark-operatorspark-role.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_spark-operatorspark-role-binding.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatoroperator-sa.yaml
tests/stacks/kubernetes/application/spark-operator/test_data/expected/~g_v1_serviceaccount_spark-operatorspark.yaml
tests/stacks/kubernetes/application/spartakus/kustomize_test.go
tests/stacks/kubernetes/application/spartakus/test_data/expected/app.k8s.io_v1beta1_application_spartakus.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/apps_v1_deployment_spartakus-volunteer.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrole_spartakus.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrolebinding_spartakus.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_configmap_spartakus-config.yaml
tests/stacks/kubernetes/application/spartakus/test_data/expected/~g_v1_serviceaccount_spartakus.yaml

* Add missing files for k8s_istio.v1.1.0 KFDef
* Also removed tensorboard from the KFDef
* Generate tests
Resolves https://github.com/kubeflow/kubeflow/issues/5246
**Checklist:**
3. `make test`

cherry-pick k8s_istio.v1.1.0 KFDef (#1515)

---

profiles/base_v3/deployment_patch.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_profiles-deployment.yaml

Resolves https://github.com/kubeflow/kubeflow/issues/5227
Add `USERID_HEADER` to access management, otherwise, istio `ServiceRoleBinding` will use wrong header.
This is a regression issue bring into v1.1-branch due from v3 manifest migration
**Checklist:**
3. `make test`

Add USERID_HEADER argument in access management

---

profiles/base_v3/deployment_patch.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_profiles-deployment.yaml

Cherry pick of #1559 on v1.1-branch.
#1559: Add USERID_HEADER argument in access management

Automated cherry pick of #1559: Add USERID_HEADER argument in access management

---

kfdef/kfctl_aws.v1.1.0.yaml
kfdef/kfctl_aws_cognito.v1.1.0.yaml

Resolves #
The time we release v1.1, we just put manifest in v1.1 branch but forget to put in master. Add it back in case some user misunderstand that AWS didn't release v1.10 
**Checklist:**
3. `make test`

Add AWS v1.1.0 manifest to master branch

---

tests/OWNERS
tests/stacks/ibm/components/tf-job/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_tf-job-operator.yaml

Resolves #
I've been continuously contributing to manifests repo and will be adding E2E test back which include manifests+kfctl.
Adding myself as tests folder approver.
Here is my contribution list:
https://github.com/kubeflow/manifests/pulls/PatrickXYS
**Checklist:**
3. `make test`

Add PatrickXYS as tests folder approver

---

tests/validate_resources_test.go

Related #1567
Since we are still using kyaml v0.1.11 for our tests, it has some bugs when parsing non SequenceNode yaml. Although it's resolved in the newer release of kyaml, updating kyaml will dramatically change the current generated tests. Therefore, we skip all the files with `wrong Node Kind for` since we only need to check the proper kubernetes yaml.
**Checklist:**
3. `make test`

[Fix tests] Skip non SequenceNode yaml to work around on the old kyaml bug

---

OWNERS

Resolves #
I want to add myself as the OWNER of manifests repo as a leader of wg-manifests.
And here is my[ contribution list ](https://github.com/kubeflow/manifests/pulls?q=is%3Apr+author%3APatrickXYS)
**Checklist:**
3. `make test`

Add PatrickXYS as OWNER of manifests repo

---

prow_config.yaml
tests/workflows/components/workflows.libsonnet

For Kubeflow 1.2 release, we have decided to move E2E test back for kfctl + manifests
Related kfctl PR: https://github.com/kubeflow/kfctl/pull/427
This PR will only be able to merge until kfctl PR merged.
1. Add E2E test
2. Change E2E configuration to make it compatible on Shared Test-infra
**Checklist:**
3. `make test`

Add E2E Test on Kubeflow Shared Test-infra

---

OWNERS

Add Arrikto folk to the OWNERS file, as part of forming the new WG
Manifests, in order to carry out the plan specified in the charter.
/cc @PatrickXYS @jlewi @Bobgy 

Update OWNERS file with Arrikto folk

---

aws/fluentd-cloud-watch/base_v3/kustomization.yaml
prow_config.yaml
tests/go.mod
tests/validate_resources_test.go

* Fix one remaining use in fluentd
* Fix #538

Add a test to verify no more use of deprecated env syntax

---

prow_config.yaml

Resolves #
Add AWS Periodic Tests to test orchestration on Kubeflow AWS.
Also removes periodic tests for e2e and unit tests, since no one will check it daily and see if they succeed or fail, thus, it only consume resources without any contribution.
**Checklist:**
3. `make test`

Add AWS Periodic Tests

---

tests/workflows/components/workflows.libsonnet

Resolves #
Increase unit test TTL from 1h to 8h
**Checklist:**
3. `make test`

Increase unit test argo workflow TTL

---

prow_config.yaml

Resolves #
Add Periodic tests back per discussion [here](https://github.com/kubeflow/manifests/pull/1612#issuecomment-722771015) 
**Checklist:**
3. `make test`

Add Periodic Tests back

---

kfdef/kfctl_aws.v1.2.0.yaml
kfdef/kfctl_aws_cognito.v1.2.0.yaml
kfdef/kfctl_ibm.v1.2.0.yaml
kfdef/kfctl_ibm_dex_multi_user.v1.2.0.yaml
kfdef/kfctl_istio_dex.v1.2.0.yaml
kfdef/kfctl_k8s_istio.v1.2.0.yaml
kfdef/kfctl_openshift.v1.2.0.yaml

Resolves #1597 
I copy from 1.1 manifests and only change manifest resource to v1.2-branch.  The reason I didn't pin to tag is because we are in RC phase and I assume they might be some bug fixed. Let's start to test it and once there's a stable RC, we can pin to tag later.
This change will be cherry-pick back to v1.2-branch after it merges. 
/cc @PatrickXYS @animeshsingh @adrian555 @nakfour
**Checklist:**
3. `make test`

Add kfdef 1.2 manifests

---

prow_config.yaml

for 1.2 release
Make prow periodical test against v1.2-branch
**Checklist:**
3. `make test`

Pin test manifest to v1.2-branch

---

katib/katib-controller/base/katib-mysql-deployment.yaml
metadata/overlays/db/metadata-db-deployment.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/ibm/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/ibm/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/openshift/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/openshift/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml

When trying to restart MySQL instances, they get stuck because the old container will refuse to give up the lock on the DB:
* `kubectl rollout restart deployment/katib-mysql  -n kubeflow`
* `kubectl rollout restart deployment/metadata-db  -n kubeflow`
This PR fixes that by setting the deployment strategy to `Recreate`.
**Checklist:**
3. `make test`

fix mysql deployment strategy

---

kfdef/kfctl_ibm.v1.2.0.yaml
kfdef/kfctl_ibm_multi_user.v1.2.0.yaml

Resolves #
The IBM 1.2 manifests are based on 1.1 which didn't include our latest changes such as App ID and Tekton. Therefore, pin the IBM 1.2 manifests with the latest kfdef.
**Checklist:**
3. `make test`

Pin IBM v1.2 manifests

---

kfdef/kfctl_aws.v1.2.0.yaml
kfdef/kfctl_aws_cognito.v1.2.0.yaml

Resolves #
Found we removed tensorboard manifests in master branch previously 
https://github.com/kubeflow/manifests/pull/1459
Remove tensorboard in AWS 1.2 manifests.
**Checklist:**
3. `make test`

Remove Tensorboard for AWS 1.2 Manifests

---

prow_config.yaml

Resolves #
Since cloud providers are changing kfdef/* manifests frequently, and we should only kick off E2E tests when `kfctl_istio_dex` manifests.
**Checklist:**
3. `make test`

Presubmit kicked off by istio_dex manifests

---

kfdef/kfctl_aws.v1.2.0.yaml
kfdef/kfctl_aws_cognito.v1.2.0.yaml
prow_config.yaml

Resolves #
Cherry-pick merged PRs from master to v1.2-branch
1. https://github.com/kubeflow/manifests/pull/1630
2. https://github.com/kubeflow/manifests/pull/1629
**Checklist:**
3. `make test`

Cherry-Pick AWS PR #1629 #1630

---

stacks/aws/application/jupyter-web-app/configs/spawner_ui_config.yaml
tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/aws/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8fc6g84c8k.yaml

Resolves #
Rollout AWS Jupyter images to 1.2.0 alongside with Kubeflow 1.2 release
**Checklist:**
3. `make test`

Rollout AWS Jupyter images to 1.2.0

---

katib/katib-controller/base/katib-mysql-deployment.yaml
metadata/overlays/db/metadata-db-deployment.yaml
tests/katib/installs/katib-standalone-ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/katib/installs/katib-standalone/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/azure/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/azure/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/ibm/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/ibm/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/stacks/openshift/application/katib/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/stacks/openshift/application/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml
tests/tests/legacy_kustomizations/katib-controller/test_data/expected/apps_v1_deployment_katib-mysql.yaml
tests/tests/legacy_kustomizations/metadata/test_data/expected/apps_v1_deployment_metadata-db.yaml

(cherry picked from commit 6c4f2653abd13e6f866ef78f2fbd63adb1c89a49)
See PR:#1562

fix mysql deployment strategy (#1562)

---

jupyter/jupyter-web-app/base/configs/spawner_ui_config.yaml
tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/azure/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/azure/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/gcp/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8kcgd8t8th.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/generic/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8kcgd8t8th.yaml
tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/ibm/application/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/ibm/application/notebooks/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/ibm/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/kubernetes/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config-8kcgd8t8th.yaml
tests/tests/legacy_kustomizations/jupyter-web-app/test_data/expected/~g_v1_configmap_jupyter-web-app-jupyter-web-app-config.yaml

Updates the default `spawner_ui_config.yaml` with new sections for the tolerations/selectors feature.
**Checklist:**
3. `make test`

update jupyter config with tolerations/selectors

---

prow_config.yaml

Resolves #
This is to enable AWS Kubeflow-Kubernetes periodic tests
**Checklist:**
3. `make test`

Enable AWS Kubeflow-Kubernetes Periodic Tests

---

prow_config.yaml

Resolves #
This PR is to enable AWS Kubeflow-Kubernetes Periodic Tests in v1.2-branch 
**Checklist:**
3. `make test`

Enable AWS Kubeflow-Kubernetes Periodic Tests in v1.2-branch

---

stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
stacks/ibm/application/notebook-controller/base/kustomization.yaml
stacks/ibm/application/profiles/base/kustomization.yaml
tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/notebook-controller/base/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/application/notebook-controller/test_data/expected/kubeflow_apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/application/profile-control-plane/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml

This PR updates the image tags that were listed in the IBM stack based on updates in https://github.com/kubeflow/manifests/pull/1645. 
Ideally, we get rid of the hard-coding here and use each component's `base_v3` directly, but I'm hesitant to do so based on https://github.com/kubeflow/manifests/issues/1285 . So for now, just update the relevant image tags in `stacks/ibm`.
**Checklist:**
3. `make test`

[IBM] Update notebooks and profiles image tags

---

stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
stacks/ibm/application/notebook-controller/base/kustomization.yaml
stacks/ibm/application/profiles/base/kustomization.yaml
tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/notebook-controller/base/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/application/notebook-controller/test_data/expected/kubeflow_apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/application/profile-control-plane/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/application/profiles/base/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/application/profiles/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_profiles-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_notebook-controller-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_profiles-deployment.yaml

This PR cherry-picks #1652 into v1.2-branch.
**Checklist:**
3. `make test`

Cherry-pick of '[IBM] Update notebooks and profiles image tags' (#1652) to v1.2-branch

---

flink/OWNERS
flink/flink-operator/README.md
flink/flink-operator/base/cluster-role-binding.yaml
flink/flink-operator/base/cluster-role.yaml
flink/flink-operator/base/configmap.yaml
flink/flink-operator/base/crd.yaml
flink/flink-operator/base/deployment.yaml
flink/flink-operator/base/kustomization.yaml
flink/flink-operator/base/leader-election-role-binding.yaml
flink/flink-operator/base/leader-election-role.yaml
flink/flink-operator/base/service-account.yaml
flink/flink-operator/base/service.yaml
flink/flink-operator/base/setup-job.yaml
flink/flink-operator/base/webhook.yaml
flink/flink-operator/overlay/application/application.yaml
flink/flink-operator/overlay/application/kustomization.yaml

Resolves https://github.com/kubeflow/manifests/issues/1468
part of https://github.com/kubeflow/kubeflow/issues/1583
Bring [GoogleCloudPlatform/flink-on-k8s-operator](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator) to Kubeflow manifest. 
**Checklist:**
3. `make test`

Add Flink Operator to Kubeflow manifests

---

common/centraldashboard/base/links-configmap.yaml
common/centraldashboard/base_v3/deployment_patch.yaml
common/centraldashboard/base_v3/kustomization.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/aws/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/azure/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/azure/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/examples/alice/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/gcp/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/generic/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/ibm/application/profile-control-plane/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/ibm/application/profile-control-plane/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/ibm/multi-user/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/ibm/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/kubernetes/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/openshift/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/openshift/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml

Resolves #
For safety reason, I only patch configmap env, this should be good enough to customize links in central dashbaord. We need to bring this back to 1.2.. 
**Checklist:**
3. `make test`

Enable central dashboard to use configmap and remove manifest link

---

stacks/azure/application/jupyter-web-app/base/kustomization.yaml
tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml

Resolves #1645
Updates hardcoded image tag for Jupyter Web App in Azure Stack
**Checklist:**
3. `make test`

Update jupyter web app image tag for Azure Stack

---

stacks/azure/application/centraldashboard/deployment_patch.yaml
stacks/azure/application/centraldashboard/kustomization.yaml
stacks/azure/application/centraldashboard/links-configmap.yaml
stacks/azure/application/jupyter-web-app/base/kustomization.yaml
stacks/azure/kustomization.yaml
tests/stacks/azure/application/centraldashboard/kustomize_test.go
tests/stacks/azure/application/centraldashboard/test_data/expected/app.k8s.io_v1beta1_application_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/apps_v1_deployment_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/networking.istio.io_v1alpha3_virtualservice_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/rbac.authorization.k8s.io_v1_clusterrole_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/rbac.authorization.k8s.io_v1_clusterrolebinding_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/rbac.authorization.k8s.io_v1_role_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/rbac.authorization.k8s.io_v1_rolebinding_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_service_centraldashboard.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_serviceaccount_centraldashboard.yaml
tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml

Resolves #1597 for Azure
Cherry-picking changes for central dashboard customization for the Azure stack
Cherry-picking change to update hardcoded image tags
**Checklist:**
3. `make test`

Cherry-picking several Azure changes for v1.2 release

---

kfdef/kfctl_aws.v1.2.0.yaml
kfdef/kfctl_aws_cognito.v1.2.0.yaml
kfdef/kfctl_azure.v1.2.0.yaml
kfdef/kfctl_azure_aad.v1.2.0.yaml
kfdef/kfctl_ibm.v1.2.0.yaml
kfdef/kfctl_ibm_multi_user.v1.2.0.yaml
kfdef/kfctl_istio_dex.v1.2.0.yaml
kfdef/kfctl_k8s_istio.v1.2.0.yaml
kfdef/kfctl_openshift.v1.2.0.yaml

Resolves #
Pin manifests to official release tag. Following cherry-pick won't affect stable deployment
**Checklist:**
3. `make test`

Pin manifest to stable tag v1.2.0

---

stacks/azure/application/centraldashboard/links-configmap.yaml
stacks/azure/kustomization.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_argo-ui.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_centraldashboard.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_jupyter-web-app.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_ml-pipeline-ui.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_profiles-kfam.yaml
tests/stacks/azure/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/azure/test_data/expected/~g_v1_service_centraldashboard.yaml
tests/stacks/azure/test_data/expected/~g_v1_service_jupyter-web-app-service.yaml

Fixes Azure stack v1.2 deployment issue due to missing kustomize variables
- Fixes Azure stack v1.2 deployment issue due to missing kustomize variables
- Also fixes JSON for Dashboard link overrides (removes trailing comma)
**Checklist:**
3. `make test`

Fix v1.2 Azure stack config

---

stacks/azure/application/centraldashboard/links-configmap.yaml
stacks/azure/kustomization.yaml
tests/stacks/azure/application/centraldashboard/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_argo-ui.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_centraldashboard.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_jupyter-web-app.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_katib-ui.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_ml-pipeline-ui.yaml
tests/stacks/azure/test_data/expected/networking.istio.io_v1alpha3_virtualservice_profiles-kfam.yaml
tests/stacks/azure/test_data/expected/~g_v1_configmap_centraldashboard-links-config.yaml
tests/stacks/azure/test_data/expected/~g_v1_service_centraldashboard.yaml
tests/stacks/azure/test_data/expected/~g_v1_service_jupyter-web-app-service.yaml

Cherry picking commit from #1678 to fix Azure Stack config for v1.2
**Checklist:**
- [X ] Unit tests have been rebuilt: 
3. `make test`

Fix Azure stack config for v1.2

---

kfdef/kfctl_azure.v1.2.0.yaml
kfdef/kfctl_azure_aad.v1.2.0.yaml

Pins Azure kfdef to particular commit which includes Azure Stack config fix
**Checklist:**
3. `make test`

Pin Azure v1.2 kfdef to include fix

---

stacks/openshift/application/jupyter-web-app/kustomization.yaml
tests/stacks/openshift/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml

Reference #1553
See https://github.com/kubeflow/manifests/pull/1645#issuecomment-728706141
Update the `jupyter-web-app` image to `v2.0.0` in the openshift stack
**Checklist:**
3. `make test`

OpenShift jupyter-web-app update imagetag to v2.0.0

---

jupyter/jupyter-web-app/base/kustomization.yaml
jupyter/jupyter-web-app/base_v3/kustomization.yaml
stacks/azure/application/jupyter-web-app/base/kustomization.yaml
stacks/ibm/application/jupyter-web-app/base/kustomization.yaml
tests/stacks/aws/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/aws/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/azure/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/examples/alice/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/gcp/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/generic/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/jupyter-web-app/base/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/application/notebooks/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/multi-user/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/ibm/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/stacks/kubernetes/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml
tests/tests/legacy_kustomizations/jupyter-web-app/test_data/expected/apps_v1_deployment_jupyter-web-app-deployment.yaml

This fixes the version of the `jupyter-web-app` image to the version which is correct for Kubeflow 1.2.
Without this, the features from https://github.com/kubeflow/kubeflow/pull/5237 are NOT present.
**Checklist:**
3. `make test`

fix jupyter-web-app image tag

---

kfdef/kfctl_aws_cognito.v1.2.0.yaml

Resolves #https://github.com/kubeflow/kfserving/issues/1234
Istio 1.1.6 is not compatible with KFServing 0.4.1
**Checklist:**
3. `make test`

Bump istio version to 1.3.1

---

pipeline/installs/tekton/kfp-tekton/kfp-pipeline-config.yaml
tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml
tests/stacks/ibm/application/kfp-tekton/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml

Resolves #
minio/mc updated the release image few hours ago that's based on the RedHat UBI image. However, the new image now doesn't include the `tar` binary for Tekton to package the kfp artifacts into tar.gz. Thus, we make minio/mc to use the stable release that we have tested.
We need to cherry pick this into the v1.2 branch to stop users from pulling the latest minio/mc image.
**Checklist:**
3. `make test`

Update Tekton to use the fixed version of minio/mc image

---

pipeline/installs/tekton/kfp-tekton/kfp-pipeline-config.yaml
tests/stacks/ibm/application/kfp-tekton-multi-user/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml
tests/stacks/ibm/application/kfp-tekton/test_data/expected/~g_v1_configmap_kfp-tekton-config.yaml

Resolves #
**Checklist:**
3. `make test`

Automated cherry pick of #1693 [Update Tekton to use the fixed version of minio/mc image] to v1.2 branch

---

kfdef/kfctl_ibm.v1.2.0.yaml
kfdef/kfctl_ibm_multi_user.v1.2.0.yaml

Resolves #
From Kubeflow 1.2, by default the stable release no longer take changes from cherry-pick. So we need to pin the cherry pick commit to our stable release kfdef.
**Checklist:**
3. `make test`

 Pin IBM 1.2 kfdef to include cherry-pick fixes

---

README.md

Resolves part of #1708
Add README documentation about current tests in kubeflow/manifests repo.
**Checklist:**
3. `make test`

Add Test README support

---

pipeline/persistent-agent/base/clusterrole-binding.yaml
tests/tests/legacy_kustomizations/persistent-agent/test_data/expected/rbac.authorization.k8s.io_v1beta1_clusterrolebinding_ml-pipeline-persistenceagent.yaml

Resolves #1711 
Change clusterrole given to `ml-pipeline-persistenceagent` serviceaccount
**Checklist:**
3. `make test`

Change cluster-admin role to `ml-pipeline-persistenceagent` for the pipeline/persistent-agent sa

---

prow_config.yaml

Part of https://github.com/kubeflow/testing/issues/861
Resolves #1725 
Migrate kubeflow/manifests to new test-infra, there's no difference between old test-infra and new test-infra from users' perspective.
Note: this PR is only used to validate if migration works or not. 
**Checklist:**
3. `make test`
/hold

Migrate manifests repo

---

distributions/kfdef/kfctl_k8s_istio.yaml

Resolves #1757 
As discussed with @PatrickXYS  in the issue #1757  i just remove spartakus for plain kubernetes, as it was done for the dex version before.
**Checklist:**
2. `make test`

remove spartakus from kfctl_k8s_istio.yaml

---

OWNERS

Similar to what all the other WGs have done in their respective repos, I am updating the OWNERS file of the `manifests` repo to include only the people in the Manifests Working Group, as described and agreed upon in the charter:
https://github.com/kubeflow/community/blob/8b830413cc3511404af63b32a37bc741bdfa23df/wgs.yaml#L201-L234
cc @kubeflow/wg-manifests-leads
Just a courtesy cc for people being removed:
@animeshsingh @Bobgy @jlewi @swiftdiaries @terrytangyuan @pvaneck

OWNERS: Update top-level owners to match wg-manifests charter

---

common/cert-manager/cert-manager/kubeflow-issuer/kustomization.yaml
common/cert-manager/cert-manager/overlays/application/kustomization.yaml
common/cert-manager/cert-manager/overlays/letsencrypt/kustomization.yaml
common/cert-manager/cert-manager/overlays/self-signed/kustomization.yaml
common/cert-manager/cert-manager/v3/kustomization.yaml

Remove v3 manifests from cert-manager, since we use plain kustomize now.

cert-manager: Remove v3 manifests

---

contrib/feast/Makefile
contrib/feast/feast/base/resources.yaml

Signed-off-by: ted chang <htchang@us.ibm.com>
Resolves #1773
**Checklist:**
2. `make test`

fix namespace conflict deploying feast to kubeflow

---

gcp/v2/cnrm/cluster/cluster.yaml

Fix issue https://github.com/kubeflow/gcp-blueprints/issues/198.
Needs to be cherry-picked for 1.2.1 release to fix the current issue on Kubeflow 1.2. Kubeflow 1.2 was designed for Kubernetes 1.16 version, so we should enforce this Kubernetes version, because the latest Kubernetes version has deprecated support for many old versions of Kubeflow's dependencies, and caused the Kubeflow deployment error-prone.
Validation:
I am able to apply this change and successfully deploy Kubeflow.
Note:
Make sure to do the following:
`If using IAP: make sure you added https://<deployment>.endpoints.<project>.cloud.goog/_gcp_gatekeeper/authenticate as an authorized redirect URI for the OAUTH credentials used to create the deployment.`
See troubleshooting: …

fix(GCP): Set fixed Kubernetes version to be 1.16 for successful Kubeflow 1.2 deployment. Fixes kubeflow/gcp-blueprints#198

---

README.md

The kustomize target is not correct.
Resolves #
**Checklist:**
2. `make test`

fix(doc): PyTorch Operator instruction in README

---

common/oidc-authservice/base/kustomization.yaml

Fix a small issue in the oidc-authservice manifests where `env: secret_params.env` is used instead of 
```yaml
envs:
- secret_params.env
```

oidc-authservice: fix secret generator envs

---

common/knative/knative-eventing-install/base/cluster-role.yaml
common/knative/knative-eventing-install/base/deployment.yaml

While testing with the latest version of kustomize the build for `common/knative/knative-eventing-install/base` fails due to the usage of `&ref_0` and `*ref_0` in the `matchLabels` and `labels` sections respectively. While investigating I compared the `deployment.yaml` of knative-eventing to that of knative-serving and noticed in the knative-serving manifests that the labels were explicitly stated. In the spirit of consistency and making the manifests usable with the latest version of kustomize this PR edits the `deployment.yaml` of knative-eventing to use the same syntax as that of knative-serving. 
/cc @yanniszark @PatrickXYS

Fix using newer kustomize for knative-eventing-install

---

contrib/feast/feast/base/resources.yaml
contrib/feast/values.yaml

Signed-off-by: ted chang <htchang@us.ibm.com>
Regenerate feast core resource manifest with the intended naming convention.
While running minimal_ride_hailing.ipynb in the  optionally enabled Jupyter notebook, the preset env variable, FEAST_CORE_URL': 'kf-feast-feast-core:6565' could not reference to the actual feast core service name, `kf-feast-core`. This caused client.apply(....) to return `ConnectionError: Connection timed out while attempting to connect to kf-feast-feast-core:6565`
/cc @woop

fix feast-core names in the generated resource.yaml

---

common/dex/overlays/github/kustomization.yaml
common/dex/overlays/istio/kustomization.yaml
common/dex/overlays/ldap/kustomization.yaml

Fixes the manifests not building with some versions of kustomize. Changes were tested with kustomize v3.2.1 and still build successfully. 
/cc @yanniszark @PatrickXYS

Dex-overlays use reference instead of base

---

common/dex/base/config-map.yaml
common/user-namespace/base/params.env

To be able to add contributors to your namespace the `name` value in the profile CR must be a valid email address. Currently, the default is set to `user` instead of `user@kubeflow.org`, which will break adding it as a contributor to other namespaces. This PR fixes the dex config so the `email` value is a "valid" email address and the associated Profile CR contains this email address. 
/cc @yanniszark 
Also /cc @berndverst as I think you might run into this as well as you are going through the deployment manifests now.
**Checklist:**
2. `make test`

Dex: Fix user must be valid email address

---

common/knative/knative-serving-install/base/deployment.yaml

Missed this reference somehow in the last PR 🤦 (https://github.com/kubeflow/manifests/pull/1827)
cc @kubeflow/wg-manifests-leads 
cc @DavidSpek

knative: Remove use of last yaml ref

---

README.md

Only Knative Serving is required for KFServing to work. Knative Eventing is used for specific logger/metrics tracking use cases.

Make note of knative-eventing being optional in README 

---

README.md

Resolves #1812
The current section for connecting to a Kubeflow cluster only covers
connecting with port-forward. Expand the section with instructions for
NodePort / LoadBalancer / Ingress.

README: Expand section for connecting to a Kubeflow cluster

---

README.md
docs/KustomizeBestPractices.md
hack/generate_tests.py
tests/test_util.go

Related to: https://github.com/kubeflow/manifests/issues/1797
This PR removes the `load_restrictor` flag from the README and the testing scripts as this flag should not be needed since https://github.com/kubeflow/manifests/pull/1840 has been merged. This allows Kustomize v3 and v4 to be used by users. This PR also fixes a few style inconsistencies in the README.
/cc @yanniszark I'm unsure if the approach for the Python and Go is correct. Also, the `load_restrictor` flag is still used in 2 places in the pipelines manifests which should be fixed upstream.
**Checklist:**
2. `make test`

Remove load_restrictor kustomize flag and lint README markdown

---

README.md

Resolves https://github.com/kubeflow/pipelines/issues/5452
Resolves https://github.com/kubeflow/pipelines/issues/5462
**Checklist:**
2. `make test`

docs(kfp): introduce multi-user KFP dependencies and KFP standalone as alternative

---

README.md

Some updates to the README to account for the change of the default user login from `user` to `user@example.com`.
/cc @yanniszark

Update user references in README to use email

---

contrib/feast/Makefile
contrib/feast/README.md
contrib/feast/feast/base/resources.yaml
contrib/feast/feast/base/static.yaml
contrib/feast/feast/overlays/kubeflow/kustomization.yaml
contrib/feast/feast/overlays/kubeflow/patches/kafka.yaml
contrib/feast/feast/overlays/kubeflow/patches/namespace.yaml
contrib/feast/feast/overlays/kubeflow/patches/redis.yaml
contrib/feast/feast/overlays/kubeflow/patches/zookeeper.yaml
contrib/feast/values.yaml

In order to make the Feast Kustomize manifests installable as both standalone and as a part of Kubeflow, the base install will continue to use the `feast` namespace and the `kubeflow` overlay can be used for those looking to use Feast with Kubeflow. The kubeflow overlay will change namespace references to `kubeflow` instead of `feast`. This allows for a bit more flexibility for those using the manifests.
- In values.yaml, `feast-jobservice` was enabled to reflect what is currently in `feast/base/resources.yaml`.
/cc @tedhtchang @woop

Add Kubeflow overlay to Feast

---

gcp/v2/cnrm/cluster/cluster.yaml

1.16 is no longer available. 1.17 seems to be the maximum version where kubeflow works in GCP.
Resolves #1887
bump gke node and master versions to 1.17 from 1.16
**Checklist:**
2. `make test`

bump gke node and master versions to 1.17 from 1.16 (#1887)

---

OWNERS

Follow up from https://github.com/kubeflow/community/pull/515. 
I'm replacing @vkoukis with myself, in the OWNERS file, to finalize the transition.

Add kimwnasptd to the owners file

---

docs/release/retrospectives/release-1.3.md

The original document is:
https://docs.google.com/document/d/1KRF4IE48Ueb61DPBKK6fryRWSaNz_urXQOxWf4G_qD8
Resolves https://github.com/kubeflow/manifests/issues/1899

docs: Add 1.3 release retrospective

---

docs/release/handbook.md

This is a first iteration in order to convert and commit the Release Handbook from a Google Doc to markdown https://docs.google.com/document/d/1mDk0lFc_4LHd71N-RZ2AjjZVF_rMou9GJrSaSaWyk5Y/edit. I also added some extra info based on some proposed comments, like further defining the roles in the release team.
Since the release team has been formed and we need to move on with providing the exact time schedule I'd like to put a maximum time cap for the review process of this PR. I think one week is a good limit. 
Of course we will continue to iterate on this doc with further PRs, but I want to at least have the first iteration merged quickly so that we can start the release process based on the committed doc.
cc @RFMVasconcelos @DavidSpek @kubeflow/wg-automl-leads …

First iteration of the Release Hanbook

---

distributions/kfdef/kfctl_openshift_v1.3.0.yaml

#1933
Changing uri to point to a tag and not a branch. Also fixing the istio folder to the right name in the 1.3.0 tag
**Checklist:**
2. `make test`

Openshift distribution: Fixing the uri to point to a tag 1.3.0 and not a branch 1.3.0

---

docs/release/OWNERS

Adding the release team as owners to the `docs/release` directory.
cc @kubeflow/wg-manifests-leads 
/cc @RFMVasconcelos @DavidSpek @mkbhanda
/assign @kimwnasptd

Add the release team as owners in the relevant dir

---

common/dex/base/deployment.yaml

Add KUBERNETES_POD_NAMESPACE environment variable for namespace discovery.
This fixes issue #1882 
This workaround has been mentioned [here](https://github.com/dexidp/dex/issues/2082#issuecomment-818124478) in the upstream dex project.
Tested on microk8s 1.21.
Resolves #
**Checklist:**
2. `make test`

Fix dex for Kubernetes 1.21

---

apps/admission-webhook/upstream/base/crd.yaml
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/configmap.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/README.md
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/base/namespace-labels.yaml
apps/profiles/upstream/base/patches/manager.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/default/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml

Closes #1972 
This PR uses the manifests from the https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0 tag
/cc @kubeflow/wg-notebooks-leads

Sync manifests for Notebooks WG v1.4-rc.0

---

README.md

Makes sure the versions in the README are up to date. In the future we should enforce that whenever a PR updates the version of a component it will also need to update the README. Thanks to @andreyvelich for also bringing it up https://github.com/kubeflow/manifests/pull/1988#pullrequestreview-736331707.
cc @pvaneck @Bobgy @kubeflow/wg-notebooks-leads [since this PR touches these components]
/cc @elikatsis

Update the versions of components in README

---

docs/releases/release-1.4/README.md

Right now we only give two weeks for distribution testing, but we should include 3 https://github.com/kubeflow/manifests/blob/master/docs/releases/handbook.md#timeline.
The manifests testing should happen 2 weeks after the feature freeze phase has started and in parallel with the docs effort. 
I missed this in the review of the initial PR https://github.com/kubeflow/manifests/pull/1974
/cc @annajung @kubeflow/release-team

Allocate 3 weeks for distribution testing

---

README.md
apps/mpi-job/upstream/base/deployment.yaml
apps/mpi-job/upstream/overlays/kubeflow/kustomization.yaml
apps/mpi-job/upstream/overlays/standalone/kustomization.yaml

Part of kubeflow 1.4 release.
Use MPI operator tag v0.3.0, but ensure the v1 controller is used.

Use MPI operator tag v0.3.0

---

contrib/seldon/seldon-core-operator/base/kubeflow-edit-seldon.yaml
contrib/seldon/seldon-core-operator/base/kustomization.yaml

Resolves #1764
@yanniszark @cliveseldon @Bobgy since it affects pipeline permissions
In a multi-user kubeflow installation each user should be able to create seldon AND kfserving deployments inside his namespace, especially from a pipeline.
for kfserving this is enabled at https://github.com/kubeflow/manifests/blob/f4cca979d3020a04e45db65bc58d7bbfe386ffd6/apps/kfserving/upstream/kfserving-install/base/cluster-role.yaml#L174 AND https://github.com/kubeflow/manifests/blob/f4cca979d3020a04e45db65bc58d7bbfe386ffd6/apps/kfserving/upstream/installs/generic/cluster-role.yaml#L18
I would like to add the following somewhere to fix the problem for seldon too
```
cat <<EOF | kubectl apply -f -
apiVersion: …
```

feat: add seldon permissions to default-editor

---

README.md
apps/katib/upstream/components/controller/katib-config.yaml
apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
apps/katib/upstream/installs/katib-external-db/kustomization.yaml
apps/katib/upstream/installs/katib-openshift/kustomization.yaml
apps/katib/upstream/installs/katib-standalone/kustomization.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml

Related: https://github.com/kubeflow/katib/issues/1597
I updated manifests for the latest Katib 0.12.0-rc.1 release which includes the latest bug fixes.
Check [the Changelog](https://github.com/kubeflow/katib/blob/2776dedd1209a77424085b1f759390fa78df5918/CHANGELOG.md#v0120-rc1-2021-09-07) for this release.
/assign @kubeflow/release-team 
/cc @kubeflow/wg-automl-leads 
**Checklist:**
2. `make test`

Update manifests for Katib 0.12.0-rc.1 release

---

README.md
apps/mpi-job/upstream/base/deployment.yaml
apps/mpi-job/upstream/overlays/kubeflow/kustomization.yaml
apps/mpi-job/upstream/overlays/standalone/kustomization.yaml

Resolves #2009
Cherry pick of #2012
**Checklist:**
2. `make test`

Cherry-pick: Use MPI operator tag v0.3.0

---

README.md
apps/training-operator/upstream/base/deployment.yaml
apps/training-operator/upstream/base/service.yaml
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml

Resolves https://github.com/kubeflow/manifests/issues/2018  https://github.com/kubeflow/manifests/issues/2005
Update training operator to v1.3.0-rc.1
/cc @kimwnasptd @johnugeorge @andreyvelich 
**Checklist:**
2. `make test`

Update training operator to v1.3.0-rc.1

---

README.md
apps/training-operator/upstream/base/kubeflow.org_mxjobs.yaml
apps/training-operator/upstream/base/kubeflow.org_pytorchjobs.yaml
apps/training-operator/upstream/base/kubeflow.org_tfjobs.yaml
apps/training-operator/upstream/base/kubeflow.org_xgboostjobs.yaml
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml

Resolves #https://github.com/kubeflow/gcp-blueprints/issues/317
Update training operator to v1.3.0-rc.2
**Checklist:**
2. `make test`

Update training operator to v1.3.0-rc.2

---

apps/mpi-job/upstream/overlays/kubeflow/kustomization.yaml
apps/mpi-job/upstream/overlays/standalone/kustomization.yaml

Resolves #2009 
Use MPI operator tag v0.2.3
Ensure the v1alpha2 controller is used.
**Checklist:**
2. `make test`

Use MPI operator tag v0.2.3

---

README.md
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml

Resolves #
training operator 1.3.0 has been released. Please help merge this PR in master
**Checklist:**
2. `make test`

Update training operator to v1.3.0

---

README.md
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml

We've cut the `v1.4.0` tag in the kubeflow/kubeflow repo. This PR syncs the manifests for it.
/cc @elikatsis

Update components of kubeflow/kubeflow for 1.4

---

common/kubeflow-namespace/base/namespace.yaml

I notice that we added Katib Metrics Collector injection label to `kubeflow` namespace in this PR: https://github.com/kubeflow/manifests/pull/1787.
We should not do that since users have to submit Katib Experiments only in Profile's namespaces.
/assign @gaocegege @johnugeorge @yanniszark @kimwnasptd 
**Checklist:**
2. `make test`

Remove Katib label from Kubeflow namespace

---

common/knative/knative-serving/base/kustomization.yaml
common/knative/knative-serving/base/patches/service-labels.yaml

Resolves #2082
When deploying knative-serving there a race due to an Istio issue that ends up having cluster-local-gateway misconfigured because of conflicting ports. In a nutshell Istio creates listeners based on Gateway ports and the corresponding Services (if any) and in our case we have two Services (cluster-local-gateway, knative-local-gateway) with port 80 and different targetPort (8080, 8081). In normal operation the pod gets the following listeners:
```
ADDRESS PORT  MATCH DESTINATION
0.0.0.0 8080  ALL   Route: http.80
0.0.0.0 8081  ALL   Route: http.8081
```
We have seen on fresh deployment to end up with only 8081:8081 and istio complaining with:
```
Error adding/updating listener(s) 0.0.0.0_8081: …
```

knative-serving: Workaround Istio race wrt Gateway creation

---

common/knative/knative-serving/base/kustomization.yaml
common/knative/knative-serving/base/patches/service-labels.yaml

Cherry-picking https://github.com/kubeflow/manifests/pull/2092 into the 1.4 branch to prepare for the 1.4.1 patch release
/cc @elikatsis

knative-serving: Workaround Istio race wrt Gateway creation (#2092)

---

apps/admission-webhook/upstream/base/kustomization.yaml
apps/admission-webhook/upstream/overlays/cert-manager/certificate.yaml
apps/admission-webhook/upstream/overlays/cert-manager/kustomization.yaml
apps/centraldashboard/upstream/base/deployment.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/overlays/istio/authorizationpolicy.yaml
apps/centraldashboard/upstream/overlays/istio/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/manager/manager.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/base/namespace-labels.yaml
apps/profiles/upstream/overlays/kubeflow/authorizationpolicy.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/patches/kfam.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/manager/manager.yaml
apps/tensorboard/tensorboard-controller/upstream/rbac/role.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml

Refs #2109 
/cc @StefanoFioravanzo @elikatsis

Update kubeflow/kubeflow manifests from v1.5.0-rc.0

---

README.md

This PR fixes link for Katib v0.13.0-rc.0 manifests.
/assign @kimwnasptd @StefanoFioravanzo 
/cc @kubeflow/wg-automl-leads 
**Checklist:**
2. `make test`

Fix link for Katib v0.13.0-rc.0 manifests

---

README.md
apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
apps/pipeline/upstream/base/cache/kustomization.yaml
apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
apps/pipeline/upstream/base/metadata/base/kustomization.yaml
apps/pipeline/upstream/base/pipeline/kustomization.yaml
apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
apps/pipeline/upstream/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
hack/sync-pipelines-manifests.sh

Refs https://github.com/kubeflow/manifests/issues/2111
I've updated the manifests with the `1.8.0-rc.2` tag of Pipelines. I also updated the sync script to be changing the README file as well.

Sync kubeflow pipelines manifests 1.8.0 rc.2

---

README.md
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/cluster-role.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/role-binding.yaml
apps/jupyter/jupyter-web-app/upstream/base/role.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml
hack/sync-kubeflow-manifests.sh

Refs #2109 
I also updated the sync-scripts to be updating the README, so that we don't have to do this manually. The PR used the new [`v1.5-rc.1`](https://github.com/kubeflow/kubeflow/tree/v1.5.0-rc.1) tag in the kubeflow/kubeflow repo.
@kubeflow/release-team  this should be the last component to be updated before cutting the RC1, which distribution testing phase will use
EDIT: Correction, it's this and the update for including the models web app https://github.com/kserve/models-web-app/tree/release-0.7

Sync kubeflow kubeflow manifests v1.5.0 rc.1

---

README.md
apps/katib/upstream/components/controller/katib-config.yaml
apps/katib/upstream/components/controller/trial-templates.yaml
apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
apps/katib/upstream/installs/katib-external-db/kustomization.yaml
apps/katib/upstream/installs/katib-openshift/kustomization.yaml
apps/katib/upstream/installs/katib-standalone/kustomization.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml

Related https://github.com/kubeflow/katib/issues/1774
I updated manifests for Katib v0.13.0-rc.1 release.
This RC fixes labels problem discussed under: https://github.com/kubeflow/manifests/issues/2106#issuecomment-1034674392.
/assign @kubeflow/wg-automl-leads @kubeflow/release-team  @yhwang
**Checklist:**
2. `make test`

Update manifests for Katib v0.13.0-rc.1 release

---

README.md

* Remove unused MPI reference (PR #2119)
* Resolves #1963
* Remove unused MPI reference (ref PR #2119)
* Resolves #1963: adds a link to the kubeflow distributions from the ingress/LB section
**Checklist:**
2. `make test`

readme: Remove MPI reference and add ingress distributions link

---

README.md
apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
apps/pipeline/upstream/base/cache/kustomization.yaml
apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
apps/pipeline/upstream/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
apps/pipeline/upstream/base/metadata/base/kustomization.yaml
apps/pipeline/upstream/base/pipeline/kustomization.yaml
apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
apps/pipeline/upstream/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml

Refs #2111 
Closes #2133 
Bumps the KFP manifests to `1.8.0` https://github.com/kubeflow/manifests/pull/2142#issuecomment-1041367206.

Update kubeflow/pipelines manifests from 1.8.0

---

hack/setup-kubeflow-light.sh
hack/setup-kubeflow.sh

Right now the helper scripts for installing kubeflow will try to create the `kubeflow` namespace. But if it already exists, then the script will fail altogether, since we have `-e`.
There have been a lot of cases where I needed to re-run the script in the same cluster, and had to comment out this line. 
Instead I've updated the scripts to try and apply the `kubeflow` namespace, so that it won't fail if it already exists

hack: Don't error if namespace kubeflow exists

---

contrib/kserve/models-web-app/base/istio.yaml
contrib/kserve/models-web-app/base/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml

Update the app's manifests to:
1. Work under the /kserve-endpoints prefix https://github.com/kserve/models-web-app/pull/32
2. Use the correct gatway in the manifests https://github.com/kserve/models-web-app/pull/32
3. Use the correct namespace in for the app's ConfigMap https://github.com/kserve/models-web-app/pull/33

kserve: Update the Models web app

---

contrib/kserve/kserve/aggregated-roles.yaml
contrib/kserve/kserve/kustomization.yaml
example/kustomization.yaml

When we install both KFServing 0.6.1 and KServe 0.7.0 we are using the standalone version of KServe 0.7.0. But, the standalone KServe installation does not include the aggregated roles for the KF `kubeflow-{admin,editor,viewer}` roles.
This PR adds the needed clusterroles/bingings as a distinct file to explicitly include them, when installing both KFServing and standalone KServe.
This should be removed within the next release.
Depends on:
1. https://github.com/kserve/models-web-app/pull/32
3. https://github.com/kubeflow/kubeflow/pull/6383

kserve: Add distinct file for cluster-roles

---

README.md

Update individual component instructions to match single line installation
**Note to reviewer**
Do we need to add a separate instructions for installing central dashboard with kfserving webapp similar to kserve/kfserving section?
**Checklist:**
2. `make test`

sync single-line install command with individual component install

---

README.md
apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
apps/pipeline/upstream/base/cache/kustomization.yaml
apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
apps/pipeline/upstream/base/metadata/base/kustomization.yaml
apps/pipeline/upstream/base/pipeline/kustomization.yaml
apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
apps/pipeline/upstream/env/cert-manager/base/cache-cert-issuer.yaml
apps/pipeline/upstream/env/cert-manager/base/cache-cert.yaml
apps/pipeline/upstream/env/cert-manager/base/cache-webhook-config.yaml
apps/pipeline/upstream/env/cert-manager/base/kustomization.yaml
apps/pipeline/upstream/env/cert-manager/base/params.yaml
apps/pipeline/upstream/env/cert-manager/cluster-scoped-resources/kustomization.yaml
apps/pipeline/upstream/env/cert-manager/dev/delete-cache-deployer.yaml
apps/pipeline/upstream/env/cert-manager/dev/kustomization.yaml
apps/pipeline/upstream/env/cert-manager/dev/namespace.yaml
apps/pipeline/upstream/env/cert-manager/dev/params.yaml
apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user/delete-cache-deployer.yaml
apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user/kustomization.yaml
apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
example/kustomization.yaml
hack/setup-kubeflow-light.sh
tests/README.md

Resolves #2165
- Add kubeflow/pipelines manifests for [1.8.2](https://github.com/kubeflow/pipelines/tree/1.8.2)
- This update brings in cert-manager for pipelines which uses cert-manager for the certificate needed for cache-server (see #2165 for more details)
- Update README, example manifest and e2e test to use cert-manager based overlay for pipeline so the example can be agnostic to the K8s platform
**Testing**
Env: EKS - 1.21, Kustomize - 3.2.0
Install Kubeflow
```
./hack/setup-kubeflow.sh
```
- Run e2e test
```
cd tests/e2e
pip install -r requirements.txt
./runner.sh
```
- Manually verified cache-server pod is running
```
$ kubectl get pods -n kubeflow | grep cache-server
cache-server-5bdbd59959-mrzhp …
```

Sync kubeflow/pipelines manifests 1.8.2

---

contrib/networkpolicies/kustomization.yaml
contrib/networkpolicies/metadata-envoy.yaml
contrib/networkpolicies/minio.yaml

@kimwnasptd 
minio should be reachable by authenticated users. it is anyway reachable from inside the cluster. This helps with external storage management
Without the metadata-envoy the corresponding part of the UI is broken.
**Checklist:**
2. `make test`

Update minio and metadata-envoy networkpolicy

---

README.md
apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_mxjobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
apps/training-operator/upstream/base/deployment.yaml
apps/training-operator/upstream/overlays/kubeflow/kubeflow-training-roles.yaml
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml
hack/sync-training-operator-manifests.sh

Used the sync script in `hack`.
I also updated the README to use the `training-operator` GH link, instead of the `tf-operator` one. Lastly I updated the sync script to automatically fix the README as well.
cc @johnugeorge

Sync kubeflow training operator manifests v1.5.0 rc.0

---

.github/workflows/centraldb_kind_test.yaml
.github/workflows/jwa_kind_test.yaml
.github/workflows/katib_kind_test.yaml
.github/workflows/kserve_kind_test.yaml
.github/workflows/nb_controller_kind_test.yaml
.github/workflows/pipeline_kind_test.yaml
.github/workflows/poddefaults_kind_test.yaml
.github/workflows/profiles_kind_test.yaml
.github/workflows/tb_controller_kind_test.yaml
.github/workflows/train_operator_kind_test.yaml
.github/workflows/twa_kind_test.yaml
.github/workflows/vwa_kind_test.yaml
tests/gh-actions/kind-cluster-1-20.yaml
tests/gh-actions/kind-cluster-1-21.yaml
tests/gh-actions/kind-cluster-1-22.yaml

As requested here https://github.com/kubeflow/manifests/pull/2237#issuecomment-1171430252 we're moving all the KinD configuration files in one place and make sure that they all use the images from v0.14.0.

Change images of KinD configuration files to be compatible with v0.14.0

---

.github/workflows/kserve_kind_test.yaml
README.md
contrib/kserve/kserve/kserve-runtimes.yaml
contrib/kserve/kserve/kserve.yaml
contrib/kserve/kserve/kserve_kubeflow.yaml
contrib/kserve/kserve/kustomization.yaml
contrib/kserve/kserve/params.env
contrib/kserve/models-web-app/base/deployment.yaml
contrib/kserve/models-web-app/base/istio.yaml
contrib/kserve/models-web-app/base/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml
hack/sync-kserve-manifests.sh
tests/gh-actions/install_kserve.sh

#2197 
- Add a script to sync kserve and kserve models-web-app manifests for future releases. This can be plugged in as a GH action since it clones and copies the manifests
- Update kserve/kserve manifests from `8079f375cbcedc4d45a1b4aade2e2308ea6f9ae8` commit in `release-0.8` branch since a new release is not available after https://github.com/kserve/kserve/pull/2298
- Update kserve/models-web-app manifests from v0.8.0
- **Note:** this PR should be merged after #2239 
**Testing**
- `kustomize build example` works

Sync kserve manifests for v0.8.0

---

.github/workflows/dex_kind_test.yaml
common/dex/base/crds.yaml
common/dex/base/deployment.yaml

Refs #2200
Dex had some `CRD`, `ClusterRole` and `ClusterRoleBinding` resources that were using the deprecated `apiextensions.k8s.io/v1` API.
This PR:
1. Updates these APIs
2. Add a GH Action for testing the Dex manifests as well

Update Dex for K8s 1.22

---

common/istio-1-14/kubeflow-istio-resources/overlays/deploy/kustomization.yaml
common/istio-1-14/kubeflow-istio-resources/overlays/ekf/kustomization.yaml
common/istio-1-14/kubeflow-istio-resources/overlays/minikf/kustomization.yaml

Remove overlays in 'kubeflow-istio-resources' for version 1.14.
Signed-off-by: Dimitris Poulopoulos <dimpo@arrikto.com>

istio: Remove Istio 1.14 overlays

---

common/knative/README.md
common/knative/knative-eventing-post-install-jobs/base/eventing-post-install-jobs.yaml
common/knative/knative-eventing/base/kustomization.yaml
common/knative/knative-eventing/base/upstream/eventing-core.yaml
common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
common/knative/knative-serving/base/istio-authorization-policy.yaml
common/knative/knative-serving/base/upstream/net-istio.yaml
common/knative/knative-serving/base/upstream/serving-core.yaml

* Update the README file
* Fetch the manifests for Knative serving 1.2.5
* Fetch the manifests for Knative eventing 1.2.4
* Remove comments, anchors and aliases
Signed-off-by: Dimitris Poulopoulos <dimpo@arrikto.com>

knative: Updrade Knative to version 1.2

---

README.md
contrib/kserve/models-web-app/base/istio.yaml
contrib/kserve/models-web-app/base/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/patches/web-app-vsvc.yaml
hack/sync-kserve-kserve-manifests.sh
hack/sync-kserve-web-app-manifests.sh
tests/e2e/hack/cleanup_yamls.sh
tests/e2e/settings.py

Did a couple of changes to wrap up the work around the web app in this PR and testing. Specifically:
1. I created a new patch release for the MWA https://github.com/kserve/models-web-app/tree/v0.8.1/config
2. Created a distinct script for the MWA, for syncing the manifests, and decoupled it from a single one for doing both the app and kserve
3. Doubled the timeout in the e2e test script. I noticed that sometimes even when everything would run as expected 5mins wasn't enough for some steps
4. Update the cleanup script, in the e2e test script, to use `kserve.io` and not `kubeflow.org` (we had missed this place)
cc @annajung @surajkota

Sync kserve web app manifests v0.8.1

---

contrib/metacontroller/OWNERS

Maintain this third-party dependency because it comes from KFP : https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/third-party/metacontroller
**Checklist:**
2. `make test`

chore: Add James Liu and Ablai to manage metacontroller

---

README.md

Sync kubeflow/training-operator manifests from v1.5.0. Previous version was v1.5.0-rc.
cc @annajung

Update kubeflow/training-operator manifests from v1.5.0

---

.github/workflows/katib_kind_test.yaml
apps/katib/upstream/components/controller/katib-config.yaml
apps/katib/upstream/components/controller/trial-templates.yaml
apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
apps/katib/upstream/installs/katib-external-db/kustomization.yaml
apps/katib/upstream/installs/katib-openshift/kustomization.yaml
apps/katib/upstream/installs/katib-standalone/kustomization.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml

- Sync Katib 0.14.0 ([ref](https://github.com/kubeflow/manifests/issues/2200#issuecomment-1220490112))

Update kubeflow/katib manifests from v0.14.0

---

README.md
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml

Updates the Notebook WG components to use the newly cut [`v1.6.0`](https://github.com/kubeflow/kubeflow/releases/tag/v1.6.0)
/cc @annajung

Update kubeflow/kubeflow manifests from v1.6.0

---

README.md
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml

- Sync notebook to 1.6.1-rc.0 which includes a fix for https://github.com/kubeflow/kubeflow/pull/6659
cc @kubeflow/release-team @kimwnasptd

Update kubeflow/kubeflow manifests from v1.6.1-rc.0

---

common/istio-1-14/istio-install/base/kustomization.yaml

Include the resources and patches in Istio install kustomization. Specifically, include:
* 'service.yaml' patch
* 'remove-pdb.yaml' patch
* 'istio-configmap-disable-tracing.yaml' patch
and:
* 'gateway_authorizationpolicy.yaml' resource
* 'deny_all_authorizationpolicy.yaml' resource
* 'gateway.yaml' resource
* 'x-forwarded-host.yaml' resource
Signed-off-by: Dimitris Poulopoulos <dimpo@arrikto.com>

istio: Include patches and resources in Istio install kustomization

---

.github/workflows/kserve_kind_test.yaml
tests/gh-actions/install_knative.sh
tests/gh-actions/kf-objects/kserve_test.yaml

Refs https://github.com/kubeflow/manifests/issues/2248

Extend KServe GH action to also apply an inference service and assert it becomes ready

---

README.md
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml

Syncing manifests with the latest `v1.6.1` tag of the kubeflow/kubeflow repo
/cc @annajung

Update kubeflow/kubeflow manifests from v1.6.1

---

common/istio-1-14/istio-install/base/gateway_authorizationpolicy.yaml

The other authorizationpolicies in the same folder have the namespace properly set (deny_all_authorizationpolicy.yaml)
Some people bring their own base istio and this leads to problems. This is also preparation for istio-cni @kimwnasptd 
**Checklist:**
2. `make test`

Missing namespace in authorizationpolicy

---

common/dex/base/kustomization.yaml

The dex image had been updated to a new registry in #2243, thus, making this image override non-functional here. 
I propose removing it here (it's dead code anyhow) and letting only the deployment.yaml refer to the image in question.
**Checklist:**
2. `make test`

Removed deprecated image override for dex

---

contrib/application/README.md
contrib/basic-auth/README.md
contrib/experimental/README.md
contrib/gatekeeper/README.md
contrib/modeldb/README.md
contrib/spartakus/README.md

- Add README to the following components to mark the directory as unmaintained and out of date
- `/contrib/application`
- `/contrib/basic-auth`
- `/contrib/experimental`
- `/contrib/gatekeeper`
- `/contrib/modeldb`
- `/contrib/spartakus`
cc @kimwnasptd @kubeflow/wg-manifests-leads

Add unmaintained notice to contrib components

---

.github/workflows/jwa_kind_test.yaml
.github/workflows/twa_kind_test.yaml
README.md
common/istio-1-16/README.md
hack/setup-kubeflow-light.sh
tests/gh-actions/install_knative.sh

Follow-up PR from: https://github.com/kubeflow/manifests/pull/2327
- Update Istio version reference in main README file
- Replace all references of `istio-1-14` with `istio-1-16`
- installation instructions in README
- helper scripts
- Minor fixes for GH Action workflows
Refs: https://github.com/kubeflow/manifests/issues/2325
cc. @kimwnasptd 
Signed-off-by: Apostolos Gerakaris <apoger@arrikto.com>

Update Istio version references to v1.16

---

contrib/tektoncd/README.md

Add README to `/contrib/tektoncd` to mark the directory as unmaintained and out of date
**Note:**
Tagging tektoncd component [owners](https://github.com/kubeflow/manifests/blob/master/contrib/flink/OWNERS) @Tomcli @animeshsingh @pvaneck to ensure awareness of the out-of-date label on the component.
cc @kimwnasptd …

Add unmaintained notice to contrib tektoncd

---

.github/workflows/metacontroller_kind_test.yaml
contrib/metacontroller/Makefile
contrib/metacontroller/README.md
contrib/metacontroller/UPDGRADE.md
contrib/metacontroller/base/stateful-set.yaml
contrib/metacontroller/test/catset-controller.yaml

Updating `contrib/metacontroller` to address #2311 and to comply with [contrib guidelines](https://github.com/kubeflow/manifests/blob/master/proposals/20220926-contrib-component-guidelines.md)
- Added tests
- Added `UPGRADE.md`
- Updated `README.md`
- Added `metacontroller_kind_test.yaml` to GH-actions
**Checklist:**

Fix contrib/metacontroller folder

---

contrib/dex-auth/README.md

Add README to `/contrib/dex-auth` to mark the directory as unmaintained and out of date
**Note:**
Tagging dex-auth component [owners](https://github.com/kubeflow/manifests/blob/master/contrib/dex-auth/OWNERS) @krishnadurai @yanniszark to ensure awareness of the out-of-date label on the component.
cc @kimwnasptd …

Add unmaintained notice to contrib dex-auth

---

contrib/flink/README.md

Add README to `/contrib/flink` to mark the directory as unmaintained and out of date
**Note:**
Tagging flink component [owners](https://github.com/kubeflow/manifests/blob/master/contrib/flink/OWNERS) @Jeffwan to ensure awareness of the out-of-date label on the component.
cc @kimwnasptd @kubeflow/wg-manifests-leads

Add unmaintained notice to contrib flink

---

contrib/feast/README.md

Add README to `/contrib/feast` to mark the directory as unmaintained and out of date
**Note:**
Tagging feast component [owners](https://github.com/kubeflow/manifests/blob/master/contrib/feast/OWNERS) @woop  @tedhtchang to ensure awareness of the out-of-date label on the component.
cc @kimwnasptd @kubeflow/wg-manifests-leads

Add unmaintained notice to contrib feast

---

contrib/README.md

Add README to `/contrib/spark` to mark the directory as unmaintained and out of date
**Note:**
Tagging spark component [owners](https://github.com/kubeflow/manifests/blob/master/contrib/spark/OWNERS) @Jeffwan @holdenk to ensure awareness of the out-of-date label on the component.
cc @kimwnasptd @kubeflow/wg-manifests-leads

Add unmaintained notice to contrib spark

---

README.md
common/knative/README.md
common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
common/knative/knative-serving/base/upstream/net-istio.yaml
common/knative/knative-serving/base/upstream/serving-core.yaml

Changes:
- Update knative serving manifests to [v1.8.1](https://github.com/knative/serving/releases/tag/knative-v1.8.1) to support K8s-v1.25
- Update Istio Ingress controller manifests to [v1.8.0](https://github.com/knative-sandbox/net-istio/releases/tag/knative-v1.8.0)
- Update `README` files (version references, instructions etc)
Refs: https://github.com/kubeflow/manifests/issues/2325

common: Upgrade Knative Serving manifests to version 1.8.1

---

.github/workflows/kserve_kind_test.yaml
common/knative/README.md
common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
common/knative/knative-eventing-post-install-jobs/base/kustomization.yaml
common/knative/knative-eventing/base/kustomization.yaml
common/knative/knative-eventing/base/upstream/eventing-core.yaml
common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml

Changes:
- Update knative eventing manifests to v1.8.1 to support K8s-v1.25
- Update README files (version references, instructions etc)
- Trigger the test workflow of each component, that uses Knative, when Knative-serving/eventing manifests are changed
Refs: https://github.com/kubeflow/manifests/issues/2325

common: Upgrade Knative Eventing manifests to version 1.8.1

---

apps/centraldashboard/upstream/base/configmap.yaml
apps/centraldashboard/upstream/overlays/kserve/patches/configmap.yaml

This PR renames `Models` to `Endpoints` in the central dashboard.
Related issue: https://github.com/kserve/kserve/issues/2534
Related PR: https://github.com/kserve/models-web-app/pull/57

centraldashboard: Rename Models to Endpoints

---

.github/workflows/bentoml_kind_test.yaml
contrib/bentoml/Makefile
contrib/bentoml/OWNERS
contrib/bentoml/README.md
contrib/bentoml/UPGRADE.md
contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/kustomization.yaml
contrib/bentoml/bentoml-yatai-stack/bases/yatai-deployment/resources.yaml
contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/kustomization.yaml
contrib/bentoml/bentoml-yatai-stack/bases/yatai-image-builder/resources.yaml
contrib/bentoml/bentoml-yatai-stack/default/kustomization.yaml
contrib/bentoml/example.yaml
contrib/bentoml/sources/kustomization-template.yaml
contrib/bentoml/sources/yatai-deployment-values.yaml
contrib/bentoml/sources/yatai-image-builder-values.yaml
contrib/bentoml/test.sh

- BentoML is an open-source framework for developing, serving, and deploying ML services.
- Building
- Unifies ML frameworks with out-of-the-box implementation of popular frameworks
- Exposes gRPC and OpenAPI for serving
- Provides Python SDK for development
- Deployment
- Any environment, batch inference, streaming, or online serving
- Any cloud platform for on-prem
- Full observability support through Grafana
- Yatai - BentoML's deployment platform
Goal: From simple Python module to distributed Kubernetes deployment.
Consider the following common ML services involve custom pre and post-processing logic and inference of multiple models.
- Create a service using saved model.
```
%%writefile service.py
import asyncio
import bentoml
fraud_detection = …
```

Feat: Add BentoML Yatai Stack contrib

---

contrib/OWNERS

@juliusvonkohout has been helping on the Manifests WG for a very long time and has done an amazing job on reviews on the `/contrib` folder. For this reason I'd like to promote Julius to be a reviewer for the `/contrib` dir.
I'm also creating this PR after looking at https://github.com/kubeflow/manifests/pull/2337. I believe that we should have a more granular process of adding someone as an approver in the whole repo and taking iterative steps. The first one is to acknowledge Julius' help on reviews and ensure the OWNERS file represent that. Then move progressively based on the (great!) contributions that will be getting merged.
At the same time I want to ensure that we have a common process for next steps for everyone, and I think https://github.com/kubeflow/community/pull/591 is the …

Add Julius von Kohout as reviewer for /contrib

---

README.md

PR to update the README, based on the progress from https://github.com/kubeflow/manifests/issues/2360
This PR 
1. adds some more troubleshooting notes on the manual installation method 
2. makes it clear when users can use Kustomize 3.2 and when 4.5.7
cc @DomFleischmann @jbottum

Update the README for kustomize 4.5.7 support

---

README.md

Update the manifests for Notebooks WG components from the newly cut [`v1.7.0-rc.0`](https://github.com/kubeflow/kubeflow/tree/v1.7.0-rc.0) tag, thanks @DomFleischmann!
/cc @elikatsis

Update kubeflow/kubeflow manifests from v1.7.0-rc.0

---

apps/katib/upstream/components/controller/controller.yaml
apps/katib/upstream/components/controller/katib-config.yaml
apps/katib/upstream/components/controller/rbac.yaml
apps/katib/upstream/components/controller/service.yaml
apps/katib/upstream/components/controller/trial-templates.yaml
apps/katib/upstream/components/postgres/kustomization.yaml
apps/katib/upstream/components/postgres/postgres.yaml
apps/katib/upstream/components/postgres/pvc.yaml
apps/katib/upstream/components/postgres/secret.yaml
apps/katib/upstream/components/postgres/service.yaml
apps/katib/upstream/components/ui/rbac.yaml
apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
apps/katib/upstream/installs/katib-external-db/kustomization.yaml
apps/katib/upstream/installs/katib-openshift/kustomization.yaml
apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
apps/katib/upstream/installs/katib-standalone-postgres/patches/db-manager.yaml
apps/katib/upstream/installs/katib-with-kubeflow/istio-authorizationpolicy.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kubeflow-katib-roles.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml
apps/katib/upstream/installs/katib-with-kubeflow/patches/enable-ui-authz-checks.yaml
apps/katib/upstream/installs/katib-with-kubeflow/patches/istio-sidecar-injection.yaml
apps/katib/upstream/installs/katib-with-kubeflow/patches/ui-rbac.yaml

Update Katib manifests to v0.15.0-rc0.
@johnugeorge @andreyvelich @kimwnasptd

Update kubeflow/katib manifests from v0.15.0-rc.0

---

example/kustomization.yaml

It seems like the profiles manifests where commented out accidentally when updating the seldon manifests. This was causing the one-line installation to fail. By uncommenting this line the installation should work again.

Uncomment profiles manifests in example dir

---

README.md
contrib/kserve/models-web-app/base/deployment.yaml
contrib/kserve/models-web-app/base/kustomization.yaml
tests/gh-actions/install_knative.sh
tests/gh-actions/install_kserve.sh
tests/gh-actions/install_pipelines.sh

Update the models web app manifests for the `v0.10.0` tag.
Also made some minor updates to the README in preparation for the release branch. Main one being that the README now explicitly shows the KF version. This is to make it slightly easier for anyone rebasing/merging a release branch into their own to have a single place to know which KF version they had used.
/cc @DomFleischmann

Sync MWA manifests from 0.10.0 and show KF version in README

---

common/oidc-authservice/base/kustomization.yaml

Recent https://github.com/kubeflow/manifests/pull/2150 modifies the version of `oidc-authservice` in [/common/oidc-authservice/base/statefulset.yaml](https://github.com/kubeflow/manifests/blob/8e5714171f1fd5b00f59f436e9ab8cb45a0f30e3/common/oidc-authservice/base/statefulset.yaml#L21) but not in the `kustomization.yaml`. Therefore, image update is not applied when installing kubeflow.
Tested that new image tag is not applied by running the following command using kustomize version 3.2.0
```
kustomize build example | grep "image: gcr.io/arrikto/kubeflow/oidc-authservice"
```
- Update oidc-authservice image tag
cc @kimwnasptd @ittus

Update oidc image tag

---

README.md
apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
apps/pipeline/upstream/base/cache/kustomization.yaml
apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
apps/pipeline/upstream/base/metadata/base/kustomization.yaml
apps/pipeline/upstream/base/pipeline/kustomization.yaml
apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml

Resolves https://github.com/kubeflow/pipelines/issues/8938
Steps to run the sync script for future reference:
1. Export the commit `export COMMIT=2.0.0-alpha.7`
1. Clone the pipelines repo locally and checkout the required commit
```
cd /tmp/
git clone https://github.com/kubeflow/pipelines.git kubeflow-pipelines
git checkout $COMMIT
```
1. cd to root of manifests repo
1. Run the sync script `./hack/sync-pipelines-manifests.sh`
1. Create the PR from your fork
Its worth converting this to a github action in future in the meantime little documentation could save some developer time.

Update kubeflow/pipelines manifests from 2.0.0-alpha.7

---

.github/workflows/manifests_unittests.yaml
README.md
example/kustomization.yaml
tests/gh-actions/install_kustomize.sh

Cherrypick #2404  to v1.7-branch

Update instructions for Kustomize 5 (#2399)

---

contrib/OWNERS

Resolves the current problem that the bentoml update and ray integration is stalled because of lack of approvers. In the future this will also relieve some burden of the manifests maintainers.
Follow up of https://github.com/kubeflow/manifests/pull/2371 and https://github.com/kubeflow/manifests/blob/master/contrib/networkpolicies/OWNERS
@kimwnasptd then we can progress with https://github.com/kubeflow/manifests/pull/2383 and https://github.com/kubeflow/manifests/pull/2414
orthogonal to https://github.com/kubeflow/manifests/pull/2337/
**Checklist:**
2. `make test`

Promote Julius von Kohout from reviewer to approver for /contrib 

---

proposals/20230323-end-to-end-testing.md

Move the content of [end-to-end manifest testing proposal doc](https://docs.google.com/document/d/1ipY1RxnAuJCFHJAd9xc7KfFaiMZQTQtk92u_HY5eBl4) to github
During May 18th meeting, it was agreed to move the content of the proposal into the Manifest repo and collect the proposal in one place.
The date in the file name (20230323) represents the day the proposal was approved.
cc @DomFleischmann @kimwnasptd

Add end-to-end testing proposal

---

hack/extract_images.sh

The script reports images used by each KF Working Group and an inventory of all images used within Kubeflow/all WGs. Not all kustomization files are considered by the script - only specific directories. See the table below:
| Working Group         	| Directories                                                                                                                                                                                                                                                                                                                      	|
|-----------------------	|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …

Add bash script that extracts used images

---

.github/workflows/pipeline_kind_test.yaml
README.md
tests/e2e/requirements.txt
tests/gh-actions/install_kind.sh
tests/gh-actions/install_pipelines.sh
tests/gh-actions/kind-cluster-1-25.yaml

Part of https://github.com/kubeflow/manifests/issues/2450
- Move default KinD 1.25 to `kind-cluster-1-25.yaml`
- Add support for Kubernetes 1.26 and set it to default for testing
- Update the requirements.txt to run e2e with katib 0.15 and kfp 1.8.22

Add Kubernetes version 1.26 and set it to default for testing

---

OWNERS

@kimwnasptd 
We now have the updated charta for leadership roles https://github.com/kubeflow/community/pull/632/files which say:
```
* Primary reviewer for at least 2 PRs in `/common`
* Primary reviewer for at least 1 PR in `/tests`
* Primary reviewer for at least 1 PR in `/contrib`
```
I satisfy all of those requirements based on my commit history https://github.com/kubeflow/manifests/commits?author=juliusvonkohout and i am already approver in /contrib.
I can also provide a way longer list of PRs that i reviewed and a list of new contributors that i onboarded.
Even though the requirements are about reviewing, so less than committing
my latest PR https://github.com/kubeflow/manifests/pull/2455 touches /common and /tests again.
**Checklist:**
**Make sure you have installed kustomize == …

Add juliusvonkohout as root reviewer

---

README.md
common/knative/README.md
common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
common/knative/knative-eventing/base/upstream/eventing-core.yaml
common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
common/knative/knative-serving/base/upstream/net-istio.yaml
common/knative/knative-serving/base/upstream/serving-core.yaml
common/knative/knative-serving/overlays/gateways/patches/gateway-selectors.yaml
tests/gh-actions/kind-cluster-1-24.yaml
tests/gh-actions/kind-cluster-1-25.yaml
tests/gh-actions/kind-cluster.yaml

Part of https://github.com/kubeflow/manifests/issues/2450
- Upgrade Knative serving to 1.10.2
- Upgrade Knative eventing to 1.101
cc @kimwnasptd

Upgrade Knative serving to 1.10.2 and eventing to 1.10.1

---

common/oidc-authservice/base/kustomization.yaml
common/oidc-authservice/base/statefulset.yaml

Part of #2469 
Mirrored the `gcr.io/arrikto/kubeflow/oidc-authservice:e236439` over to `docker.io/kubeflowmanifestswg/oidc-authservice:e236439`

Update AuthService image for KF 1.6

---

common/oidc-client/oidc-authservice/base/kustomization.yaml

Use the kubeflow manifests WG mirrored container images for pulling oidc-authservice.
Part of #2469
Mirrored the `gcr.io/arrikto/kubeflow/oidc-authservice:e236439` over to `docker.io/kubeflowmanifestswg/oidc-authservice:e236439`
cc: @kimwnasptd @annajung

chore: replace arrikto/kubeflow container registry with kubeflowmanifestswg

---

hack/sync-kubeflow-manifests.sh

Update the `hack/sync-kubeflow-manifests.sh` to be able to sync the pvcviewer-controller.
This change has to be backported to `v1.8-branch`
cc: @kimwnasptd

feat: add pvcviewer to sync script

---

hack/sync-kubeflow-manifests.sh

Update the hack/sync-kubeflow-manifests.sh to be able to sync the pvcviewer-controller. This is a backport from `master`.
cc: @kimwnasptd

feat: add pvcviewer to sync script (#2529)

---

contrib/seldon/Makefile
contrib/seldon/OWNERS
contrib/seldon/README.md
contrib/seldon/example.yaml
contrib/seldon/seldon-core-operator/base/resources.yaml

Updating seldon core to v1.17.1
**Checklist:**
2. `make test`

Updating seldon core to v1.17.1

---

proposals/20200913-rootlessKubeflow.md

Related to #2528 
Add proposal for rootless Kubeflow.
**Checklist:**
2. `make test`

Proposal for rootless Kubeflow

---

README.md
apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
apps/pipeline/upstream/base/cache/kustomization.yaml
apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
apps/pipeline/upstream/base/installs/generic/postgres/pipeline-install-config.yaml
apps/pipeline/upstream/base/metadata/base/kustomization.yaml
apps/pipeline/upstream/base/pipeline/kustomization.yaml
apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml

Sync kubeflow/pipelines tag 2.0.3 manifests.
WG leads @chensun @kubeflow/wg-pipeline-leads 
WG liaison @Davidnet

Update kubeflow/pipelines manifests from 2.0.3

---

README.md
apps/katib/upstream/components/controller/trial-templates.yaml
apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
apps/katib/upstream/installs/katib-external-db/katib-config.yaml
apps/katib/upstream/installs/katib-external-db/kustomization.yaml
apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
apps/katib/upstream/installs/katib-openshift/katib-config.yaml
apps/katib/upstream/installs/katib-openshift/kustomization.yaml
apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
apps/katib/upstream/installs/katib-standalone/katib-config.yaml
apps/katib/upstream/installs/katib-standalone/kustomization.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml

Sync kubeflow/katib tag v0.16.0 manifests.
WG leads @andreyvelich @johnugeorge https://github.com/orgs/kubeflow/teams/wg-automl-leads
WG liaison @nagar-ajay

Update kubeflow/katib manifests from v0.16.0

---

README.md

Sync kubeflow/training-operator tag v1.7.0 manifests
WG leads @andreyvelich @johnugeorge @kubeflow/wg-training-leads 
WG liaison @nagar-ajay

Update kubeflow/training-operator manifests from v1.7.0

---

common/user-namespace/base/kustomization.yaml

While the command is running:
```
kustomize build common/user-namespace/base
```
A warning appeared:
```
```
I used the command:
```
kustomize edit fix --vars
```
And also corrected errors received when executing this command. Manifests are now generated without warnings.
Please note that this PR should not affect the manifests themselves in any way, only the warning is removed.
Resolves #
**Checklist:**
2. `make test`

Fixes user-namespace for kustomize 5

---

common/dex/base/config-map.yaml
common/dex/base/deployment.yaml
common/dex/base/dex-passwords.yaml

Resolves #
**Checklist:**
2. `make test`

Use hashFromEnv in dex component for static user passwords

---

common/dex/base/dex-passwords.yaml
common/dex/base/kustomization.yaml

The dex-passwords secret has not been defined properly and the secret wasn't added to the dex kustomization file.
The changes are done as discussed in https://github.com/kubeflow/manifests/pull/2229#pullrequestreview-1799825164.

Fix #2229 - dex-passwords in common/dex/base

---

common/dex/overlays/istio/kustomization.yaml
common/user-namespace/base/kustomization.yaml

While the command is running:
```
kustomize build common/dex/overlays/istio
```
A warning appeared:
```
```
I used the command:
```
kustomize edit fix --vars
```
And also corrected errors received when executing this command. Manifests are now generated without warnings.
Please note that this PR should not affect the manifests themselves in any way, only the warning is removed.
Resolves #
**Checklist:**
2. `make test`

Fixes dex for kustomize 5

---

common/dex/base/kustomization.yaml
common/dex/overlays/istio/kustomization.yaml

The overlays for ldap and github were not taken into consideration because atm they don't work because the dex's base kustimization doesn't define dex-parameters CM anymore.
These changes shouldn't cause any differences in generated manifests.
Implementing changes discussed here: https://github.com/kubeflow/manifests/pull/2586#issuecomment-1874255700
**Checklist:**
```
$ git reset --hard
HEAD is now at 2d047ae6 Improve dex kustomizations readability
$ kustomize build common/dex/overlays/istio/ > dex.overlay.istio.improve-dex-kustomization-readability.yaml
$ kustomize build common/dex/base/ > dex.overlay.base.improve-dex-kustomization-readability.yaml
$ git checkout master
$ git log -1
commit ed4caf3e26060f626571b421185326257777576c (HEAD -> master, …
```

Improve dex kustomizations readability

---

hack/extract_images.sh

Fix unresolved image name ($VOLUME_VIEWER_IMAGE) produced by hack/extract_images.sh
Resolves #2560
Fix the `sed` command that deletes all lines starting with the `$` sign or curly brackets. Usually, such lines come from plain  CRDs and PodTemplates, multiline configs.   
**Checklist:**
2. `make test`

Fix image name ($VOLUME_VIEWER_IMAGE) produced by hack/extract_images.sh

---

common/cert-manager/kubeflow-issuer/base/kustomization.yaml

Tried to apply manifests generated via kustomize  with `kpt live apply -` and it complained that the kubeflow clusterissuer had a namespace specified. The error message was terse and I had to go digging for it. Seems like 'kubectl' just ignored it but kpt did not.

removed namespace from kubeflow cluster issuer

---

tests/README.md
tests/e2e/README.md
tests/e2e/mnist.py
tests/e2e/runasnonroot.sh
tests/e2e/runner.sh
tests/e2e/utils/kserve.py

We need to list all containers that do not have runasnonroot set or run as the root user. Based on this list i can create per workinggroup patches and at some point we can just enable the test in the e2e pipeline.
Adding tests to warn and later on error on root containers in the cicd.

Add tests for rootless containers

---

.github/pull_request_template.md

Resolves #
**Checklist:**
2. `make test`

Update PR template to install kustomize 5.0.1

---

README.md

Resolves the missing steps to be able to get Kubeflow up and running locally.
It will add some steps in order to make it easy to have Kubeflow on top of kind.
**Checklist:**
- [ x ] Unit tests pass:
2. `make test`

Add steps to install Kubeflow on kind

---

README.md

Append failed during the kind cluster deletion
Some users didn't like the idea of replacing all the content of `~/.kube/config`
Backup the `~/.kube/config` before the replacement
**Checklist:**
- [ X ] Unit tests pass:
2. `make test`

Backup ~/.kube/config before the replacement

---

.github/pull_request_template.md
README.md
go.mod
tests/e2e/README.md
tests/gh-actions/install_kustomize.sh

@rimolive 
https://github.com/kubeflow/manifests/pull/2653

kustomize 5.2.1

---

common/cert-manager/kubeflow-issuer/base/kustomization.yaml
common/istio-1-17/cluster-local-gateway/base/kustomization.yaml
common/istio-cni-1-17/cluster-local-gateway/base/kustomization.yaml
common/knative/README.md
common/knative/knative-eventing/base/kustomization.yaml
common/knative/knative-serving/base/kustomization.yaml
common/knative/knative-serving/base/patches/remove-gateway.yaml
common/knative/knative-serving/base/upstream/net-istio.yaml

Related to https://github.com/kubeflow/manifests/issues/2388
Fix most Kustomize v5 warnings related to for `common/`.
The warning about `vars` being deprecated is still present for `oidc-client/oidc-authservice/base/kustomization.yaml` as I weren't successful in fixing it without changes.
kustomize build generates no changes between old and new version.
**Checklist:**
2. `make test`

fix most kustomize v5 warnings

---

common/oidc-client/oidc-authservice/base/envoy-filter.yaml

Resolves in latest version of istio , the authn-filter may not work becuase of filterChain `envoy.http_connection_manager` is deactived, and changed it to `envoy.filters.network.http_connection_manager` 
https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ListenerMatch-FilterChainMatch
**Checklist:**
2. `make test`

fix: istio 1.70 envoy filter chain should be changed.

---

common/dex/overlays/oauth2-proxy/config-map.yaml

Same as cd991e6010a8c694a729d2978f4c8be597669fff
**Checklist:**
2. `make test`

Also use hashFromEnv for oauth2-proxy overlay

---

README.md

NA
Bump node image to 1.28
**Checklist:**
- [ X ] Unit tests pass:
2. `make test`

Bump node image to 1.28

---

README.md
hack/sync-model-registry-manifests.sh

Resolves https://github.com/kubeflow/manifests/issues/2631
- Added script to automatically fetch model-registry manifests, followed the same approach that has been done for other components
- Updated README adding model-registry row, since there is no version yet I linked `main` branch
**Checklist:**
2. `make test`

Add model registry sync script

---

common/oidc-client/oauth2-proxy/base/kustomization.yaml

This ensures that the namespace is always deployed before anything else, even if fifo ordering is used with Kustomize.
**Checklist:**
2. `make test`

Reorder oauth2-proxy manifests so that namespace is first

---

common/dex/base/deployment.yaml

Resolves #
Upgrade `dex` to `2.39.1`
**Checklist:**
2. `make test`

Upgrade dex to 2.39.1

---

.github/workflows/kserve_cni_test.yaml
README.md
common/knative/README.md
common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
common/knative/knative-eventing/base/upstream/eventing-core.yaml
common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
common/knative/knative-serving/base/upstream/net-istio.yaml
common/knative/knative-serving/base/upstream/serving-core.yaml
hack/sync-knative-manifests.sh

Resolves #
Upgrade knative (used latest versions for `v1.12` stream):
- _Serving_ to `v1.12.4`
- _Extension_ to `v1.12.3`
- _Eventing_ to `v1.12.6`
Add `sync-knative-manifests.sh` script to automate the manifests synchronization (used for https://github.com/kubeflow/manifests/pull/2709/commits/231c54335cb925e2faccf880f753b374ffea5148)
**Checklist:**
2. `make test`

Upgrade knative to v1.12.4

---

contrib/seldon/Makefile
contrib/seldon/seldon-core-operator/base/resources.yaml
hack/sync-seldon-manifests.sh

Resolves https://github.com/kubeflow/manifests/issues/2673
I had to slightly change the `contrib/seldon/Makefile` because the `v1.18.1` charts seem not present in https://storage.googleapis.com/seldon-charts helm chart repo, therefore I switched to download the github repo and using local helm chart. 
**Checklist:**
2. `make test`

Update seldon manifests from v1.18.1

---

hack/extract_images.sh

Included in `hack/extract_images.sh` script the Model Registry images.
N/A
N/A
---     
>You can join our slack channel **wg-manifests** [here](https://www.kubeflow.org/docs/about/community/). This link also contains our meeting schedule.

Change extract_images.sh to include Model Registry

---

common/networkpolicies/base/kustomization.yaml
common/networkpolicies/base/model-registry.yaml

Raising as draft following indication on #2701 but not yet sure how to manually verify: I've tested with `1.9.0-rc.0` on a local cluster, both with _and_ without this network policy, I can reach the service both externally the cluster (authenticated call) and from another pod in a different namespace (namespace "default" using wget from an hello-world pod).
Resolves #2701 
**Checklist:**
2. `make test`

add Model Registry networkpolicy

---

README.md
contrib/kserve/kserve/kserve-cluster-resources.yaml
contrib/kserve/kserve/kserve.yaml
contrib/kserve/kserve/kserve_kubeflow.yaml
hack/sync-kserve-kserve-manifests.sh

Updates kserve to v0.13.0 from v0.12.1
This update was generated using the procedure from contrib/kserve/UPGRADE.md, not using hacks/sync-kserve-kserve-manifests.sh, because kserve [appears to have forgotten to add 0.13.0 to their `install/` directory](https://github.com/kserve/kserve/tree/v0.13.0/install/v0.13.0).  Instead, the manifests here have been pulled directly from [the 0.13.0 release assets](https://github.com/kserve/kserve/releases/tag/v0.13.0)

Sync kserve manifests 0.13.0

---

README.md

> I changed the slack channel to CNCF slack channel
---     

set CNCF slack channel in README file

---

contrib/security/PSS/static/baseline/kustomization.yaml
contrib/security/PSS/static/baseline/patches/istio-labels.yaml
contrib/security/PSS/static/baseline/patches/kubeflow-labels.yaml
contrib/security/PSS/static/restricted/kustomization.yaml
contrib/security/PSS/static/restricted/patches/istio-labels.yaml
contrib/security/PSS/static/restricted/patches/kubeflow-labels.yaml
example/kustomization.yaml

> I enabled pod security standards to namespaces.
---     

Added PSS to contrib/baseline and contrib/restricted as kustomize components

---

README.md
apps/training-operator/upstream/base/crds/kubeflow.org_mpijobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_mxjobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_paddlejobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_pytorchjobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_tfjobs.yaml
apps/training-operator/upstream/base/crds/kubeflow.org_xgboostjobs.yaml
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml
hack/sync-training-operator-manifests.sh

the script had some issues, but i hope it is fine now @rimolive

Synchronize kubeflow training operator manifests from v1.8.0-rc.1

---

.github/workflows/trivy.yaml
hack/trivy_scan.py

> Fixed the requested chnages
---     

Improve the trivy CVE scanning output

---

proposals/20240606-jwt-handling.md

Continuing from the discussion in https://github.com/kubeflow/manifests/issues/2747
After the `oauth2-proxy` PRs are merged we have made some changes on how JWTs are used from within the cluster (`RequestAuthentication`) and how headers are added from these tokens.
This lead to some issues in KFP, for which to resolve we'll need to have an agreed upon story on how to be working in the future with JWTs.
After agreeing on the above, this can also enable us to push the effort for supporting groups since we'll have an agreed upon way of working with identity information.
/cc @juliusvonkohout @kromanow94 @thesuperzapper @axel7083 
cc @rimolive @DnPlas

proposal: Uniform way for handling JWTs

---

README.md
apps/admission-webhook/upstream/base/kustomization.yaml
apps/centraldashboard/upstream/base/kustomization.yaml
apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml
apps/jupyter/jupyter-web-app/upstream/base/kustomization.yaml
apps/jupyter/notebook-controller/upstream/base/kustomization.yaml
apps/profiles/upstream/base/kustomization.yaml
apps/profiles/upstream/overlays/kubeflow/kustomization.yaml
apps/pvcviewer-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboard-controller/upstream/base/kustomization.yaml
apps/tensorboard/tensorboards-web-app/upstream/base/kustomization.yaml
apps/volumes-web-app/upstream/base/kustomization.yaml
hack/synchronize-kubeflow-manifests.sh
tests/gh-actions/kf-objects/notebook.test.kubeflow-user-example.com.yaml
tests/gh-actions/run_and_wait_kubeflow_pipeline.py

Update kubeflow/kubeflow manifests from v1.9.0-rc.1

---

contrib/security/PSS/static/baseline/kustomization.yaml
contrib/security/PSS/static/baseline/patches/cert-manager-labels.yaml
contrib/security/PSS/static/baseline/patches/dex-labels.yaml
contrib/security/PSS/static/baseline/patches/oauth2-proxy-labels.yaml
contrib/security/PSS/static/restricted/kustomization.yaml
contrib/security/PSS/static/restricted/patches/cert-manager-labels.yaml
contrib/security/PSS/static/restricted/patches/dex-labels.yaml
contrib/security/PSS/static/restricted/patches/oauth2-proxy-labels.yaml

> I patched other namespaces in common directory with PSS labels
---     

Patch further static namespaces with PSS labels

---

common/istio-cni-1-22/istio-install/base/install.yaml
hack/synchronize-istio-cni-manifests.sh

> I  added Daemonset back to istio-cni-1-22/istio-install/base/install.yaml and fixed the hack script
---     

Added Daemonset to istio-cni and fixed the script

---

common/networkpolicies/base/kustomization.yaml
common/networkpolicies/base/training-operator-webhook.yaml

I moved the networkpolicies from https://github.com/kubeflow/manifests/pull/2779 into this PR to have it ready for 1.9

networkpolicy for training operator

---

.github/PULL_REQUEST_TEMPLATE.md

Unit Test Checklist and Contributor checklist are done automatically
A brief description of the changes is a duplicated of Please include a summary of changes and the related issue.

Simplify the pull request template

---

apps/katib/upstream/components/controller/trial-templates.yaml
apps/katib/upstream/installs/katib-cert-manager/katib-config.yaml
apps/katib/upstream/installs/katib-cert-manager/kustomization.yaml
apps/katib/upstream/installs/katib-external-db/katib-config.yaml
apps/katib/upstream/installs/katib-external-db/kustomization.yaml
apps/katib/upstream/installs/katib-leader-election/katib-config.yaml
apps/katib/upstream/installs/katib-openshift/katib-config.yaml
apps/katib/upstream/installs/katib-openshift/kustomization.yaml
apps/katib/upstream/installs/katib-standalone-postgres/katib-config.yaml
apps/katib/upstream/installs/katib-standalone-postgres/kustomization.yaml
apps/katib/upstream/installs/katib-standalone/katib-config.yaml
apps/katib/upstream/installs/katib-standalone/kustomization.yaml
apps/katib/upstream/installs/katib-with-kubeflow/kustomization.yaml

As part of Kubeflow 1.9 release, this PR is bumping Katib manifests to v0.17.0
N/A
N/A
---     

Update kubeflow/katib manifests from v0.17.0

---

README.md
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml

As part of the Kubeflow 1.9 release, this PR bumps Training Operator manifests to v1.8.0
N/A
N/A
---     

Update kubeflow/training-operator manifests from v1.8.0

---

example/kustomization.yaml

> I commented out the   _../common/knative/knative-eventing/base_ in [Kustomization.yaml](https://github.com/kubeflow/manifests/blob/master/example/kustomization.yaml) file to deprecate optional Knative Eventing components from common manifests
> [#2685](https://github.com/kubeflow/manifests/issues/2685)
---     
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [**#kubeflow-platform**](https://app.slack.com/client/T08PSQ7BQ/C0 …

 Deprecate optional Knative Eventing components

---

README.md

> I documented on how to change default username and email for dex.
---     

Document how to change the default username for dex

---

contrib/ray/raycluster_example.yaml

> Updated the ray version and enable autoScaling
> #2742 
---     

change ray version and enable auto scaling

---

.github/workflows/dex_test.yaml

---     
@tzabbi follow up of https://github.com/kubeflow/manifests/pull/2815
I see 
```
Run pip3 install requests
pip3 install requests …
```

disable the broken dex login test for now or fix it

---

example/kustomization.yaml

> I added ray and Seldon into kustomization.yaml file
---     

Expose Ray and Seldon to example kustomization.yaml file

---

.github/workflows/dex_test.yaml
tests/gh-actions/deploy-dex-login-environment/kustomization.yaml
tests/gh-actions/test_dex_login.py

> I changed:
- set executable permission for python script
- set shebang line in python script
> My PR depends on #2827
> The following issues are related, because dex login test currently does not work
---     

fix dex-login-test

---

common/oauth2-proxy/components/configure-self-signed-kubernetes-oidc-issuer/cronjob.kubeflow-m2m-oidc-configurator.yaml
contrib/security/PSS/patches/cache-server.yaml
contrib/security/PSS/patches/cluster-local-gateway.yaml
contrib/security/PSS/patches/dex.yaml
contrib/security/PSS/patches/kfam.yaml
contrib/security/PSS/patches/kubeflow-pipelines-profile-controller.yaml
contrib/security/PSS/patches/manager.yaml
contrib/security/PSS/patches/metadata-envoy-deployment.yaml
contrib/security/PSS/patches/metadata-grpc-deployment.yaml
contrib/security/PSS/patches/metadata-writer.yaml
contrib/security/PSS/patches/minio.yaml
contrib/security/PSS/patches/ml-pipeline-persistenceagent.yaml
contrib/security/PSS/patches/ml-pipeline-scheduledworkflow.yaml
contrib/security/PSS/patches/ml-pipeline-ui.yaml
contrib/security/PSS/patches/ml-pipeline-viewer-crd.yaml
contrib/security/PSS/patches/ml-pipeline-visualizationserver.yaml
contrib/security/PSS/patches/ml-pipeline.yaml
contrib/security/PSS/patches/mysql.yaml
contrib/security/PSS/patches/oauth2-proxy.yaml

> I added securityContext for profile-controller containers kfam and manager.
---     

Added securityContext profiles for deployments failing PSS restricted level

---

.github/workflows/trivy.yaml

> I added the new step to upload Trivy results artifacts.
By default, GitHub Actions artifacts are retained for 90 days before they are automatically deleted. However, you can adjust the retention period as needed. For more information, refer to the [GitHub documentation on configuring the retention period for GitHub Actions artifacts and logs](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization).
- Submit the [Contributor License Agreements](https://cla.developers.google.com/clas) …

Adjust the Trivy scanning workflow to upload artifacts

---

common/oauth2-proxy/README.md

> I changed readme doc for oauth2 proxy; 
---     

fix: wrong diagram path for kubeflow auth .

---

.github/workflows/katib_test.yaml
.github/workflows/pipeline_run_from_notebook.yaml

… made a triiger path
> #2797
---     

Consolidate Kubeflow Manifest tests

---

README.md

> I changed README.md
> The following issues are related, because "Install individual components" is not correct.
- After install as  "Install individual components", I can not connect to the central dashboard.
- And this is related closed issue #2800, the message "Cannot get MLMD objects from Metadata store." appeared when I install with "Install individual components" method.
- This update has to be applied to v1.9.0 also, so I will make a PR for v1.9.0
---     
> You can join the …

Updating master README.md for Install individual components

---

README.md
apps/pipeline/upstream/README.md
apps/pipeline/upstream/base/cache-deployer/kustomization.yaml
apps/pipeline/upstream/base/cache/kustomization.yaml
apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml
apps/pipeline/upstream/base/installs/multi-user/istio-authorization-config.yaml
apps/pipeline/upstream/base/installs/multi-user/view-edit-cluster-roles.yaml
apps/pipeline/upstream/base/metadata/base/kustomization.yaml
apps/pipeline/upstream/base/pipeline/kustomization.yaml
apps/pipeline/upstream/base/pipeline/metadata-writer/kustomization.yaml
apps/pipeline/upstream/base/pipeline/ml-pipeline-ui-deployment.yaml
apps/pipeline/upstream/env/aws/README.md
apps/pipeline/upstream/env/gcp/inverse-proxy/kustomization.yaml
apps/pipeline/upstream/env/platform-agnostic-multi-user-legacy/kustomization.yaml
apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml
apps/pipeline/upstream/hack/presubmit.sh
apps/pipeline/upstream/sample/README.md
apps/pipeline/upstream/sample/kustomization.yaml
apps/pipeline/upstream/third-party/argo/base/workflow-controller-configmap-patch.yaml
apps/pipeline/upstream/third-party/argo/base/workflow-controller-deployment-patch.yaml
apps/pipeline/upstream/third-party/argo/upstream/manifests/Kptfile
apps/pipeline/upstream/third-party/argo/upstream/manifests/namespace-install/kustomization.yaml
apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/base/kustomization.yaml
apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/minimal/kustomization.yaml
apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/mysql/kustomization.yaml
apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/postgres/kustomization.yaml
apps/pipeline/upstream/third-party/argo/upstream/manifests/quick-start/sso/kustomization.yaml
hack/synchronize-pipelines-manifests.sh

> I changed KFP version to 2.3.0
> The following issues are related, because synchronizing manifests with KFP 2.3.0
---     

Update kubeflow/pipelines manifests from 2.3.0

---

README.md
apps/model-registry/upstream/README.md
hack/synchronize-model-registry-manifests.sh

@lampajr @rimolive Did you change the manifest structure? because i do not see any real changes.

Synchronize kubeflow model registry manifests v0.2.5 alpha

---

.github/workflows/pss_test.yaml
contrib/security/PSS/patches/cache-server.yaml
contrib/security/PSS/patches/kfam.yaml
contrib/security/PSS/patches/kubeflow-pipelines-profile-controller.yaml
contrib/security/PSS/patches/manager.yaml
contrib/security/PSS/patches/metacontroller.yaml
contrib/security/PSS/patches/metadata-envoy-deployment.yaml
contrib/security/PSS/patches/metadata-grpc-deployment.yaml
contrib/security/PSS/patches/metadata-writer.yaml
contrib/security/PSS/patches/minio.yaml
contrib/security/PSS/patches/ml-pipeline-persistenceagent.yaml
contrib/security/PSS/patches/ml-pipeline-scheduledworkflow.yaml
contrib/security/PSS/patches/ml-pipeline-ui.yaml
contrib/security/PSS/patches/ml-pipeline-viewer-crd.yaml
contrib/security/PSS/patches/ml-pipeline-visualizationserver.yaml
contrib/security/PSS/patches/ml-pipeline.yaml
contrib/security/PSS/patches/mysql.yaml
contrib/security/PSS/patches/oauth2-proxy.yaml
contrib/security/PSS/patches/workflow-controller.yaml
tests/gh-actions/install_istio-cni.sh

> I pushed a PR just to view workflows here in CICD
---     

Debugging warnings in pss workflow

---

contrib/spark/spark-operator/base/aggregated-roles.yaml

This PR expands the existing Spark RBAC (Role-Based Access Control) to include support for `ScheduledSparkApplication` resources. Previously, the RBAC configuration only covered `SparkApplication` resources, which limited the ability to manage scheduled jobs effectively. 
- Added necessary RBAC rules for `ScheduledSparkApplication` resources, including permissions for `get`, `list`, `watch`, `create`, `update`, `delete`, and `patch`.
- Updated existing ClusterRole and Role bindings to ensure scheduled Spark jobs have appropriate access.
The absence of RBAC permissions for `ScheduledSparkApplication` resulted in failed scheduled job executions, as the service account lacked the required permissions. By extending the RBAC, we ensure that scheduled Spark jobs are managed securely and can …

fix: expand spark rbac to include scheduledsparkapplication

---

README.md

> I changed the README file to update the Central Dashboard component installation dir
> N/A
> N/A
---     

Running command in README errors, upstream folder does not exist

---

README.md
apps/model-registry/upstream/base/kustomization.yaml
hack/synchronize-model-registry-manifests.sh

> I upgraded model registry to v0.2.9
---     

Synchronize kubeflow model registry manifests v0.2.9

---

README.md

updated README FILE to:
-  update kustomize link
- remove kubeflow tekton pipelines from table
Resolves issue https://github.com/kubeflow/manifests/issues/2902)

update Readme file to fix Kustomize links and Tekton pipelines information

---

README.md
contrib/kserve/kserve/kserve-cluster-resources.yaml
contrib/kserve/kserve/kserve.yaml
contrib/kserve/kserve/kserve_kubeflow.yaml
hack/synchronize-kserve-kserve-manifests.sh
tests/gh-actions/install_kserve.sh

@tarekabouzeid @rimolive for a /lgtm

Synchronize kserve manifests v0.14.0

---

README.md
apps/model-registry/upstream/base/kustomization.yaml
apps/model-registry/upstream/options/csi/clusterstoragecontainer.yaml
apps/model-registry/upstream/options/csi/kustomization.yaml
hack/synchronize-model-registry-manifests.sh

> I upgraded model registry to v0.2.10
---     

feat: synchronize kubeflow model registry manifests to v0.2.10

---

README.md

@tarekabouzeid please review
supersedes https://github.com/kubeflow/manifests/pull/2888 @choudhryfrompak

Dex,oauth2-proxy and k8s token documentation

---

common/dex/base/deployment.yaml
common/oauth2-proxy/base/kustomization.yaml

@tarekabouzeid for /lgtm
- https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.7.1
- https://github.com/dexidp/dex/releases/tag/v2.41.1
- https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml
- https://github.com/dexidp/dex/pkgs/container/dex/254808321?tag=v2.41.1
- https://quay.io/repository/oauth2-proxy/oauth2-proxy?tab=tags&tag=v7.7.1
- https://github.com/kubeflow/manifests/pull/2710/files

Update Dex and oauth2-proxy to 2.41.1 and 7.7.1

---

.github/workflows/linting_bash_python_yaml_files.yaml
.github/workflows/pipeline_run_from_notebook.yaml
README.md
changed_files_in_PR.txt
common/knative/README.md
common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
common/knative/knative-eventing/base/upstream/eventing-core.yaml
common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
common/knative/knative-serving/base/upstream/net-istio.yaml
common/knative/knative-serving/base/upstream/serving-core.yaml
hack/synchronize-knative-manifests.sh
tests/gh-actions/install_knative-cni.sh
tests/gh-actions/install_knative.sh

@tarekabouzeid lets see what my tests say :-D

Synchronize knative manifests v1.16.0

---

README.md

> I changed the README, single component installation section and corrected the bash script for cert-manager component. 
> it does not depend on anything.
> No related issue or PR.
---     

fix cert-manager wrong path in standalone installation section

---

README.md
apps/pipeline/upstream/hack/presubmit.sh
contrib/ray/README.md
tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh
tests/gh-actions/install_kustomize.sh

closes https://github.com/kubeflow/manifests/issues/2796
---     

kustomize 5.4.3 and documentation updates

---

contrib/ray/kuberay-operator/overlays/kubeflow/disable-injection.yaml
contrib/ray/kuberay-operator/overlays/kubeflow/kustomization.yaml
contrib/ray/test.sh

When istio is enabled, the kuberay-operator must disable the init container injection.
See https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/istio.html#step-3-optional-enable-istio-mtls-strict-mode
The kubeflow overlay will disable the init container injection.
#2907 
---     
> You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here …

Disable init container injection for ray

---

.github/workflows/pipeline_swfs_test.yaml
.github/workflows/pipeline_test.yaml
README.md
tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh

Kubernetes 1.32 and kind 0.26

---

README.md

This fixes the installation command for PVC Viewer Controller in README.md.
This does not depend on anything.
This fixes #2945 .
---     

Fix command for PVC Viewer Controller in README.md

---

README.md
apps/training-operator/upstream/overlays/kubeflow/kustomization.yaml
apps/training-operator/upstream/overlays/standalone/kustomization.yaml
hack/synchronize-training-operator-manifests.sh

Update kubeflow/training-operator manifests from v1.9.0

---

README.md
tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh

Follow the install instructions  👉🏻： https://github.com/kubeflow/manifests?tab=readme-ov-file#install-with-a-single-command
but the `cluster-jwks-proxy` not works due to the wrong config for kind cluster, the `kubernetes.default.svc` issuer should be corrected as `https://kubernetes.default.svc`
None
#2963 
---     
> You can join the CNCF Slack and access our meetings at the [Kubeflow …

fix: update kind config

---

common/networkpolicies/README.md
common/oauth2-proxy/README.md
contrib/ray/README.md
contrib/ray/kuberay-operator/base/kustomization.yaml

- Continue implementation from #2885
---     

Fix raycluster Readme

---

.github/workflows/model_registry_test.yaml
apps/model-registry/upstream/README.md
apps/model-registry/upstream/base/kustomization.yaml
apps/model-registry/upstream/options/csi/kustomization.yaml
apps/model-registry/upstream/options/ui/base/kustomization.yaml
apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
apps/model-registry/upstream/options/ui/base/model-registry-ui-role.yaml
apps/model-registry/upstream/options/ui/base/model-registry-ui-service-account.yaml
apps/model-registry/upstream/options/ui/base/model-registry-ui-service.yaml
apps/model-registry/upstream/options/ui/overlays/integrated/kustomization.yaml
apps/model-registry/upstream/options/ui/overlays/integrated/model-registry-ui-deployment.yaml
apps/model-registry/upstream/options/ui/overlays/istio/authorization-policy-ui.yaml
apps/model-registry/upstream/options/ui/overlays/istio/destination-rule-ui.yaml
apps/model-registry/upstream/options/ui/overlays/istio/kustomization.yaml
apps/model-registry/upstream/options/ui/overlays/istio/model-registry-ui-service.yaml
apps/model-registry/upstream/options/ui/overlays/istio/virtual-service.yaml
apps/model-registry/upstream/options/ui/overlays/standalone/kubeflow-dashboard-rbac.yaml
apps/model-registry/upstream/options/ui/overlays/standalone/kustomization.yaml
apps/model-registry/upstream/options/ui/overlays/standalone/model-registry-ui-deployment.yaml
apps/model-registry/upstream/overlays/db/kustomization.yaml
apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
hack/synchronize-model-registry-manifests.sh

Updated KF manifests for MR following most recent release update
none
for KF 1.10 RC builds
---     

Update kubeflow/model-registry manifests from 5d8ed91

---

common/networkpolicies/base/kustomization.yaml
common/networkpolicies/base/model-registry-ui.yaml

This PR adds model registry ui network policy. It's a blocker to include Model Registry UI.
No dependencies
No dependencies
---     

Add model registry ui network policy

---

contrib/kserve/models-web-app/base/kustomization.yaml
contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml

fix warnings after kustomize build in contrib

---

README.md
apps/model-registry/upstream/README.md
apps/model-registry/upstream/base/kustomization.yaml
apps/model-registry/upstream/base/model-registry-deployment.yaml
apps/model-registry/upstream/options/csi/kustomization.yaml
apps/model-registry/upstream/options/ui/base/kustomization.yaml
apps/model-registry/upstream/options/ui/base/model-registry-ui-deployment.yaml
apps/model-registry/upstream/options/ui/overlays/istio/kustomization.yaml
apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
apps/model-registry/upstream/overlays/postgres/kustomization.yaml
apps/model-registry/upstream/overlays/postgres/model-registry-db-deployment.yaml
apps/model-registry/upstream/overlays/postgres/patches/model-registry-deployment.yaml
hack/synchronize-model-registry-manifests.sh

1. make script BSD/MacOSX compatible (e1dcefeab598d13a629fb722f838fa654b20b63a)
2. update the manifests
- include [this request](https://github.com/kubeflow/manifests/pull/2973#issuecomment-2645813716) to make sure to update the readme
- include [this request](https://github.com/kubeflow/manifests/pull/2973#issuecomment-2636264568) to add securityContext
none related
none related
---     

Synchronize kubeflow model registry manifests v0.2.14

---

.pre-commit-config.yaml
contrib/spark/test.sh
tests/gh-actions/install_knative-cni.sh
tests/gh-actions/install_knative.sh

- Added pre-commit configuration for code quality checks
- Integrated existing linters into pre-commit:
- black for Python formatting
- yamllint for YAML validation
- shellcheck for shell script analysis
- Fixed shellcheck some warnings
- To use these checks locally:
- Install pre-commit: `pip install pre-commit`
-  Set up the git hooks: `pre-commit install`
The checks will now run automatically on `git commit`, or you can run manually:
- part of #2797
---     

feat: Add pre-commit hooks for automated code quality checks

---

.github/workflows/model_registry_test.yaml

Fix for https://github.com/kubeflow/manifests/issues/2984
- Add integration test for MR UI
---     

Add Model Registry UI Integration Test

---

README.md

- added a section for pre-commit in the README
- made some minor improvements in README
- https://github.com/kubeflow/manifests/pull/3001#issuecomment-2666067349
---     

Add a section for pre-commit in README.md

---

README.md
common/knative/README.md
common/knative/knative-eventing-post-install-jobs/base/eventing-post-install.yaml
common/knative/knative-eventing/base/upstream/eventing-core.yaml
common/knative/knative-eventing/base/upstream/in-memory-channel.yaml
common/knative/knative-eventing/base/upstream/mt-channel-broker.yaml
common/knative/knative-serving-post-install-jobs/base/serving-post-install-jobs.yaml
common/knative/knative-serving/base/upstream/serving-core.yaml
hack/synchronize-knative-manifests.sh

Update common/knative manifests to v1.16.2/v1.16.4.
Fixes #3016, replaces #3020.
---     

Update common/knative manifests to v1.16.2/v1.16.4.

---

apps/pipeline/upstream/third-party/mysql/base/mysql-deployment.yaml

* Add a pod `securityContext` that sets `fsGroup` and `fsGroupChangePolicy` so that volumes from previous versions of Kubeflow have their file permissions seamlessly changed to match the security context on upgrade.
* Change `runAsUser` and `runAsGroup` to 999 to match `mysql` user in container.
Fixes #3018.
---     

Pipelines MySQL volume permissions fix

---

apps/pipeline/upstream/third-party/minio/base/minio-deployment.yaml

This change will will make Kubernetes automatically set the correct ownership of the mounted volumes to be accessible by `user 1000`
fixes #3040 
---     

fix(pipeline): minio filesystem permission access error

---

README.md
common/istio-cni-1-24/istio-install/base/install.yaml
tests/gh-actions/install_KinD_create_KinD_cluster_install_kustomize.sh

Kind 0.27 https://github.com/kubernetes-sigs/kind/releases/tag/v0.27.0 with
But Kubernetes 1.30 is already [End of Life](https://kubernetes.io/releases/#release-history) by 2025-06-28, so we strongly recommend to upgrade to 1.31+. We also tested that native sidecars work on AKS and GKE 1.31+. Kubernetes 1.33 is planned for release on April 23 2025, so we would support 1.31-1.33 and down to 1.29 with native sidecars workarounds.

Update Kind and test Kubernetes 1.29-1.32

---

README.md
apps/model-registry/upstream/base/kustomization.yaml
apps/model-registry/upstream/base/model-registry-deployment.yaml
apps/model-registry/upstream/options/csi/clusterstoragecontainer.yaml
apps/model-registry/upstream/options/csi/kustomization.yaml
apps/model-registry/upstream/options/ui/base/kustomization.yaml
apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
apps/model-registry/upstream/overlays/postgres/model-registry-db-deployment.yaml

Followup [nano v0.2.15.3 release](https://github.com/kubeflow/model-registry/releases/tag/v0.2.15.3) to support the migration to `ghcr.io` as requested, it also include the istio label change requested.
Special thanks to @madmecodes , @mahdikhashan , for their contributions.
n/a
- https://github.com/kubeflow/manifests/issues/3010
- https://github.com/kubeflow/manifests/issues/2798
---     
this superseeds https://github.com/kubeflow/manifests/pull/3065

Update kubeflow/model-registry manifests from v0.2.15.3

---

.github/workflows/model_registry_test.yaml

amend the existing dry-run testing,
by fixing to avoid a duplicate step name,
by having a "debug hook" in case one await fails
so to get some indications on the reasons for the
awaited failure
n/a
n/a
- [n/a] I have tested these changes with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites).
---     
cc @lucferbux @Al-Pragliola

test: fix name, debug hooks

---

common/istio-1-24/cluster-local-gateway/base/gateway-authorizationpolicy.yaml
common/istio-cni-1-24/cluster-local-gateway/base/gateway-authorizationpolicy.yaml

Revert OAuth2 authentication policy for cluster-local-gateway
---     

Fix: Revert OAuth2 authentication policy for cluster-local-gateway

---

.github/workflows/dex_oauth2-proxy_test.yaml
README.md
experimental/ray/test.sh
tests/gh-actions/install_cert_manager.sh
tests/gh-actions/install_oauth2-proxy.sh

Kubernetes API conditions are case-sensitive and standard
pod conditions use capitalized names. This changes all
instances of "--for=condition=ready" to "--for=condition=Ready"
to ensure consistent behavior across installation scripts.
none
none
---     

Fix: kubectl wait condition case from ready to Ready

---

.github/workflows/full_kubeflow_integration_test.yaml

GitHub Actions workflow implements full end-to-end integration testing for Kubeflow deployment. The workflow automates testing of critical Kubeflow components, including authentication, pipelines, notebooks, and machine learning services. 
> Fix #3054 
---     

Add comprehensive Kubeflow integration test GitHub Actions workflow

---

common/oauth2-proxy/overlays/m2m-dex-and-kind/kustomization.yaml

Different Kubernetes distributions and configurations may use
either format for service account tokens. This fix ensures
M2M authentication works across all environments by adding
a second JWT rule to the RequestAuthentication.
This change adds support for both JWT issuer formats:
- https://kubernetes.default.svc.cluster.local
- https://kubernetes.default.svc
Fixes issue where service account tokens fail with:
**"Jwt issuer is not configured" error.**
I was facing this issue, in my kind cluster, default _kubectl apply -k common/oauth2-proxy/overlays/m2m-dex-and-kind_ was using kubernetes.default.svc.cluster.local as issuer giving me Jwt issuer is not configured" error on curl, 
fixed by adding this as issuer, in patch of kustomizatin https://kubernetes.default.svc and fixed the issue. …

fix: Fixes issue where service account tokens fail with: "Jwt issuer is not configured" error.

---

.github/workflows/kserve_m2m_test.yaml
apps/kserve/tests/utils.py
common/knative/knative-serving/overlays/gateways/patches/config-domain.yaml
tests/gh-actions/install_knative-cni.sh
tests/gh-actions/install_knative.sh

Removed KServe DNS patches from GitHub Actions tests, as they were already added as a patch, see https://github.com/kubeflow/manifests/pull/3084
Follow up to PR: https://github.com/kubeflow/manifests/pull/3084
none
---     

Removed KServe DNS patches from GitHub Actions tests

---

.github/workflows/dex_oauth2-proxy_test.yaml
tests/gh-actions/test_dex_login.py

1. Make the Dex test more robust (fix flakiness)
**403 Handling - When receiving a 403 Forbidden response during login, we attempt to restart the OAuth flow, which helps when sessions expire.**
```
kubectl run load-test --image=busybox --restart=Never -- /bin/sh -c "while true; do wget -q -O- http://localhost:8080; done"
```
You will get this:
After implementing 403 handling:
```
if resp.status_code == 403:
oauth_url = f"{urlsplit(self._endpoint_url).scheme}://{urlsplit(self._endpoint_url).netloc}/oauth2/start"
resp = s.get(
oauth_url,
headers=headers,
allow_redirects=True,
verify=not self._skip_tls_verify,
timeout=30
)
if resp.status_code == 200:
if s.cookies:
return "; ".join([f"{c.name}={c.value}" for c in s.cookies])
```
Successfully passed, after main 403 retry. (load test pod still …

Fix: flaky Dex login test by improving authentication flow handling

---

.github/workflows/full_kubeflow_integration_test.yaml
.github/workflows/manifests_example_test.yaml
.github/workflows/stale.yaml
.github/workflows/trivy.yaml

disables the GHA runs in forked repo
fixes #3095 
---     

fix: disable GHA in forked repo

---

tests/gh-actions/install_kserve.sh

> Added a check to wait for the Certificate resource for the kserve
---     

Fixed the cert manager readiness for kserve

---

apps/kserve/kserve/kustomization.yaml
tests/gh-actions/enable_baseline_PSS.sh
tests/gh-actions/enable_restricted_PSS.sh
tests/gh-actions/install_kserve.sh

> Updates the behavior of the PSS (Pod Security Standards) baseline  tests. 
> The tests will now fail immediately upon detecting a policy violation.
---     

Enforce failure on PSS baseline test violations

---

apps/kserve/kserve/kustomization.yaml
common/knative/knative-serving/base/kustomization.yaml
common/knative/knative-serving/base/patches/seccomp.yaml

- Added patch to insert `seccompProfile` in several knative-serving deployments
- #3015
---     

Fix knative-serving PSS warnings

---

scripts/library.sh

Previously, we updated the sync script to run effectively on Mac OSX, ie BSD `sed`:
https://github.com/kubeflow/manifests/blob/c1ae849873a36199af43c4e14d113bd60fc695d7/scripts/synchronize-model-registry-manifests.sh#L64
since the refactor to use a "common library", here:
https://github.com/kubeflow/manifests/blob/53724ce69fca11951158c2a5374e5a4b2fa15b08/scripts/library.sh#L81
the missing extension to the `-i` parameter works for GNU `sed`, but making it fail again for BSD `sed`.
Kindly consider this modification which shall be compatible for both.
none applicable
none applicable
- [n/a] I have tested these changes with kustomize. See [Installation Prerequisites](https://github.com/kubeflow/manifests#prerequisites).
---     
> You can join the CNCF Slack and access our meetings at the …

fix: make again script runnable on Mac OSX

---

.github/workflows/full_kubeflow_integration_test.yaml
.github/workflows/pipeline_test.yaml
tests/gh-actions/kserve/requirements.txt
tests/gh-actions/test_pipeline_v1.py

> Added KFP v1 SDK (>=1.8.22,<2.0.0) pipeline test to CI workflow
> Create simple hello world V1 pipeline test script
---     

Add KFP V1 Pipeline Test to CI Workflow

---

.github/workflows/pipeline_run_from_notebook.yaml
.github/workflows/pipeline_test.yaml

- use istio-cni in the pipelines gha
- split changes from https://github.com/kubeflow/manifests/pull/3050
---     

Use istio cni in pipelines gha

---

apps/admission-webhook/upstream/base/deployment.yaml
apps/centraldashboard/upstream/base/deployment.yaml
apps/katib/upstream/components/controller/controller.yaml
apps/katib/upstream/components/db-manager/db-manager.yaml
apps/katib/upstream/components/mysql/mysql.yaml
apps/katib/upstream/components/postgres/postgres.yaml
apps/katib/upstream/components/ui/ui.yaml
apps/katib/upstream/installs/katib-with-kubeflow/patches/istio-sidecar-injection.yaml
apps/kserve/kserve/kserve_kubeflow.yaml
apps/kserve/models-web-app/overlays/kubeflow/patches/web-app-sidecar.yaml
apps/model-registry/upstream/base/model-registry-deployment.yaml
apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
apps/model-registry/upstream/overlays/postgres/model-registry-db-deployment.yaml
apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
apps/pipeline/upstream/base/metadata/base/metadata-envoy-deployment.yaml
apps/pipeline/upstream/base/metadata/overlays/db/metadata-db-deployment.yaml
apps/pipeline/upstream/base/metadata/overlays/postgres/metadata-db-deployment.yaml
apps/pipeline/upstream/third-party/metacontroller/base/stateful-set.yaml
apps/profiles/upstream/manager/manager.yaml
apps/profiles/upstream/overlays/kubeflow/patches/kfam.yaml
apps/spark/spark-operator/base/kustomization.yaml
apps/spark/sparkapplication_example.yaml
apps/training-operator/upstream/base/deployment.yaml
common/knative/knative-serving/base/patches/sidecar-injection.yaml
tests/gh-actions/kf-objects/training_operator_job.yaml

This PR fixes Istio sidecar injection by moving control from annotations to labels across all manifests, following Istio best practices documentation.
No dependencies on other PRs.
Fixes #2798
---     

Fix Istio sidecar injection by moving from annotations to labels

---

common/knative/knative-serving/base/kustomization.yaml
tests/gh-actions/enable_baseline_PSS.sh
tests/gh-actions/enable_restricted_PSS.sh

- Modified PSS enable scripts to apply pss labels from diectly PSS enable scripts
- working on fixing `knative-serving` pss warning
---     

Apply pss labels from diectly PSS enable scripts

---

.github/workflows/pipeline_swfs_test.yaml

The test_pipeline.py has been changed to test_pipeline_v2.py in https://github.com/kubeflow/manifests/pull/3129
---     

The test_pipeline.py has been changed to test_pipeline_v2.py

---

.github/workflows/full_kubeflow_integration_test.yaml
.github/workflows/model_registry_test.yaml
README.md
apps/model-registry/upstream/README.md
apps/model-registry/upstream/base/kustomization.yaml
apps/model-registry/upstream/base/model-registry-deployment.yaml
apps/model-registry/upstream/options/csi/kustomization.yaml
apps/model-registry/upstream/options/istio/kustomization.yaml
apps/model-registry/upstream/options/ui/base/kustomization.yaml
apps/model-registry/upstream/overlays/db/kustomization.yaml
apps/model-registry/upstream/overlays/db/model-registry-db-deployment.yaml
apps/model-registry/upstream/overlays/db/patches/model-registry-deployment.yaml
apps/model-registry/upstream/overlays/postgres/kustomization.yaml
apps/model-registry/upstream/overlays/postgres/patches/model-registry-deployment.yaml

periodic sync following the MR release
n/a
n/a
---     

Update kubeflow/model-registry manifests from v0.2.18

---

README.md

This PR corrects an issue in the Dex configuration example within the [Dex section](https://github.com/kubeflow/manifests?tab=readme-ov-file#dex) of `README.md`. 
The example Dex configuration with Azure OIDC connector currently specifies:
* `issuer`: `http://dex.auth.svc.cluster.local:5556/dex`
* `connectors[0].config.redirectURI`: `https://$KUBEFLOW_INGRESS_URL/dex/callback`
This configuration creates a mismatch because Dex expects the callback URL to be `${issuer}/callback`. A typical error message resulting from this misconfiguration is:
```
connector returned error when creating callback" connector_id=azure err="expected callback URL \"http://dex.auth.svc.cluster.local:5556/dex/callback\" did not match the URL in the config \"https://$KUBEFLOW_INGRESS_URL/dex/callback\"
```
To …

Correct Dex's issuer in README config example

---

tests/kserve/utils.py

The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
---     

Modernize logger interface

---

apps/profiles/pss/kustomization.yaml
apps/profiles/pss/namespace-labels.yaml
example/kustomization.yaml
tests/multi_tenancy_install.sh

- Follow up PR https://github.com/kubeflow/manifests/pull/3150
---     

Move dynamic PSS baseline patch to `apps/profiles/`

---

tests/kserve_test.sh

Problem Statement
Input: User request to implement path-based routing for KServe inference services
Requirement: Enable custom URL paths like /serving/namespace/service/v1/models/... to route to KServe services
**Original**
Client → istio-ingressgateway → isvc-sklearn-predictor-ingress VS → Service
**New Path-Based Flow**
Client → istio-ingressgateway → kserve-path-gateway → kserve-path-routing VS → knative-local-gateway → Service
First Attempt: Direct VirtualService
**FAILED APPROACH**
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
name: test-path-routing
spec:
hosts: ["*"]  # Problem: Too broad
gateways: ["kubeflow/kubeflow-gateway"]  # Problem: Conflicts with existing
```
**Issues Encountered:**
1. VirtualService Conflicts: Existing KServe VirtualServices …

KServe Path-Based Routing Implementation

---

.github/workflows/full_kubeflow_integration_test.yaml

- Add pipelines swfs test to full_kubeflow_integration_test.yaml
- part of https://github.com/kubeflow/manifests/issues/3119
---     

Add swfs test to full_kubeflow_integration_test.yaml

---

.github/workflows/full_kubeflow_integration_test.yaml
tests/training_operator_test.sh

Switch to large oracle runners

---

applications/katib/upstream/components/controller/rbac.yaml
experimental/helm/charts/katib/templates/controller/rbac.yaml

Adding TrainJob support to Katib Trial Templates.
https://github.com/kubeflow/katib/pull/2560
---     

TrainJob support to Katib Trial Templates

---

common/networkpolicies/base/cert-manager-webhook.yaml
common/networkpolicies/base/default-allow-same-namespace-auth.yaml
common/networkpolicies/base/default-allow-same-namespace-cert-manager.yaml
common/networkpolicies/base/default-allow-same-namespace-istio-system.yaml
common/networkpolicies/base/default-allow-same-namespace-knative-serving.yaml
common/networkpolicies/base/default-allow-same-namespace-oauth2-proxy.yaml
common/networkpolicies/base/kustomization.yaml

> Add Default Deny All the NetworkPolicy for rest of namespaces like knative-serving, oauth2-proxy, cert-manager, auth, istio-system similar to already implemented kubeflow and kubeflow-system.
> #3227 
---     

Deny All Network Policies for the namespaces knative-serving oauth2-proxy cert-manager istio-system auth

---

.github/workflows/helm-kustomize-comparison.yml

> Update the helm tests to be non blocking when a manifests are updated.
> #3232 
---     

Make Helm Comparision Tests Non Blocking
